//===- POPOps.cpp ---------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file implements the POP dialect operations.
//
//===----------------------------------------------------------------------===//

#include "KGEN/POPDialect/POPOps.h"
#include "KGEN/KGENDialect/KGENParameters.h"
#include "KGEN/POPDialect/POPDialect.h"

using namespace M;
using namespace KGEN;
using namespace mlir;

//===----------------------------------------------------------------------===//
// ConstantOp
//===----------------------------------------------------------------------===//

void ConstantOp::getAsmResultNames(
    function_ref<void(Value, StringRef)> setNameFn) {
  setNameFn(getResult(), "cst");
}

LogicalResult ConstantOp::verify() {
  auto valueType = getValue().dyn_cast<TypedAttr>().getType();
  // The value type should be a scalar type.
  if (!isBuildableWith(getValue(), valueType))
    return emitError(
        "constant has to be either an integer, float or index type");

  // The return type should be a meta scalar which is compatible with the input
  // value type or can be parameterized.
  auto resultDType = getType().cast<ScalarType>().getDtype();

  if (auto resultConstantDType = resultDType.dyn_cast<DTypeConstantAttr>()) {
    if (!resultConstantDType.isCompatibleWith(valueType))
      return emitOpError()
             << "expected the type of the constant input value (" << valueType
             << ") to be compatible with the dtype of the return value ('"
             << resultConstantDType.getDType().getAsString() << "').";
    else
      return success();
  } else if (resultDType.isa<ParamDeclRefAttr>()) {
    return success();
  }

  llvm::report_fatal_error("unhandled output type");
}

bool ConstantOp::isBuildableWith(Attribute value, Type type) {
  return type.isa<IntegerType, FloatType, IndexType>();
}

OpFoldResult ConstantOp::fold(ArrayRef<Attribute> operands) {
  assert(operands.empty() && "constant has no operands");
  return getValue();
}

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "KGEN/POPDialect/POP.cpp.inc"
