load("//utils/bazel/build/rules:globals_library.bzl", "globals_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "CompilerSupportHeaders",
    hdrs = glob([
        "include/LLCL/CompilerSupport/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":RuntimeHeaders",
        "//Support:Threading",
    ],
)

cc_library(
    name = "RuntimeHeaders",
    hdrs = glob([
        "include/LLCL/Runtime/*.h",
        "include/LLCL/Runtime/Globals/*.h",
    ]) + [
        "include/LLCL/ForwardDecls.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:private"],
    deps = [
        ":SupportHeaders",
        "//Support:ProfilingHeaders",
    ],
)

cc_library(
    name = "SupportHeaders",
    hdrs = glob(["include/LLCL/Support/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:private"],
)

cc_library(
    name = "CompilerSupport",
    srcs = glob(["lib/CompilerSupport/*.cpp"]),
    hdrs = glob(["include/LLCL/CompilerSupport/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Runtime",
    ],
)

cc_library(
    name = "Runtime",
    srcs = glob(["lib/Runtime/*.cpp"]),
    hdrs = glob([
        "include/LLCL/Runtime/Globals/*.h",
        "include/LLCL/Runtime/*.h",
    ]) + [
        "include/LLCL/ForwardDecls.h",
    ],
    local_defines = select({
        "@platforms//os:linux": ["MODULAR_HAVE_SEM_TIMEDWAIT"],
        "//conditions:default": [],
    }),
    strip_include_prefix = "include",
    deps = [
        ":RuntimeHeaders",
        ":Support",
        "//Support:ADT",
        "//Support:Profiling",
    ],
)

globals_library(
    name = "RuntimeGlobals",
    srcs = glob(["lib/Runtime/Globals/*.cpp"]),
    deps = [
        ":CompilerSupport",
        ":RuntimeHeaders",
        ":SupportHeaders",
        "//Support:Base",
        "//Support:Profiling",
        "//Support:SymbolExport",
        "@llvm-project//llvm:Support",
    ],
)

cc_library(
    name = "Support",
    srcs = glob(["lib/Support/*.cpp"]),
    hdrs = glob(["include/LLCL/Support/*.h"]),
    local_defines = select({
        "//:llcl_no_affinity_setting": ["LLCL_NO_AFFINITY"],
        "//conditions:default": [],
    }),
    strip_include_prefix = "include",
    deps = [
        "//Support:MArchTarget",
        "//Support:Threading",
    ],
)
