load("//bazel:api.bzl", "modular_cc_test")

modular_cc_test(
    name = "AsyncValueTest",
    srcs = ["AsyncValueTest.cpp"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "@com_github_google_googletest//:gtest_main",
    ],
)

modular_cc_test(
    name = "DebuggingAllocatorsTest",
    srcs = ["DebuggingAllocatorsTest.cpp"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "@com_github_google_googletest//:gtest_main",
    ],
)

modular_cc_test(
    name = "ResourceTest",
    srcs = ["ResourceTest.cpp"],
    deps = [
        "//LLCL:Support",
        "@com_github_google_googletest//:gtest_main",
    ],
)

modular_cc_test(
    name = "RuntimeTest",
    srcs = ["RuntimeTest.cpp"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "@com_github_google_googletest//:gtest_main",
    ],
)

modular_cc_test(
    name = "TypeIDTest",
    srcs = ["TypeIDTest.cpp"],
    deps = [
        "//LLCL:Support",
        "//Support:Base",
        "//Support:Globals",
        "@com_github_google_googletest//:gtest_main",
    ],
)

modular_cc_test(
    name = "TimerHeapTest",
    srcs = ["TimerHeapTest.cpp"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//LLCL:Support",
        "//Support:Globals",
        "@com_github_google_googletest//:gtest_main",
    ],
)
