load("//bazel:api.bzl", "modular_cc_test")

modular_cc_test(
    name = "AllocatorTest",
    srcs = ["AllocatorTest.cpp"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "AsyncValueTest",
    srcs = ["AsyncValueTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "DebuggingAllocatorsTest",
    srcs = ["DebuggingAllocatorsTest.cpp"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "ResourceTest",
    srcs = ["ResourceTest.cpp"],
    deps = ["//LLCL:Support"],
)

modular_cc_test(
    name = "RuntimeTest",
    srcs = ["RuntimeTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "TypeIDTest",
    srcs = ["TypeIDTest.cpp"],
    deps = [
        "//LLCL:Support",
        "//Support:Base",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "TimerHeapTest",
    srcs = ["TimerHeapTest.cpp"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//LLCL:Support",
        "//Support:Globals",
    ],
)
