load("//bazel:api.bzl", "modular_cc_library")

# gazelle:default_visibility //visibility:public

package(default_visibility = ["//visibility:public"])

modular_cc_library(
    name = "Init",
    srcs = [
        "lib/DevelopmentSignalHandler.cpp",
        "lib/Init.cpp",
    ],
    hdrs = [
        "include/Init/DevelopmentSignalHandler.h",
        "include/Init/Init.h",
    ],
    deps = [
        "//AsyncRT:Runtime",
        "//Config",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:Context",
        "//Support:CrashReporting",
        "//Support:HTTP",
        "//Support:MArchTarget",
        "//Support:MArchTargetMinimal",
        "//Support:Telemetry",
        "@llvm-project//llvm:Support",
    ],
)
