load("@llvm-project//mlir:tblgen.bzl", "gentbl_cc_library", "td_library")
load("//utils/bazel/build/rules:expand_root_cert_inc.bzl", "expand_root_cert_inc")
load("//utils/bazel/build/rules:globals_library.bzl", "globals_library")
load("//utils/bazel/build/rules:tablegen.bzl", "gentbl_mlir_dialect")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

cc_library(
    name = "SymbolExport",
    hdrs = [
        "include/Support/SymbolExport.h",
    ],
    strip_include_prefix = "include",
)

cc_library(
    name = "Base",
    srcs = [
        "lib/AlignedAlloc.cpp",
        "lib/BuildInfo.cpp",
        "lib/Config.cpp",
        "lib/Error.cpp",
        "lib/ErrorOr.cpp",
        "lib/IPInt.cpp",
        "lib/IPRational.cpp",
        "lib/Process.cpp",
        "lib/Progress.cpp",
        "lib/Random.cpp",
        "lib/ReferenceCounted.cpp",
        "lib/Version.cpp",
    ],
    hdrs = [
        "include/Support/AlignedAlloc.h",
        "include/Support/Binary.h",
        "include/Support/BuildInfo.h",
        "include/Support/CommandLine.h",
        "include/Support/Config.h",
        "include/Support/Context.h",
        "include/Support/Error.h",
        "include/Support/ErrorOr.h",
        "include/Support/ForwardDecls.h",
        "include/Support/FunctionExtras.h",
        "include/Support/IPInt.h",
        "include/Support/IPRational.h",
        "include/Support/LLVMCompilerForwardDecls.h",
        "include/Support/LLVMForwardDecls.h",
        "include/Support/LLVMYAMLForwardDecls.h",
        "include/Support/LogicalResult.h",
        "include/Support/MathExtras.h",
        "include/Support/PlatformUtils.h",
        "include/Support/Preprocessor.h",
        "include/Support/Process.h",
        "include/Support/Progress.h",
        "include/Support/RCRef.h",
        "include/Support/Random.h",
        "include/Support/ReferenceCounted.h",
        "include/Support/STLExtras.h",
        "include/Support/SymbolExport.h",
        "include/Support/TypeID.h",
        "include/Support/Version.h",
    ],
    strip_include_prefix = "include",
    deps = [
        "//Config",
        "@llvm-project//mlir:Pass",
        "@llvm-project//mlir:Support",
    ],
)

cc_test(
    name = "BaseTest",
    srcs = [
        "unittests/AlignedAllocTest.cpp",
        "unittests/BufferTest.cpp",
        "unittests/ErrorOrTest.cpp",
        "unittests/ErrorTest.cpp",
        "unittests/FunctionExtrasTest.cpp",
        "unittests/IPIntTest.cpp",
        "unittests/IPRationalTest.cpp",
        "unittests/MathExtras.cpp",
        "unittests/RandomTest.cpp",
        "unittests/VersionTest.cpp",
    ],
    deps = [
        ":Base",
        ":Buffer",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "BufferTest",
    srcs = [
        "unittests/BufferTest.cpp",
    ],
    deps = [
        ":Buffer",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Base64",
    srcs = ["lib/Base64.cpp"],
    hdrs = ["include/Support/Base64.h"],
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_test(
    name = "Base64Test",
    srcs = ["unittests/Base64Test.cpp"],
    deps = [
        ":Base64",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "CommonCLOptions",
    srcs = ["lib/CommonCLOptions.cpp"],
    hdrs = ["include/Support/CommonCLOptions.h"],
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Filesystem",

        # Needed for the type definitions, and the reason that this is split
        # into a separate library when required.
        "@llvm-project//mlir:IR",
    ],
)

cc_library(
    name = "HMAC",
    srcs = ["lib/HMAC.cpp"],
    hdrs = ["include/Support/HMAC.h"],
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_test(
    name = "HMACTest",
    srcs = ["unittests/HMACTest.cpp"],
    deps = [
        ":HMAC",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Buffer",
    srcs = ["lib/Buffer.cpp"],
    hdrs = ["include/Support/Buffer.h"],
    strip_include_prefix = "include",
    deps = [
        ":ADT",
        ":Base",
        ":Filesystem",
    ],
)

cc_library(
    name = "DeviceSpecs",
    srcs = ["lib/DeviceSpecs.cpp"],
    hdrs = ["include/Support/DeviceSpecs.h"],
    strip_include_prefix = "include",
    deps = [
        ":Base",
        "@llvm-project//llvm:TargetParser",
    ],
)

cc_test(
    name = "DeviceSpecsTest",
    srcs = ["unittests/DeviceSpecsTest.cpp"],
    deps = [
        ":DeviceSpecs",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "CPUCache",
    srcs = ["lib/CPUCache.cpp"],
    hdrs = ["include/Support/CPUCache.h"],
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_library(
    name = "MicroBenchmark",
    srcs = ["lib/MicroBenchmark.cpp"],
    hdrs = ["include/Support/MicroBenchmark.h"],
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":CPUCache",
        "@llvm-project//llvm:Support",
    ],
)

cc_test(
    name = "MicroBenchmarkTest",
    srcs = ["unittests/MicroBenchmarkTest.cpp"],
    deps = [
        ":MicroBenchmark",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Driver",
    srcs = glob(["lib/Driver/*.cpp"]),
    hdrs = glob([
        "include/Support/Driver/*.h",
        "include/Support/Driver/*.inc",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Filesystem",
        "@llvm-project//mlir:Support",
    ],
)

cc_library(
    name = "CUDA",
    srcs = glob(["lib/CUDA/*.cpp"]),
    hdrs = glob(["include/Support/CUDA/*.h"]),
    strip_include_prefix = "include",
    textual_hdrs = glob(["lib/CUDA/*.h"]),
    deps = [":Base"],
)

cc_library(
    name = "ASN1",
    srcs = glob(["lib/ASN1/*.cpp"]),
    hdrs = glob(["include/Support/ASN1/*.h"]),
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_test(
    name = "ASN1Test",
    srcs = ["unittests/ASN1Test.cpp"],
    deps = [
        ":ASN1",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "ADT",
    srcs = glob([
        "lib/ADT/*.cpp",
    ]) + [
        # TODO: This should be part of Base but has circular dependencies
        "lib/TypeID.cpp",
    ],
    hdrs = glob(["include/Support/ADT/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Globals.headers",
        "@llvm-project//mlir:IR",
    ],
)

cc_test(
    name = "ADTTest",
    srcs = glob(["unittests/ADT/*.cpp"]),
    deps = [
        ":ADT",
        ":Globals",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Configuration",
    srcs = ["lib/Configuration.cpp"],
    hdrs = ["include/Support/Configuration.h"],
    strip_include_prefix = "include",
    deps = [
        ":ADT",
        ":Base",
        ":Filesystem",
    ],
)

cc_test(
    name = "ConfigurationTest",
    srcs = ["unittests/ConfigurationTest.cpp"],
    deps = [
        ":Configuration",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "CrashReporting",
    srcs = glob(["lib/CrashReporting/*.cpp"]),
    hdrs = [
        "include/Support/CrashReporting.h",
    ],
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Configuration",
        ":Settings",
        "@crashpad//:client",
    ],
)

cc_library(
    name = "Cryptography",
    srcs = glob(["lib/Cryptography/*.cpp"]),
    hdrs = glob(["include/Support/Cryptography/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Base64",
        ":Buffer",
        ":Configuration",
        ":JSON",
        "@mbedtls",
    ],
)

cc_test(
    name = "CryptographyTest",
    srcs = glob(["unittests/Cryptography/*.cpp"]),
    deps = [
        ":Cryptography",
        "@com_github_google_googletest//:gtest_main",
    ],
)

expand_root_cert_inc(
    name = "CertificatesHeader",
    cert_pem = select({
        "//:ProdBuild": "lib/Entitlements/RootCertificates/prod/cert.pem",
        "//:DevBuild": "lib/Entitlements/RootCertificates/local/cert.pem",
    }),
    endpoint = select({
        "//:ProdBuild": "lib/Entitlements/RootCertificates/prod/endpoint.txt",
        "//:DevBuild": "lib/Entitlements/RootCertificates/local/endpoint.txt",
    }),
    key_pem = select({
        "//:ProdBuild": "lib/Entitlements/RootCertificates/prod/key.pem",
        "//:DevBuild": "lib/Entitlements/RootCertificates/local/key.pem",
    }),
    source = "lib/Entitlements/RootCertificates/RootCert.inc.in",
)

cc_library(
    name = "Certificates",
    hdrs = [":CertificatesHeader"],
    # FIXME: This should really be namedspace in the proper place, but now it
    # relies on being in the same directory as the entitlements code.
    include_prefix = "./",
)

cc_library(
    name = "Entitlements",
    srcs = glob(["lib/Entitlements/*.cpp"]),
    hdrs = glob(["include/Support/Entitlements/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":ASN1",
        ":Base",
        ":Certificates",
        ":Configuration",
        ":Cryptography",
        ":HTTP",
    ],
)

cc_test(
    name = "EntitlementsTest",
    srcs = glob(["unittests/Entitlements/*.cpp"]),
    deps = [
        ":Entitlements",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Filesystem",
    srcs = [
        "lib/FileSystemExtras.cpp",
    ] + glob([
        "lib/Filesystem/*.cpp",
    ]),
    hdrs = [
        "include/Support/FileSystemExtras.h",
    ] + glob([
        "include/Support/Filesystem/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        "@llvm-project//llvm:Support",
    ],
)

cc_test(
    name = "FilesystemTest",
    srcs = ["unittests/FileSystemExtrasTest.cpp"],
    deps = [
        ":Buffer",
        ":Filesystem",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "IPInt",
    srcs = ["lib/IPInt.cpp"],
    hdrs = ["include/Support/IPInt.h"],
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_library(
    name = "IPRational",
    srcs = ["lib/IPRational.cpp"],
    hdrs = ["include/Support/IPRational.h"],
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":IPInt",
    ],
)

cc_library(
    name = "Stats",
    srcs = ["lib/Stats.cpp"],
    hdrs = ["include/Support/Stats.h"],
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_library(
    name = "URI",
    srcs = ["lib/URI.cpp"],
    hdrs = ["include/Support/URI.h"],
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_test(
    name = "URITest",
    srcs = ["unittests/URITest.cpp"],
    deps = [
        ":URI",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "JSON",
    srcs = ["lib/JSON.cpp"],
    hdrs = ["include/Support/JSON.h"],
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_test(
    name = "JSONTest",
    srcs = ["unittests/JSONTest.cpp"],
    deps = [
        ":JSON",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "HTTPHeaders",
    hdrs = glob(["include/Support/HTTP/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Base64",
        ":Buffer",
        ":Configuration",
        ":URI",
        "@curl",
        "@llvm-project//llvm:Support",
    ],
)

cc_library(
    name = "HTTP",
    srcs = glob(["lib/HTTP/*.cpp"]),
    hdrs = glob(["include/Support/HTTP/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Base64",
        ":Buffer",
        ":Configuration",
        ":Threading",
        ":URI",
        "@curl",
        "@llvm-project//llvm:Support",
    ],
)

cc_test(
    name = "HTTPTest",
    srcs = glob(["unittests/HTTP/*.cpp"]),
    deps = [
        ":HTTP",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "ML",
    srcs = glob(["lib/ML/*.cpp"]),
    hdrs = glob(["include/Support/ML/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        "@llvm-project//mlir:IR",
    ],
)

cc_test(
    name = "MLTest",
    srcs = [
        "unittests/BCastTest.cpp",
        "unittests/DTypeTest.cpp",
        "unittests/TensorShapeTest.cpp",
        "unittests/TensorSpecTest.cpp",
    ],
    deps = [
        ":ML",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Threading",
    srcs = glob(["lib/Threading/*.cpp"]),
    hdrs = glob(["include/Support/Threading/*.h"]),
    strip_include_prefix = "include",
    deps = [":Base"],
)

cc_test(
    name = "HostTest",
    srcs = ["unittests/HostTest.cpp"],
    deps = [
        ":MArchTarget",
        ":Threading",
        "//LLCL:CompilerSupport",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Profiling",
    srcs = glob(["lib/Profiling/*.cpp"]),
    hdrs = glob(["include/Support/Profiling/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Globals.headers",
        ":MArchTarget",
    ],
)

cc_library(
    name = "ProfilingHeaders",
    hdrs = glob(["include/Support/Profiling/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
    ],
)

cc_test(
    name = "ProfilingTest",
    srcs = ["unittests/TimeProfilerTest.cpp"],
    deps = [
        ":Globals",
        ":Profiling",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "MArchTarget",
    srcs = glob(["lib/MArchTarget/*.cpp"]),
    hdrs = glob(["include/Support/MArchTarget/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":CPUCache",
        ":MDialect",
        ":DeviceSpecs",
        ":Threading",

        # Rerquired for diagnostics.
        "@llvm-project//clang:basic",

        # Used by target-info.
        "@llvm-project//llvm:AllTargetsAsmParsers",
        "@llvm-project//llvm:AllTargetsCodeGens",
        "@llvm-project//llvm:AllTargetsDisassemblers",
        "@llvm-project//llvm:AllTargetsMCAs",
    ],
)

cc_test(
    name = "MArchTargetTest",
    srcs = glob(["unittests/MArchTarget/*.cpp"]),
    deps = [
        ":MArchTarget",
        "//LLCL:CompilerSupport",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Compiler",
    srcs = glob(["lib/Compiler/*.cpp"]),
    hdrs = glob(["include/Support/Compiler/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":ADT",
        ":Base",
        ":Buffer",
        ":MDialect",
        ":Profiling",
        "@llvm-project//mlir:AllPassesAndDialects",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

MODULAR_TELEMETRY_COPTS = [
    "-DWITH_OTLP_HTTP=ON",
    "-DENABLE_HTTP_SSL_PREVIEW=ON",
    "-DENABLE_OTLP_HTTP_SSL_PREVIEW=ON",
    "-Wno-global-constructors",  # Avoid errors coming from opentelemetry
]

cc_library(
    name = "Telemetry",
    srcs = glob(["lib/Telemetry/**/*.cpp"]),
    hdrs = glob(["include/Support/Telemetry/**/*.h"]),
    copts = MODULAR_TELEMETRY_COPTS,
    defines = [
        # FIXME(amscanne): These configurations should be removed. We
        # unilaterally set sensible configurations for now.
        "MODULAR_ENABLE_TELEMETRY",
        "HAVE_CPP_STDLIB",
    ] + select({
        "//:ProdBuild": [
            'MODULAR_TELEMETRY_URL=\\"https://telemetry.modular.com:443\\"',
        ],
        "//:DevBuild": [
            'MODULAR_TELEMETRY_URL=\\"https://telemetry-dev.modular.com:443\\"',
        ],
    }),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Configuration",
        ":Entitlements",
        ":MArchTarget",
        ":Settings",
        "@io_opentelemetry_cpp//api",
        "@io_opentelemetry_cpp//exporters/ostream:ostream_log_record_exporter",
        "@io_opentelemetry_cpp//exporters/ostream:ostream_metric_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_grpc_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_grpc_log_record_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_grpc_metric_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_http_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_http_log_record_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_http_metric_exporter",
        "@io_opentelemetry_cpp//sdk:headers",
    ],
)

cc_test(
    name = "TelemetryTest",
    srcs = ["unittests/TelemetryTest.cpp"],
    tags = ["manual"],  # TODO: fix on linux and re-enable
    deps = [
        ":Telemetry",
        "@com_github_google_googletest//:gtest_main",
    ],
)

td_library(
    name = "MTdFiles",
    srcs = glob([
        "include/Support/MDialect/*.td",
        "include/Support/Compiler/*.td",
    ]),
    includes = ["include"],
    deps = [
        ":Base",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "MDialectIncGen",
    dialect = "M",
    td_file = "include/Support/MDialect/M.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MAttrs",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attrdef-decls",
            ],
            "include/Support/MDialect/MAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
            ],
            "include/Support/MDialect/MAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/M.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MTypeInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-type-interface-decls",
            ],
            "include/Support/MDialect/MTypeInterfaces.h.inc",
        ),
        (
            [
                "-gen-type-interface-defs",
            ],
            "include/Support/MDialect/MTypeInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/MTypeInterfaces.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MAttrInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attr-interface-decls",
            ],
            "include/Support/MDialect/MAttrInterfaces.h.inc",
        ),
        (
            [
                "-gen-attr-interface-defs",
            ],
            "include/Support/MDialect/MAttrInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/MAttrInterfaces.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MDialectByteCode",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=M",
            ],
            "include/Support/MDialect/MDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/MDialectBytecode.td",
    deps = [":MTdFiles"],
)

cc_library(
    name = "MDialect",
    srcs = glob(["lib/MDialect/*.cpp"]),
    hdrs = glob([
        "include/Support/MDialect/*.h",
    ]) + [
        # The dialect files include some files that belong to other logical
        # packages in an apparent set of ordering violations. These create
        # loops in the logical package structure. Just encode these explicit
        # exceptions for now.
        "include/Support/Compiler/MLIRDenseAttr.h",
        "include/Support/MArchTarget/Host.h",
    ],
    strip_include_prefix = "include",
    deps = [
        ":ADT",
        ":Base",
        ":DeviceSpecs",
        ":MAttrInterfaces",
        ":MAttrs",
        ":MDialectByteCode",
        ":MDialectIncGen",
        ":ML",
        ":MTypeInterfaces",
        "//LLCL:CompilerSupportHeaders",
        "@llvm-project//llvm:MC",
        "@llvm-project//llvm:Target",
    ],
)

filegroup(
    name = "DebugInfoTdFiles",
    srcs = glob([
        "include/Support/DebugInfoDialect/**/*.td",
        "include/Support/Compiler/*.td",
    ]),
)

gentbl_cc_library(
    name = "DebugInfoToLLVMDialect",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-pass-decls",
                "-name",
                "DebugInfoToLLVM",
            ],
            "include/Support/DebugInfoDialect/DebugInfoToLLVM/DebugInfoToLLVM.h.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/DebugInfoToLLVM/DebugInfoToLLVM.td",
    deps = [
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "DebugInfoIncGen",
    dialect = "debuginfo",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfo.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "DebugInfoTypeInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-op-interface-decls",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoInterfaces.h.inc",
        ),
        (
            [
                "-gen-op-interface-defs",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfoInterfaces.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

cc_library(
    name = "DebugInfoDialect",
    srcs = glob(["lib/DebugInfoDialect/IR/*.cpp"]),
    hdrs = glob(["include/Support/DebugInfoDialect/IR/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Compiler",
        ":DebugInfoDialectAttrs",
        ":DebugInfoDialectBytecode",
        ":DebugInfoExprAttrInterfaces",
        ":DebugInfoIncGen",
        ":DebugInfoTypeInterfaces",
        "@llvm-project//llvm:BinaryFormat",
        "@llvm-project//mlir:IR",
    ],
)

cc_library(
    name = "Settings",
    srcs = glob(["lib/Settings/*.cpp"]),
    hdrs = glob(["include/Support/Settings/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Configuration",
        ":Entitlements",
    ],
)

gentbl_cc_library(
    name = "DebugInfoExprAttrInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attr-interface-decls",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoExprAttrInterfaces.h.inc",
        ),
        (
            [
                "-gen-attr-interface-defs",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoExprAttrInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfoExprAttrInterfaces.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "DebugInfoDialectAttrs",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-enum-decls",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoEnums.h.inc",
        ),
        (
            [
                "-gen-enum-defs",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoEnums.cpp.inc",
        ),
        (
            [
                "-gen-attrdef-decls",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfo.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "DebugInfoDialectBytecode",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfoDialectBytecode.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "DebugInfoTransformPasses",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-pass-decls",
                "-name",
                "Transforms",
            ],
            "include/Support/DebugInfoDialect/Transforms/Transforms.h.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/Transforms/Passes.td",
    deps = [
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

cc_library(
    name = "DebugInfoTransforms",
    srcs = glob(["lib/DebugInfoDialect/Transforms/*.cpp"]),
    hdrs = glob(["include/Support/DebugInfoDialect/Transforms/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":DebugInfoDialect",
        ":DebugInfoTransformPasses",
        "@llvm-project//mlir:Parser",
        "@llvm-project//mlir:TransformUtils",
    ],
)

cc_library(
    name = "DebugInfoToLLVM",
    srcs = glob(["lib/DebugInfoDialect/DebugInfoToLLVM/*.cpp"]),
    hdrs = glob(["include/Support/DebugInfoDialect/DebugInfoToLLVM/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":DebugInfoDialect",
        ":DebugInfoToLLVMDialect",
        ":DebugInfoTransforms",
        "@llvm-project//mlir:LLVMCommonConversion",
        "@llvm-project//mlir:LLVMDialect",
        "@llvm-project//mlir:Pass",
    ],
)

cc_test(
    name = "DebugInfoDialectTest",
    srcs = glob(["unittests/DebugInfoDialect/*.cpp"]),
    deps = [
        ":DebugInfoDialect",
        ":DebugInfoToLLVM",
        ":DebugInfoTransforms",
        "//LLCL:CompilerSupport",
        "@com_github_google_googletest//:gtest_main",
    ],
)

td_library(
    name = "DriverCommandTdFiles",
    srcs = glob(
        [
            "include/Support/Driver/*.td",
        ],
        exclude = [
            "include/Support/Driver/OptTable.inc",
        ],
    ),
    includes = ["include"],
    deps = [
        "@llvm-project//llvm:OptParserTdFiles",
    ],
)

td_library(
    name = "OptTableTdFiles",
    srcs = ["include/Support/Driver/OptTable.inc"],
    includes = ["include"],
)

cc_library(
    name = "Init",
    srcs = [
        "lib/Init/Init.cpp",
    ],
    hdrs = [
        "include/Support/Init/Init.h",
    ],
    strip_include_prefix = "include",
    deps = [
        ":CrashReporting",
        ":Settings",
        ":Telemetry",
        "//LLCL:Runtime",
    ],
)

cc_test(
    name = "FillTest",
    srcs = ["unittests/ML/FillTest.cpp"],
    deps = [
        ":ML",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "CompilerTest",
    srcs = glob(["unittests/Compiler/*.cpp"]),
    deps = [
        ":Compiler",
        "//LLCL:CompilerSupport",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "Billing",
    srcs = glob(["lib/Billing/**/*.cpp"]),
    hdrs = glob(["include/Support/Billing/**/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":HTTP",
    ],
)

cc_test(
    name = "BillingTest",
    srcs = glob(["unittests/Billing/*.cpp"]),
    tags = ["manual"],  # FIXME: Currently crashes with cmake too
    deps = [
        ":Billing",
        ":Threading",
        "@com_github_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "FrameworkSupport",
    srcs = glob(["lib/Frameworks/*.cpp"]),
    hdrs = glob(["include/Support/Frameworks/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Telemetry",
    ],
)

globals_library(
    name = "Globals",
    srcs = glob(["lib/Globals/*.cpp"]),
    hdrs = glob(["include/Support/Globals/*.h"]) + [
        "include/Support/SymbolExport.h",
    ],
    strip_include_prefix = "include",
    # TODO: Missing define conditionals for symbol visibility
    # NOTE: This library should not have any deps to avoid shared object linking issues
)

cc_library(
    name = "Metering",
    srcs = glob(["lib/Metering/**/*.cpp"]),
    hdrs = glob(["include/Support/Metering/**/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Base",
        ":Buffer",
        ":HTTP",
        ":Telemetry",
        "//LLCL:Support",
    ],
)

cc_test(
    name = "MeteringTests",
    srcs = glob(["unittests/Metering/*.cpp"]),
    deps = [
        ":Metering",
        "@com_github_google_googletest//:gtest_main",
    ],
)
