load("@pybind11_bazel//:build_defs.bzl", "pybind_library")
load("//bazel:api.bzl", "gentbl_cc_library", "gentbl_mlir_dialect", "gentbl_modular_passes", "modular_cc_library", "modular_shared_library", "td_library")
load("//utils/bazel/build/rules:expand_root_cert_inc.bzl", "expand_root_cert_inc")

exports_files(["include/Support/Driver/DriverCommand.td"])

modular_cc_library(
    name = "SymbolExport",
    hdrs = [
        "include/Support/SymbolExport.h",
    ],
)

modular_cc_library(
    name = "Base",
    srcs = [
        "lib/AlignedAlloc.cpp",
        "lib/BuildInfo.cpp",
        "lib/Config.cpp",
        "lib/DynamicLibrary.cpp",
        "lib/Error.cpp",
        "lib/ErrorOr.cpp",
        "lib/PlatformLibNames.cpp",
        "lib/Process.cpp",
        "lib/Random.cpp",
        "lib/ReferenceCounted.cpp",
        "lib/Version.cpp",
        "lib/VisualizationUtils.cpp",
    ],
    hdrs = [
        "include/Support/AlignedAlloc.h",
        "include/Support/AssertStream.h",
        "include/Support/Binary.h",
        "include/Support/BuildInfo.h",
        "include/Support/CommandLine.h",
        "include/Support/Config.h",
        "include/Support/Context.h",
        "include/Support/DynamicLibrary.h",
        "include/Support/Error.h",
        "include/Support/ErrorOr.h",
        "include/Support/ForwardDecls.h",
        "include/Support/FunctionExtras.h",
        "include/Support/LLVMCompilerForwardDecls.h",
        "include/Support/LLVMForwardDecls.h",
        "include/Support/LLVMYAMLForwardDecls.h",
        "include/Support/LogicalResult.h",
        "include/Support/MathExtras.h",
        "include/Support/PlatformLibNames.h",
        "include/Support/PlatformUtils.h",
        "include/Support/Preprocessor.h",
        "include/Support/Process.h",
        "include/Support/RCRef.h",
        "include/Support/Random.h",
        "include/Support/ReferenceCounted.h",
        "include/Support/STLExtras.h",
        "include/Support/SymbolExport.h",
        "include/Support/TypeID.h",
        "include/Support/Version.h",
        "include/Support/VisualizationUtils.h",
    ],
    local_defines = [
        "SHARED_LIBRARY_PREFIX='\"lib\"'",
        "STATIC_LIBRARY_PREFIX='\"lib\"'",
        "STATIC_LIBRARY_SUFFIX='\".a\"'",
    ] + select({
        "@platforms//os:macos": ["SHARED_LIBRARY_SUFFIX='\".dylib\"'"],
        "@platforms//os:linux": ["SHARED_LIBRARY_SUFFIX='\".so\"'"],
    }),
    deps = [
        "//Config",
        "@llvm-project//mlir:Pass",
        "@llvm-project//mlir:Support",
    ],
)

modular_cc_library(
    name = "Base64",
    srcs = ["lib/Base64.cpp"],
    hdrs = ["include/Support/Base64.h"],
    deps = [":Base"],
)

modular_cc_library(
    name = "CommonCLOptions",
    srcs = ["lib/CommonCLOptions.cpp"],
    hdrs = ["include/Support/CommonCLOptions.h"],
    deps = [
        ":Base",
        ":Filesystem",

        # Needed for the type definitions, and the reason that this is split
        # into a separate library when required.
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "HMAC",
    srcs = ["lib/HMAC.cpp"],
    hdrs = ["include/Support/HMAC.h"],
    deps = [":Base"],
)

modular_cc_library(
    name = "Buffer",
    srcs = ["lib/Buffer.cpp"],
    hdrs = ["include/Support/Buffer.h"],
    deps = [
        ":ADT",
        ":Base",
        ":Filesystem",
    ],
)

modular_cc_library(
    name = "DeviceSpecs",
    srcs = ["lib/DeviceSpecs.cpp"],
    hdrs = ["include/Support/DeviceSpecs.h"],
    deps = [
        ":Base",
        "@llvm-project//llvm:TargetParser",
    ],
)

modular_cc_library(
    name = "CPUCache",
    srcs = ["lib/CPUCache.cpp"],
    hdrs = ["include/Support/CPUCache.h"],
    deps = [":Base"],
)

modular_cc_library(
    name = "MicroBenchmark",
    srcs = ["lib/MicroBenchmark.cpp"],
    hdrs = ["include/Support/MicroBenchmark.h"],
    deps = [
        ":Base",
        ":CPUCache",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_library(
    name = "Driver",
    srcs = glob(["lib/Driver/*.cpp"]),
    hdrs = glob([
        "include/Support/Driver/*.h",
        "include/Support/Driver/*.inc",
    ]),
    deps = [
        ":Base",
        ":Filesystem",
        "@llvm-project//mlir:Support",
    ],
)

modular_cc_library(
    name = "CUDA",
    srcs = glob(["lib/CUDA/*.cpp"]),
    hdrs = glob(["include/Support/CUDA/*.h"]),
    textual_hdrs = glob(["lib/CUDA/*.h"]),
    deps = [":Base"],
)

modular_cc_library(
    name = "ASN1",
    srcs = glob(["lib/ASN1/*.cpp"]),
    hdrs = glob(["include/Support/ASN1/*.h"]),
    deps = [":Base"],
)

modular_cc_library(
    name = "ADT",
    srcs = glob([
        "lib/ADT/*.cpp",
    ]) + [
        # TODO: This should be part of Base but has circular dependencies
        "lib/TypeID.cpp",
    ],
    hdrs = glob(["include/Support/ADT/*.h"]),
    deps = [
        ":Base",
        ":Globals.headers",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "Configuration",
    srcs = ["lib/Configuration.cpp"],
    hdrs = ["include/Support/Configuration.h"],
    deps = [
        ":ADT",
        ":Base",
        ":Filesystem",
    ],
)

modular_cc_library(
    name = "CrashReporting",
    srcs = glob(["lib/CrashReporting/*.cpp"]),
    hdrs = [
        "include/Support/CrashReporting.h",
    ],
    deps = [
        ":Base",
        ":Configuration",
        ":Settings",
        "@crashpad//:client",
    ],
)

modular_cc_library(
    name = "Cryptography",
    srcs = glob(["lib/Cryptography/*.cpp"]),
    hdrs = glob(["include/Support/Cryptography/*.h"]),
    deps = [
        ":Base",
        ":Base64",
        ":Buffer",
        ":Configuration",
        ":JSON",
        "@mbedtls",
    ],
)

expand_root_cert_inc(
    name = "CertificatesHeader",
    cert_pem = select({
        "//:DevBuild": "lib/Entitlements/RootCertificates/dev/cert.pem",
        "//:LocalBuild": "lib/Entitlements/RootCertificates/local/cert.pem",
        "//:ProdBuild": "lib/Entitlements/RootCertificates/prod/cert.pem",
        "//:StagingBuild": "lib/Entitlements/RootCertificates/staging/cert.pem",
    }),
    endpoint = select({
        "//:DevBuild": "lib/Entitlements/RootCertificates/dev/endpoint.txt",
        "//:LocalBuild": "lib/Entitlements/RootCertificates/local/endpoint.txt",
        "//:ProdBuild": "lib/Entitlements/RootCertificates/prod/endpoint.txt",
        "//:StagingBuild": "lib/Entitlements/RootCertificates/staging/endpoint.txt",
    }),
    key_pem = select({
        "//:DevBuild": "lib/Entitlements/RootCertificates/dev/key.pem",
        "//:LocalBuild": "lib/Entitlements/RootCertificates/local/key.pem",
        "//:ProdBuild": "lib/Entitlements/RootCertificates/prod/key.pem",
        "//:StagingBuild": "lib/Entitlements/RootCertificates/staging/key.pem",
    }),
    source = "lib/Entitlements/RootCertificates/RootCert.inc.in",
    visibility = [":__subpackages__"],
)

modular_cc_library(
    name = "Entitlements",
    srcs = [":CertificatesHeader"] + glob(["lib/Entitlements/*.cpp"]),
    hdrs = glob(["include/Support/Entitlements/*.h"]),
    copts = ["-I$(GENDIR)/Support"],
    deps = [
        ":ASN1",
        ":Base",
        ":Configuration",
        ":Cryptography",
        ":HTTP",
    ],
)

modular_cc_library(
    name = "Filesystem",
    srcs = [
        "lib/FileSystemExtras.cpp",
    ] + glob([
        "lib/Filesystem/*.cpp",
    ]),
    hdrs = [
        "include/Support/FileSystemExtras.h",
    ] + glob([
        "include/Support/Filesystem/*.h",
    ]),
    deps = [
        ":Base",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_library(
    name = "IPInt",
    srcs = ["lib/IPInt.cpp"],
    hdrs = ["include/Support/IPInt.h"],
    deps = [":Base"],
)

modular_cc_library(
    name = "IPRational",
    srcs = ["lib/IPRational.cpp"],
    hdrs = ["include/Support/IPRational.h"],
    deps = [
        ":Base",
        ":IPInt",
    ],
)

modular_cc_library(
    name = "Stats",
    srcs = ["lib/Stats.cpp"],
    hdrs = ["include/Support/Stats.h"],
    deps = [":Base"],
)

modular_cc_library(
    name = "URI",
    srcs = ["lib/URI.cpp"],
    hdrs = ["include/Support/URI.h"],
    deps = [":Base"],
)

modular_cc_library(
    name = "JSON",
    srcs = ["lib/JSON.cpp"],
    hdrs = ["include/Support/JSON.h"],
    deps = [":Base"],
)

modular_cc_library(
    name = "UI",
    srcs = glob(["lib/UI/*.cpp"]),
    hdrs = glob(["include/Support/UI/*.h"]),
    deps = [
        ":Base",
    ],
)

modular_cc_library(
    name = "HTTP",
    srcs = glob(["lib/HTTP/*.cpp"]),
    hdrs = glob(["include/Support/HTTP/*.h"]),
    deps = [
        ":Base",
        ":Base64",
        ":Buffer",
        ":Configuration",
        ":Threading",
        ":UI",
        ":URI",
        "@curl",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_library(
    name = "ML",
    srcs = glob(["lib/ML/*.cpp"]),
    hdrs = glob(["include/Support/ML/*.h"]),
    deps = [
        ":Base",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "Threading",
    srcs = glob(["lib/Threading/*.cpp"]),
    hdrs = glob(["include/Support/Threading/*.h"]),
    deps = [":Base"],
)

modular_cc_library(
    name = "Profiling",
    srcs = glob(["lib/Profiling/*.cpp"]),
    hdrs = glob(["include/Support/Profiling/*.h"]),
    deps = [
        ":Base",
        ":Globals.headers",
        ":MArchTarget",
    ],
)

modular_cc_library(
    name = "Profiling.headers",
    hdrs = glob(["include/Support/Profiling/*.h"]),
    visibility = ["//LLCL:__subpackages__"],
    deps = [
        ":Base",
    ],
)

modular_cc_library(
    name = "MArchTarget",
    srcs = glob(["lib/MArchTarget/*.cpp"]),
    hdrs = glob(["include/Support/MArchTarget/*.h"]),
    deps = [
        ":Base",
        ":CPUCache",
        ":MDialect",
        ":DeviceSpecs",
        ":Threading",

        # Rerquired for diagnostics.
        "@llvm-project//clang:basic",

        # Used by target-info.
        "@llvm-project//llvm:AllTargetsAsmParsers",
        "@llvm-project//llvm:AllTargetsCodeGens",
        "@llvm-project//llvm:AllTargetsDisassemblers",
        "@llvm-project//llvm:AllTargetsMCAs",
    ],
)

modular_cc_library(
    name = "Compiler",
    srcs = glob(["lib/Compiler/*.cpp"]),
    hdrs = glob(["include/Support/Compiler/*.h"]),
    deps = [
        ":ADT",
        ":Base",
        ":Buffer",
        ":MDialect",
        ":Profiling",
        "@llvm-project//mlir:AllPassesAndDialects",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

MODULAR_TELEMETRY_COPTS = [
    "-DWITH_OTLP_HTTP=ON",
    "-DENABLE_HTTP_SSL_PREVIEW=ON",
    "-DENABLE_OTLP_HTTP_SSL_PREVIEW=ON",
    "-Wno-global-constructors",  # Avoid errors coming from opentelemetry
    "-Wno-covered-switch-default",  # Avoid errors coming from opentelemetry
]

modular_cc_library(
    name = "Telemetry",
    srcs = glob(["lib/Telemetry/**/*.cpp"]),
    hdrs = glob(["include/Support/Telemetry/**/*.h"]),
    copts = MODULAR_TELEMETRY_COPTS,
    defines = [
        # FIXME(amscanne): These configurations should be removed. We
        # unilaterally set sensible configurations for now.
        "MODULAR_ENABLE_TELEMETRY",
        "HAVE_CPP_STDLIB",
    ] + select({
        "//:ProdBuild": [
            'MODULAR_TELEMETRY_URL=\\"https://telemetry.modular.com:443\\"',
        ],
        "//conditions:default": [
            'MODULAR_TELEMETRY_URL=\\"https://telemetry-dev.modular.com:443\\"',
        ],
    }),
    deps = [
        ":Base",
        ":Configuration",
        ":Entitlements",
        ":Filesystem",
        ":HTTP",
        ":MArchTarget",
        ":Settings",
        "@io_opentelemetry_cpp//api",
        "@io_opentelemetry_cpp//exporters/ostream:ostream_log_record_exporter",
        "@io_opentelemetry_cpp//exporters/ostream:ostream_metric_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_grpc_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_grpc_log_record_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_grpc_metric_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_http_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_http_log_record_exporter",
        "@io_opentelemetry_cpp//exporters/otlp:otlp_http_metric_exporter",
        "@io_opentelemetry_cpp//sdk:headers",
    ],
)

td_library(
    name = "MTdFiles",
    srcs = glob([
        "include/Support/MDialect/*.td",
        "include/Support/Compiler/*.td",
    ]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":Base",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "MDialectIncGen",
    dialect = "M",
    td_file = "include/Support/MDialect/M.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MAttrs",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attrdef-decls",
            ],
            "include/Support/MDialect/MAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
            ],
            "include/Support/MDialect/MAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/M.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MTypeInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-type-interface-decls",
            ],
            "include/Support/MDialect/MTypeInterfaces.h.inc",
        ),
        (
            [
                "-gen-type-interface-defs",
            ],
            "include/Support/MDialect/MTypeInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/MTypeInterfaces.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MAttrInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attr-interface-decls",
            ],
            "include/Support/MDialect/MAttrInterfaces.h.inc",
        ),
        (
            [
                "-gen-attr-interface-defs",
            ],
            "include/Support/MDialect/MAttrInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/MAttrInterfaces.td",
    deps = [":MTdFiles"],
)

gentbl_cc_library(
    name = "MDialectByteCode",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=M",
            ],
            "include/Support/MDialect/MDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/MDialect/MDialectBytecode.td",
    deps = [":MTdFiles"],
)

modular_cc_library(
    name = "MDialect",
    srcs = glob(["lib/MDialect/*.cpp"]),
    hdrs = glob([
        "include/Support/MDialect/*.h",
    ]) + [
        # The dialect files include some files that belong to other logical
        # packages in an apparent set of ordering violations. These create
        # loops in the logical package structure. Just encode these explicit
        # exceptions for now.
        "include/Support/Compiler/MLIRDenseAttr.h",
        "include/Support/MArchTarget/Host.h",
    ],
    deps = [
        ":ADT",
        ":Base",
        ":Buffer",
        ":DeviceSpecs",
        ":MAttrInterfaces",
        ":MAttrs",
        ":MDialectByteCode",
        ":MDialectIncGen",
        ":ML",
        ":MTypeInterfaces",
        "//LLCL:CompilerSupport.headers",
        "@llvm-project//llvm:MC",
        "@llvm-project//llvm:Target",
    ],
)

filegroup(
    name = "DebugInfoTdFiles",
    srcs = glob([
        "include/Support/DebugInfoDialect/**/*.td",
        "include/Support/Compiler/*.td",
    ]),
    visibility = ["//visibility:public"],
)

gentbl_modular_passes(
    name = "DebugInfoToLLVMIncGen",
    output_name = "DebugInfoToLLVM",
    td_file = "include/Support/DebugInfoDialect/DebugInfoToLLVM/DebugInfoToLLVM.td",
    deps = [
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "DebugInfoIncGen",
    dialect = "debuginfo",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfo.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "DebugInfoTypeInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-op-interface-decls",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoInterfaces.h.inc",
        ),
        (
            [
                "-gen-op-interface-defs",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfoInterfaces.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

modular_cc_library(
    name = "DebugInfoDialect",
    srcs = glob(["lib/DebugInfoDialect/IR/*.cpp"]),
    hdrs = glob(["include/Support/DebugInfoDialect/IR/*.h"]),
    deps = [
        ":Base",
        ":Compiler",
        ":DebugInfoDialectAttrs",
        ":DebugInfoDialectBytecode",
        ":DebugInfoExprAttrInterfaces",
        ":DebugInfoIncGen",
        ":DebugInfoTypeInterfaces",
        "@llvm-project//llvm:BinaryFormat",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "Settings",
    srcs = glob(["lib/Settings/*.cpp"]),
    hdrs = glob(["include/Support/Settings/*.h"]),
    deps = [
        ":Configuration",
        ":Entitlements",
    ],
)

gentbl_cc_library(
    name = "DebugInfoExprAttrInterfaces",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attr-interface-decls",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoExprAttrInterfaces.h.inc",
        ),
        (
            [
                "-gen-attr-interface-defs",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoExprAttrInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfoExprAttrInterfaces.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "DebugInfoDialectAttrs",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-enum-decls",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoEnums.h.inc",
        ),
        (
            [
                "-gen-enum-defs",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoEnums.cpp.inc",
        ),
        (
            [
                "-gen-attrdef-decls",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
                "-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfo.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "DebugInfoDialectBytecode",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=debuginfo",
            ],
            "include/Support/DebugInfoDialect/IR/DebugInfoDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/Support/DebugInfoDialect/IR/DebugInfoDialectBytecode.td",
    deps = [
        ":Base",
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_modular_passes(
    name = "DebugInfoTransformPasses",
    output_name = "Transforms",
    td_file = "include/Support/DebugInfoDialect/Transforms/Passes.td",
    deps = [
        ":DebugInfoTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

modular_cc_library(
    name = "DebugInfoTransforms",
    srcs = glob(["lib/DebugInfoDialect/Transforms/*.cpp"]),
    hdrs = glob(["include/Support/DebugInfoDialect/Transforms/*.h"]),
    deps = [
        ":Base",
        ":DebugInfoDialect",
        ":DebugInfoTransformPasses",
        "@llvm-project//mlir:Parser",
        "@llvm-project//mlir:TransformUtils",
    ],
)

modular_cc_library(
    name = "DebugInfoToLLVM",
    srcs = glob([
        "lib/DebugInfoDialect/DebugInfoToLLVM/**/*.cpp",
        "lib/DebugInfoDialect/DebugInfoToLLVM/**/*.h",
    ]),
    hdrs = glob(["include/Support/DebugInfoDialect/DebugInfoToLLVM/*.h"]),
    deps = [
        ":DebugInfoDialect",
        ":DebugInfoToLLVMIncGen",
        ":DebugInfoTransforms",
        "@llvm-project//mlir:LLVMCommonConversion",
        "@llvm-project//mlir:LLVMDialect",
        "@llvm-project//mlir:Pass",
    ],
)

td_library(
    name = "DriverCommandTdFiles",
    srcs = glob(["include/Support/Driver/*.td"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "@llvm-project//llvm:OptParserTdFiles",
    ],
)

td_library(
    name = "OptTableTdFiles",
    srcs = ["include/Support/Driver/OptTable.inc"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

modular_cc_library(
    name = "Init",
    srcs = [
        "lib/Init/Init.cpp",
    ],
    hdrs = [
        "include/Support/Init/Init.h",
    ],
    deps = [
        ":CrashReporting",
        ":Settings",
        ":Telemetry",
        "//LLCL:Runtime",
    ],
)

modular_cc_library(
    name = "FrameworkSupport",
    srcs = glob(["lib/Frameworks/*.cpp"]),
    hdrs = glob(["include/Support/Frameworks/*.h"]),
    deps = [
        ":Telemetry",
    ],
)

modular_shared_library(
    name = "Globals",
    srcs = glob(["lib/Globals/*.cpp"]),
    hdrs = glob(["include/Support/Globals/*.h"]) + [
        "include/Support/SymbolExport.h",
    ],
    output_name = "MSupportGlobals",
    # TODO: Missing define conditionals for symbol visibility
    # NOTE: This library should not have any deps to avoid shared object linking issues
)

modular_cc_library(
    name = "Metering",
    srcs = glob(["lib/Metering/**/*.cpp"]),
    hdrs = glob(["include/Support/Metering/**/*.h"]),
    deps = [
        ":Base",
        ":Buffer",
        ":HTTP",
        ":Telemetry",
    ],
)

pybind_library(
    name = "Python",
    srcs = ["lib/Python/Helpers.cpp"],
    hdrs = ["include/Support/Python/Helpers.h"],
    copts = ["-frtti"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
