##===----------------------------------------------------------------------===##
#
# This file is Modular Inc proprietary.
#
##===----------------------------------------------------------------------===##

add_subdirectory(include/Support/HLCFDialect)
add_subdirectory(include/Support/HLCFToLLVM)
add_subdirectory(include/Support/MDialect)
#add_subdirectory(integration_test)
add_subdirectory(lib)
add_subdirectory(tools/support-dialect-opt)
add_subdirectory(tools/system-info)
add_subdirectory(test)
add_subdirectory(unittests)
