load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "system-info",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//AsyncRT:CompilerSupport",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
        "//Support:MArchTarget",
        "//Support:MDialect",
    ],
)
