load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "test",
    size = "large",
    srcs = [
        "pybind.mojo",
        "test.py",
    ],
    data = ["module.mojo"],
    mojo_deps = [
        "//open-source/mojo/stdlib/stdlib",
    ],
    tools = [
        "//KGEN/tools/kgen",
        "//KGEN/tools/kgen-translate",
        "//KGEN/tools/mojo",
    ],
    deps = [
        # Adds path/to/mojo-pybind/.. to the PYTHONPATH so we can invoke it as:
        #   RUN: python3 -m mojo-pybind.main
        "//KGEN/MojoBindings/mojo-pybind",
    ],
)
