load("//bazel:api.bzl", "modular_cc_binary")

package(default_visibility = ["//KGEN:consumers"])

modular_cc_binary(
    name = "kgen-doc",
    srcs = ["kgen-doc.cpp"],
    deps = [
        "//AsyncRT:Runtime",
        "//Init",
        "//KGEN:MojoTooling",
        "//KGEN:ToolCommon",
        "//KGEN/tools/mojo:DocIncFiles",
        "//Support:Driver",
    ],
)
