//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This is the top level file for the HLKGEN dialect.
//
//===----------------------------------------------------------------------===//

#ifndef HLKGEN_TD
#define HLKGEN_TD

include "KGEN/KGENDialect/KGENAttrs.td"
include "KGEN/HLKGENDialect/HLKGENOps.td"

#endif // KGEN_TD
