load("//bazel:api.bzl", "mojo_library")

package(default_visibility = ["//visibility:public"])

exports_files(["stdlib/__init__.mojo"])

filegroup(
    name = "test-packages",
    srcs = glob(["**/*.mojo"]),
    visibility = ["//visibility:public"],
)

mojo_library(
    name = "stdlib",
    srcs = glob(["**/*.mojo"]),
)
