load("@pip_deps//:requirements.bzl", "requirement")

py_binary(
    name = "mojo-pybind",
    srcs = ["main.py"] + glob(["src/*.py"]),
    imports = [
        # Needed so that `bazel run <mojo-pybind>` correctly resolves
        # `import mojo_pybind` from main.py
        ".",
        # Needed so that `python3 -m mojo-pybind` works when using
        # `RUN: python3 -m mojo-pybind` in integration tests.
        "..",
    ],
    main = "main.py",
    # Prevent dependent uses of this script for the time being, as its still
    # massively unstable, and unlike our desired final end state.
    visibility = [
        ":__subpackages__",
        "//KGEN:__subpackages__",
        "//open-source/mojo/integration-test:__subpackages__",
    ],
    deps = [
        requirement("click"),
    ],
)
