# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

TEMPLATE = """\
# This file is generated by rules_pycross.
# It is not intended for manual editing.
\"\"\"Pycross-generated dependency targets.\"\"\"

load("@bazel_skylib//lib:selects.bzl", "selects")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@module_versions//:config.bzl", "PYTHON_VERSIONS_DOTTED")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("@@rules_pycross+//pycross:defs.bzl", "pycross_wheel_build", "pycross_wheel_library")

_TESTONLY_DEPS = [
    "hypothesis",
    "lm-eval",
    "mteb",
    "peft",
    "pygame-ce",
    "sentence-transformers",
    "sglang",
    "timm",
    "torchmetrics",
    "torchvision",
    "vllm",
    "xgrammar",
]

PINS = {{
{pins}
}}

# buildifier: disable=unnamed-macro
def targets():
    \"\"\"Generated package targets.\"\"\"

    for pin_name, pin_target in PINS.items():
        native.alias(
            name = pin_name,
            actual = ":" + pin_target,
            testonly = pin_name in _TESTONLY_DEPS,
        )

    native.alias(
        name = "torch@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":torch@2.11.0+cu130",
            "@@//:use_vllm_setting": ":torch@2.13.0+cu130",
            "@@//:amd_gpu": ":torch@2.10.0+rocm7.2.3.lw.git1a270074",
            "@@//:nvidia_gpu": ":torch@2.10.0+cu128",
            "@platforms//os:macos": ":torch@2.10.0",
            "//conditions:default": ":torch@2.10.0+cpu",
        }}),
    )

    native.alias(
        name = "torchaudio@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":torchaudio@2.11.0+cu130",
            "@@//:use_vllm_setting": ":torchaudio@2.11.0+cu130",
            "@@//:amd_gpu": ":torchaudio@2.10.0+rocm7.2.3.git5047768f",
            "@@//:nvidia_gpu": ":torchaudio@2.10.0+cu128",
            "@platforms//os:macos": ":torchaudio@2.10.0",
            "@@//:linux_aarch64": ":torchaudio@2.10.0",
            "//conditions:default": ":torchaudio@2.10.0+cpu",
        }}),
    )

    native.alias(
        name = "torchvision@multiple",
        testonly = True,
        actual = select({{
            "@@//:use_sglang_setting": ":torchvision@0.26.0+cu130",
            "@@//:use_vllm_setting": ":torchvision@0.28.0+cu130",
            "@@//:amd_gpu": ":torchvision@0.25.0+rocm7.2.3.git82df5f59",
            "@@//:nvidia_gpu": ":torchvision@0.25.0+cu128",
            "@platforms//os:macos": ":torchvision@0.25.0",
            "@@//:linux_aarch64": ":torchvision@0.25.0+cpu",
            "//conditions:default": ":torchvision@0.25.0+cpu",
        }}),
    )

    native.alias(
        name = "triton@multiple",
        testonly = True,
        actual = select({{
            "@@//:use_vllm_setting": ":triton@3.7.1",
            "@@//:amd_gpu": ":triton@3.6.0+rocm7.2.3.git4ed88892",
            "//conditions:default": ":triton@3.6.0",
        }}),
    )

    native.alias(
        name = "llguidance@multiple",
        testonly = True,
        actual = select({{
            "@@//:use_sglang_setting": ":llguidance@0.7.30",
            "@@//:use_vllm_setting": ":llguidance@1.7.5",
            "//conditions:default": ":llguidance@1.7.5",
        }}),
    )

    native.alias(
        name = "transformers@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":transformers@5.6.0",
            "@@//:use_vllm_setting": ":transformers@5.12.1",
            "//conditions:default": ":transformers@5.12.1",
        }}),
    )

    native.alias(
        name = "click@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":click@8.5.0",
            "@@//:use_vllm_setting": ":click@8.5.0",
            "//conditions:default": ":click@8.1.7",
        }}),
    )

    native.alias(
        name = "openai@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":openai@2.6.1",
            "@@//:use_vllm_setting": ":openai@2.54.0",
            "//conditions:default": ":openai@2.11.0",
        }}),
    )

    native.alias(
        name = "idna@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":idna@3.8",
            "@@//:use_vllm_setting": ":idna@3.20",
            "//conditions:default": ":idna@3.8",
        }}),
    )

    native.alias(
        name = "mcp@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":mcp@1.28.1",
            "@@//:use_vllm_setting": ":mcp@2.3.0",
            "//conditions:default": ":mcp@1.28.1",
        }}),
    )

    native.alias(
        name = "sse-starlette@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":sse-starlette@2.1.2",
            "@@//:use_vllm_setting": ":sse-starlette@3.5.0",
            "//conditions:default": ":sse-starlette@2.1.2",
        }}),
    )

    native.alias(
        name = "hf-xet@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":hf-xet@1.6.0",
            "@@//:use_vllm_setting": ":hf-xet@1.6.0",
            "//conditions:default": ":hf-xet@1.4.2",
        }}),
    )

    native.alias(
        name = "huggingface-hub@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":huggingface-hub@1.33.0",
            "@@//:use_vllm_setting": ":huggingface-hub@1.33.0",
            "//conditions:default": ":huggingface-hub@1.8.0",
        }}),
    )

    native.alias(
        name = "apache-tvm-ffi@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":apache-tvm-ffi@0.1.9",
            "@@//:use_vllm_setting": ":apache-tvm-ffi@0.1.11",
            "//conditions:default": ":apache-tvm-ffi@0.1.9",
        }}),
    )

    native.alias(
        name = "compressed-tensors@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":compressed-tensors@0.17.0",
            "@@//:use_vllm_setting": ":compressed-tensors@0.17.0",
            "//conditions:default": ":compressed-tensors@0.15.0.1",
        }}),
    )

    native.alias(
        name = "cuda-pathfinder@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":cuda-pathfinder@1.8.2",
            "@@//:use_vllm_setting": ":cuda-pathfinder@1.8.2",
            "//conditions:default": ":cuda-pathfinder@1.3.2",
        }}),
    )

    native.alias(
        name = "flashinfer-cubin@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":flashinfer-cubin@0.6.11.post1",
            "@@//:use_vllm_setting": ":flashinfer-cubin@0.6.8.post1",
            "//conditions:default": ":flashinfer-cubin@0.6.8.post1",
        }}),
    )

    native.alias(
        name = "flashinfer-python@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":flashinfer-python@0.6.11.post1",
            "@@//:use_vllm_setting": ":flashinfer-python@0.6.18.post1",
            "//conditions:default": ":flashinfer-python@0.6.8.post1",
        }}),
    )

    native.alias(
        name = "nvidia-cutlass-dsl@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cutlass-dsl@4.5.1",
            "@@//:use_vllm_setting": ":nvidia-cutlass-dsl@4.7.1",
            "//conditions:default": ":nvidia-cutlass-dsl@4.4.2",
        }}),
    )

    native.alias(
        name = "nvidia-cutlass-dsl-libs-base@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cutlass-dsl-libs-base@4.5.1",
            "@@//:use_vllm_setting": ":nvidia-cutlass-dsl-libs-base@4.7.1",
            "//conditions:default": ":nvidia-cutlass-dsl-libs-base@4.4.2",
        }}),
    )

    native.alias(
        name = "nvidia-cutlass-dsl-libs-core@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cutlass-dsl-libs-core@4.6.2",
            "@@//:use_vllm_setting": ":nvidia-cutlass-dsl-libs-core@4.7.1",
        }}),
    )

    native.alias(
        name = "nvidia-cutlass-dsl-libs-cu12@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cutlass-dsl-libs-cu12@4.6.2",
            "@@//:use_vllm_setting": ":nvidia-cutlass-dsl-libs-cu12@4.7.1",
        }}),
    )

    native.alias(
        name = "nvidia-cutlass-dsl-libs-cu13@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cutlass-dsl-libs-cu13@4.5.1",
            "@@//:use_vllm_setting": ":nvidia-cutlass-dsl-libs-cu13@4.7.1",
        }}),
    )

    native.alias(
        name = "fastapi@multiple",
        actual = select({{
            # vllm 0.24.0 caps fastapi below what the default group resolves to
            "@@//:use_vllm_setting": ":fastapi@0.136.3",
            "//conditions:default": ":fastapi@0.139.2",
        }}),
    )

    native.alias(
        name = "tilelang@multiple",
        testonly = True,
        actual = select({{
            "@@//:use_vllm_setting": ":tilelang@0.1.12",
            "//conditions:default": ":tilelang@0.1.8",
        }}),
    )

    native.alias(
        name = "outlines-core@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":outlines-core@0.1.26",
            "@@//:use_vllm_setting": ":outlines-core@0.2.14",
        }}),
    )

    native.alias(
        name = "cuda-bindings@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":cuda-bindings@13.4.3",
            "@@//:use_vllm_setting": ":cuda-bindings@13.4.3",
            "//conditions:default": ":cuda-bindings@12.9.4",
        }}),
    )

    native.alias(
        name = "cuda-python@multiple",
        actual = select({{
            "@@//:use_sglang_setting": ":cuda-python@13.4.1",
            "@@//:use_vllm_setting": ":cuda-python@13.4.1",
            "//conditions:default": ":cuda-python@12.9.4",
        }}),
    )

    native.alias(
        name = "cuda-toolkit@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":cuda-toolkit@13.0.2",
            "@@//:use_vllm_setting": ":cuda-toolkit@13.0.3.0",
        }}),
    )

    native.alias(
        name = "nvidia-cublas@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cublas@13.1.0.3",
            "@@//:use_vllm_setting": ":nvidia-cublas@13.1.1.3",
        }}),
    )

    native.alias(
        name = "nvidia-cudnn-cu13@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cudnn-cu13@9.19.0.56",
            "@@//:use_vllm_setting": ":nvidia-cudnn-cu13@9.20.0.48",
        }}),
    )

    native.alias(
        name = "nvidia-cusparselt-cu13@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-cusparselt-cu13@0.8.0",
            "@@//:use_vllm_setting": ":nvidia-cusparselt-cu13@0.8.1",
        }}),
    )

    native.alias(
        name = "nvidia-nccl-cu13@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-nccl-cu13@2.28.9",
            "@@//:use_vllm_setting": ":nvidia-nccl-cu13@2.29.7",
        }}),
    )

    native.alias(
        name = "nvidia-nvjitlink@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":nvidia-nvjitlink@13.0.88",
            "@@//:use_vllm_setting": ":nvidia-nvjitlink@13.4.92",
        }}),
    )

    native.alias(
        name = "nvidia-nvshmem-cu12@multiple",
        testonly = True,
        actual = select({{
            "//conditions:default": ":nvidia-nvshmem-cu12@3.4.5",
        }}),
    )

    native.alias(
        name = "sglang@multiple",
        testonly = True,
        actual = ":sglang@0.5.12.post1",
        target_compatible_with = ["@@//:nvidia_gpu"],
    )

    native.alias(
        name = "quack-kernels@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":quack-kernels@0.4.1",
            "@@//:use_vllm_setting": ":quack-kernels@0.6.5",
        }}),
    )

    native.alias(
        name = "tokenspeed-mla@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":tokenspeed-mla@0.1.1",
            "@@//:use_vllm_setting": ":tokenspeed-mla@0.1.8",
        }}),
    )

    native.alias(
        name = "torchcodec@multiple",
        testonly = True,
        target_compatible_with = select({{
            "@@//:use_sglang_setting": [],
            "@@//:use_vllm_setting": [],
            "//conditions:default": ["@platforms//:incompatible"],
        }}),
        actual = select({{
            "@@//:use_sglang_setting": ":torchcodec@0.11.1",
            "@@//:use_vllm_setting": ":torchcodec@0.16.0",
        }}),
    )

    native.alias(
        name = "vllm@multiple",
        testonly = True,
        actual = ":vllm@0.30.0",
        target_compatible_with = ["@@//:nvidia_gpu"],
    )

    native.alias(
        name = "numpy@multiple",
        testonly = True,
        actual = select({{
            ":_env_python_3.10_aarch64-apple-darwin": ":numpy@2.2.6",
            ":_env_python_3.10_aarch64-unknown-linux-gnu": ":numpy@2.2.6",
            ":_env_python_3.10_x86_64-unknown-linux-gnu": ":numpy@2.2.6",
            ":_env_python_3.10_x86_64-unknown-linux-gnu_amd_gpu": ":numpy@2.2.6",
            ":_env_python_3.10_x86_64-unknown-linux-gnu_nvidia_gpu": ":numpy@2.2.6",
            "//conditions:default": ":numpy@2.3.5",
        }}),
    )

    native.alias(
        name = "scipy@multiple",
        testonly = True,
        actual = select({{
            ":_env_python_3.10_aarch64-apple-darwin": ":scipy@1.14.1",
            ":_env_python_3.10_aarch64-unknown-linux-gnu": ":scipy@1.14.1",
            ":_env_python_3.10_x86_64-unknown-linux-gnu": ":scipy@1.14.1",
            ":_env_python_3.10_x86_64-unknown-linux-gnu_amd_gpu": ":scipy@1.14.1",
            ":_env_python_3.10_x86_64-unknown-linux-gnu_nvidia_gpu": ":scipy@1.14.1",
            "//conditions:default": ":scipy@1.16.3",
        }}),
    )

    extra_build_args = {{
        "copts": ["-fvisibility=default", "-w"],
        "linkopts": select({{
            "@platforms//os:linux": ["-Wl,-z,undefs"],
            "@platforms//os:macos": ["-Wl,-undefined,dynamic_lookup"],
        }}),
        "tags": [
            "manual",
            "requires-network",
        ],
        "exec_properties": {{"dockerNetwork": "bridge"}},
    }}

    build_targets = {{}}
    for version in PYTHON_VERSIONS_DOTTED:
        for platform in ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]:
            alias_name = "_env_python_{{}}_{{}}".format(version, platform)
            build_targets[":" + alias_name] = "@@rules_pycross++environments+rules_pycross_all_environments//:python_{{}}_{{}}.json".format(version, platform)
            native.alias(
                name = alias_name,
                actual = "@@rules_pycross++environments+rules_pycross_all_environments//:python_{{}}_{{}}_config".format(version, platform),
            )

        for gpu in ["nvidia", "amd"]:
            selects.config_setting_group(
                name = "_env_python_{{}}_x86_64-unknown-linux-gnu_{{}}_gpu".format(version, gpu),
                match_all = [
                    "@@//:{{}}_gpu".format(gpu),
                    "_env_python_{{}}_x86_64-unknown-linux-gnu".format(version),
                ],
            )

    for version in [v for v in PYTHON_VERSIONS_DOTTED if v >= "3.14"]:
        for platform in ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]:
            alias_name = "_env_python_{{}}_{{}}-freethreaded".format(version, platform)
            build_targets[":" + alias_name] = "@@rules_pycross++environments+rules_pycross_all_environments//:python_{{}}_{{}}-freethreaded.json".format(version, platform)
            native.alias(
                name = alias_name,
                actual = "@@rules_pycross++environments+rules_pycross_all_environments//:python_{{}}_{{}}-freethreaded_config".format(version, platform),
            )

        for gpu in ["nvidia", "amd"]:
            selects.config_setting_group(
                name = "_env_python_{{}}_x86_64-unknown-linux-gnu-freethreaded_{{}}_gpu".format(version, gpu),
                match_all = [
                    "@@//:{{}}_gpu".format(gpu),
                    "_env_python_{{}}_x86_64-unknown-linux-gnu-freethreaded".format(version),
                ],
            )

    # buildifier: disable=unused-variable
    _target = select(build_targets)

{targets}def repositories():
    \"\"\"Generated package repositories.\"\"\"
{repositories}
"""
