[project]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.0.0"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Add a short description here"
name = "local"

[tasks]
test = "mojo zero.mojo"

[dependencies]
max = "*"
pytorch = ">=2.5.1,<3"
