load("//bazel:api.bzl", "modular_cc_library")

modular_cc_library(
    name = "CPython",
    srcs = glob(["lib/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    local_defines = ["Py_LIMITED_API=0x030A0000"],
    deps = [
        "@llvm-project//llvm:Support",
        "@python_3_9//:python_headers",
    ],
)
