load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "compilation-server",
    srcs = glob(
        ["**/*.test"],
        exclude = [
            "definition.test",  # TODO: Debug and enable
        ],
    ),
    mojo_deps = [
        "//open-source/mojo/stdlib/stdlib",
    ],
    tools = [
        "//KGEN/tools/compilation-server",
    ],
)
