load("//utils/bazel/build/rules:lit.bzl", "lit_tests")

lit_tests(
    srcs = glob(
        [
            "**/*.test",
            "**/*.mojo",
        ],
        exclude = [
            "**/inputs/**",
            "package/test_package/**/*.mojo",
            "package/test_package_with_main/**/*.mojo",
            "format/mojo-format.test",  # TODO: Requires mblack
            "test/test_execution.mojo",  # TODO: Debug crash
            "build/default-output-name.mojo",  # TODO: Linker crash
            "build/mojo-build-def-main.mojo",  # TODO: Linker crash
            "build/mojo-build-fn-main.mojo",  # TODO: Linker crash
            "debug/mojo-lldb-version.mojo",  # TODO: LLDB
        ],
    ),
    data = [
        "//KGEN:CompilerRT.distributable",
        "//KGEN:CompilerRT.shared.file",
        "//KGEN:mojo-build-server",
        "//Kernels/mojo/layout",
        "//Kernels/mojo/stdlib",
        "@llvm-project//compiler-rt:orc_rt",
    ] + glob([
        "**/inputs/**",
        "package/test_package/**/*.mojo",
        "package/test_package_with_main/**/*.mojo",
        "build/inputs/**/*.mojo",
        "test/inputs/**/*.mojo",
        "test/inputs/**/*.🔥",
    ]),
    env = {
        "MODULAR_MOJO_ORCRT_PATH": "$(location @llvm-project//compiler-rt:orc_rt)",
        "MODULAR_MOJO_COMPILERRT_PATH": "$(location //KGEN:CompilerRT.shared.file)",
        "MODULAR_MOJO_COMPILERRT_STATIC_PATH": "$(location //KGEN:CompilerRT.distributable)",
        "MODULAR_CRASH_REPORTING_ENABLED": "false",
        "MODULAR_MOJO_IMPORT_PATH": "$(location //Kernels/mojo/stdlib),$(location //Kernels/mojo/layout)",
        "MODULAR_MOJO_BUILD_SERVER_PATH": "$(location //KGEN:mojo-build-server)",
    },
    tools = [
        "//KGEN:kgen-opt",
        "//KGEN:mojo",
        "@llvm-project//llvm:llvm-objdump",
    ],
)
