load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "mojo-tool",
    srcs = glob(
        [
            "**/*.test",
            "**/*.mojo",
        ],
        exclude = [
            "**/inputs/**",
            "package/test_package/**/*.mojo",
            "package/test_package_with_main/**/*.mojo",
            "package/test_package_moco_773/**/*.mojo",
        ],
    ),
    data = [
        "//utils/mblack:shim.py",
    ] + glob([
        "**/inputs/**",
        "package/test_package/**/*.mojo",
        "package/test_package_with_main/**/*.mojo",
        "package/test_package_moco_773/**/*.mojo",
        "build/inputs/**/*.mojo",
        "test/inputs/**/*.mojo",
        "test/inputs/**/*.🔥",
    ]),
    env = {
        "MODULAR_MOJO_MAX_MBLACK_PATH": "$(location //utils/mblack:shim.py)",
    },
    mojo_deps = [
        "//open-source/max/mojo/kernels/src/layout",
        "//open-source/max/mojo/stdlib/stdlib",
    ],
    tools = [
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/mojo",
        "@llvm-project//llvm:llvm-objdump",
    ],
    deps = [
        "//utils/mblack",
    ],
)
