load("//bazel:api.bzl", "lit_tests")

package(default_visibility = ["//visibility:private"])

lit_tests(
    name = "mojo-tool",
    srcs = glob(
        [
            "**/*.test",
            "**/*.mojo",
        ],
        exclude = [
            "**/inputs/**",
            "package/test_package/**/*.mojo",
            "package/test_package_with_main/**/*.mojo",
            "package/test_package_moco_773/**/*.mojo",
            "package/test_package_fixit/**/*.mojo",
        ],
    ),
    data = [
        "//utils/mblack",
    ] + glob([
        "**/inputs/**",
        "package/test_package/**/*.mojo",
        "package/test_package_with_main/**/*.mojo",
        "package/test_package_moco_773/**/*.mojo",
        "package/test_package_fixit/**/*.mojo",
        "build/inputs/**/*.mojo",
    ]),
    env = {
        "MODULAR_MOJO_MAX_MBLACK_PATH": "$(rootpath //utils/mblack)",
    },
    force_strip = True,  # TODO(MOTO-1190): Debug and fix this duplicate symbol issue
    mojo_deps = [
        "//max:layout",
        "@mojo//:stdlib",
    ],
    tools = [
        "//KGEN/tools/kgen",
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/mojo",
        "@llvm-project//llvm:llvm-as",
        "@llvm-project//llvm:llvm-objdump",
    ],
    deps = [
        "//utils/mblack",
    ],
)
