load("//bazel:api.bzl", "modular_cc_library", "modular_cc_test")

# Header adding test helpers for using gtest with `ErrorOr<T>`.
modular_cc_library(
    name = "TestUtils",
    testonly = True,
    hdrs = [
        "TestUtils.h",
    ],
    visibility = ["//visibility:private"],
    deps = [
        "@llvm-project//third-party/unittest:gtest_main",
    ],
)

modular_cc_test(
    name = "AllocatorTest",
    timeout = "short",
    srcs = ["AllocatorTest.cpp"],
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "AsyncValueTest",
    size = "small",
    srcs = ["AsyncValueTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//AsyncRT:Support",
        "//Support:Globals",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "BufferCacheTest",
    size = "small",
    srcs = [
        "BufferCacheTest.cpp",
        "ScopedEnvVar.h",
    ],
    env = {
        # Set up consistent buffer cache environment for testing
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_SIZE": "25",
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_CHUNK_PERCENT": "25",
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_SELF_CHECK": "True",
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_LOG": "False",
    },
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "GPUBufferCacheTest",
    size = "small",
    srcs = [
        "GPUBufferCacheTest.cpp",
        "ScopedEnvVar.h",
    ],
    env = {
        # Set up consistent buffer cache environment for testing
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_SELF_CHECK": "True",
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_LOG": "False",
    },
    gpu_constraints = select({
        "//:apple_gpu": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tags = ["gpu"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "DebuggingAllocatorsTest",
    size = "small",
    srcs = ["DebuggingAllocatorsTest.cpp"],
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "DeviceContextTest",
    size = "small",
    srcs = ["DeviceContextTest.cpp"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "VirtualDeviceContextTest",
    size = "small",
    srcs = ["VirtualDeviceContextTest.cpp"],
    target_compatible_with = select({
        "@platforms//os:macos": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "GPUDeviceContextTest",
    size = "small",
    srcs = ["GPUDeviceContextTest.cpp"],
    # Setup environment ensuring that the buffer cache is properly configured
    # for the tests being run.
    env = {
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_SIZE": "1073741824",
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_CHUNK_PERCENT": "100",
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_ONLY": "true",
        # Log buffer cache operations for debugging.
        "MODULAR_DEVICE_CONTEXT_BUFFER_CACHE_LOG": "true",
        # These tests exercise the host buffer cache, so give them 8GB
        # to use for the tests.
        "MODULAR_DEVICE_CONTEXT_HOST_BUFFER_CACHE_SIZE": "8589934592",
    },
    gpu_constraints = ["//:has_gpu"],
    tags = ["gpu"],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

# This is a temporary test for the Metal device context. It will be removed once has_gpu is updated to include metal.
# The goal for it is to test the Metal device context implementation on macos.
# TODO(amir): remove this test once has_gpu is updated to include metal.
modular_cc_test(
    name = "MetalGPUDeviceContextTest",
    size = "small",
    srcs = ["GPUDeviceContextTest.cpp"],
    gpu_constraints = ["//:apple_gpu"],
    tags = ["gpu"],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "MetalDeviceContextTest",
    size = "small",
    srcs = ["MetalDeviceContextTest.cpp"],
    gpu_constraints = ["//:apple_gpu"],
    tags = ["gpu"],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "CUDADeviceContextTest",
    size = "small",
    srcs = ["CUDADeviceContextTest.cpp"],
    gpu_constraints = ["//:nvidia_gpu"],
    tags = ["gpu"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "CUDAMultiDeviceContextTest",
    size = "small",
    srcs = ["CUDADeviceContextTest.cpp"],
    gpu_constraints = [
        "//:nvidia_gpu",
        "//:has_multi_gpu",
    ],
    tags = ["gpu"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "GPUDeviceTest",
    size = "small",
    srcs = ["GPUDeviceTest.cpp"],
    gpu_constraints = ["//:has_gpu"],
    tags = ["gpu"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "MultiGPUDeviceTest",
    size = "small",
    srcs = ["MultiGPUDeviceTest.cpp"],
    gpu_constraints = ["//:has_multi_gpu"],
    tags = ["gpu"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
        "//Support:Buffer",
    ],
)

modular_cc_test(
    name = "RuntimeTest",
    size = "small",
    srcs = ["RuntimeTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "WorkQueueTest",
    size = "small",
    srcs = ["WorkQueueTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//AsyncRT:DeviceContextImpl",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "TypeIDTest",
    size = "small",
    srcs = ["TypeIDTest.cpp"],
    deps = [
        "//AsyncRT:Support",
        "//Support:Base",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "TimerHeapTest",
    size = "small",
    srcs = ["TimerHeapTest.cpp"],
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//AsyncRT:Support",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "NixlTest",
    size = "small",
    srcs = ["NixlTest.cpp"],
    # Even though this is just a CPU transfer, we still require a GPU because
    # we build NIXL to necessarily pick up either CUDA or ROCm.
    gpu_constraints = [
        "//:has_gpu",
    ],
    tags = ["gpu"],
    deps = [
        "//AsyncRT:NIXL",
    ],
)

modular_cc_test(
    name = "NixlTestUcx",
    size = "small",
    srcs = ["NixlTestUcx.cpp"],
    gpu_constraints = [
        "//:has_gpu",
        "//:has_multi_gpu",
    ],
    tags = ["gpu"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
        "//AsyncRT:NIXL",
        "//Support:Base",
        "@llvm-project//llvm:Support",
    ],
)
