load("//bazel:api.bzl", "modular_cc_library", "modular_cc_test")

# Header adding test helpers for using gtest with `ErrorOr<T>`.
modular_cc_library(
    name = "TestUtils",
    testonly = True,
    hdrs = [
        "TestUtils.h",
    ],
    visibility = ["//visibility:private"],
    deps = [
        "@llvm-project//third-party/unittest:gtest_main",
    ],
)

modular_cc_test(
    name = "AllocatorTest",
    timeout = "short",
    srcs = ["AllocatorTest.cpp"],
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "AsyncValueTest",
    size = "small",
    srcs = ["AsyncValueTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "DebuggingAllocatorsTest",
    size = "small",
    srcs = ["DebuggingAllocatorsTest.cpp"],
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "DeviceContextTest",
    size = "small",
    srcs = ["DeviceContextTest.cpp"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "GPUDeviceContextTest",
    size = "small",
    srcs = ["GPUDeviceContextTest.cpp"],
    gpu_constraints = ["//:has_gpu"],
    tags = ["gpu"],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "CUDADeviceContextTest",
    size = "small",
    srcs = ["CUDADeviceContextTest.cpp"],
    gpu_constraints = ["//:has_gpu"],
    tags = ["gpu"],
    deps = [
        ":TestUtils",
        "//AsyncRT:DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "ResourceTest",
    size = "small",
    srcs = ["ResourceTest.cpp"],
    deps = ["//AsyncRT:Support"],
)

modular_cc_test(
    name = "RuntimeTest",
    size = "small",
    srcs = ["RuntimeTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "TypeIDTest",
    size = "small",
    srcs = ["TypeIDTest.cpp"],
    deps = [
        "//AsyncRT:Support",
        "//Support:Base",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "TimerHeapTest",
    size = "small",
    srcs = ["TimerHeapTest.cpp"],
    deps = [
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//AsyncRT:Support",
        "//Support:Globals",
    ],
)
