//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include "AsyncRT/DeviceContext/DeviceContext.h"

#include "gtest/gtest.h"

#include <cstdint>
#include <cstring>
#include <iostream>

using namespace M::AsyncRT;
using M::ErrorOr;
using M::ErrorOrSuccess;

namespace {

TEST(CUDAMultiDeviceContextTest, MultiGPUKernels) {
  const char *p2p_copy_ptx = R"PTX(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-32688072
// Cuda compilation tools, release 12.1, V12.1.105
// Based on NVVM 7.0.1
//
// Compiled by nvcc -ptx
// Simple copy kernel
// __global__ void p2pMemcpyKernel(float* dst, float* src, size_t numElements) {
//     int idx = blockIdx.x * blockDim.x + threadIdx.x;
//     if (idx < numElements) {
//         dst[idx] = src[idx];
//     }
// }

.version 8.1
.target sm_52
.address_size 64

	// .globl	_Z15p2pMemcpyKernelPfS_m

.visible .entry _Z15p2pMemcpyKernelPfS_m(
	.param .u64 _Z15p2pMemcpyKernelPfS_m_param_0,
	.param .u64 _Z15p2pMemcpyKernelPfS_m_param_1,
	.param .u64 _Z15p2pMemcpyKernelPfS_m_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<5>;
	.reg .b64 	%rd<10>;


	ld.param.u64 	%rd2, [_Z15p2pMemcpyKernelPfS_m_param_0];
	ld.param.u64 	%rd3, [_Z15p2pMemcpyKernelPfS_m_param_1];
	ld.param.u64 	%rd4, [_Z15p2pMemcpyKernelPfS_m_param_2];
	mov.u32 	%r1, %ctaid.x;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r3, %tid.x;
	mad.lo.s32 	%r4, %r1, %r2, %r3;
	cvt.s64.s32 	%rd1, %r4;
	setp.ge.u64 	%p1, %rd1, %rd4;
	@%p1 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd5, %rd3;
	shl.b64 	%rd6, %rd1, 2;
	add.s64 	%rd7, %rd5, %rd6;
	ld.global.f32 	%f1, [%rd7];
	cvta.to.global.u64 	%rd8, %rd2;
	add.s64 	%rd9, %rd8, %rd6;
	st.global.f32 	[%rd9], %f1;

$L__BB0_2:
	ret;

}
)PTX";

  ErrorOr<int> err_num = Device::numberOfDevices("cuda");
  ASSERT_FALSE(err_num) << err_num.getError() << "\n";
  int num_devices = err_num.get();
  std::cerr << "Number of CUDA devices: " << num_devices << "\n";

  ErrorOr<DeviceContextRef> err_ctx = DeviceContext::create("cuda", 0);
  ASSERT_FALSE(err_ctx) << err_ctx.getError() << "\n";
  DeviceContextRef src_ctx = std::move(err_ctx.get());
  ASSERT_TRUE(src_ctx);

  for (int cur_device_id = -1; cur_device_id < num_devices; cur_device_id++) {
    DeviceContextRef dst_ctx;
    if (cur_device_id < 0) {
      std::cerr << "Copying within the same device context.\n";
      dst_ctx = DeviceContextRef::copy(src_ctx.getPointer());
    } else {
      std::cerr << "Copying from context on GPU[0] to context on GPU["
                << cur_device_id << "].\n";

      ErrorOr<DeviceContextRef> err_ctx =
          DeviceContext::create("cuda", cur_device_id);
      ASSERT_FALSE(err_ctx) << err_ctx.getError() << "\n";
      dst_ctx = std::move(err_ctx.get());
    }
    ASSERT_TRUE(dst_ctx);

    if (src_ctx->device().id() != dst_ctx->device().id()) {
      ErrorOr<bool> err_bool = src_ctx->device().canAccess(dst_ctx->device());
      ASSERT_FALSE(err_bool) << err_bool.getError() << "\n";
      ASSERT_TRUE(err_bool.get());

      ErrorOrSuccess err = src_ctx->enablePeerAccess(*dst_ctx);
      ASSERT_FALSE(err) << err.getError() << "\n";

      err = dst_ctx->enablePeerAccess(*src_ctx);
      ASSERT_FALSE(err) << err.getError() << "\n";
    }

    const size_t num_elems = 256;
    const size_t alloc_len = 4 * num_elems;

    char *check_data = new char[alloc_len];
    // Initialize check_data with a pattern specific for this run.
    for (size_t i = 0; i < alloc_len; i++) {
      check_data[i] = cur_device_id + i;
    }

    ErrorOr<void *> err_ptr = src_ctx->malloc_host(alloc_len);
    EXPECT_FALSE(err_ptr) << err_ptr.getError() << "\n";
    void *src_ptr = err_ptr.get();
    EXPECT_NE(src_ptr, nullptr);

    ErrorOr<DeviceBufferRef> err_ref = src_ctx->createBuffer(alloc_len, 1);
    EXPECT_FALSE(err_ref) << err_ref.getError() << "\n";
    DeviceBufferRef src_buf = std::move(err_ref.get());
    EXPECT_TRUE(src_buf);

    err_ref = dst_ctx->createBuffer(alloc_len, 1);
    EXPECT_FALSE(err_ref) << err_ref.getError() << "\n";
    DeviceBufferRef dst_buf = std::move(err_ref.get());
    EXPECT_TRUE(dst_buf);

    char *dst_ptr = static_cast<char *>(malloc(alloc_len));
    EXPECT_NE(dst_ptr, nullptr);
    // Initialize with known bad values.
    for (size_t i = 0; i < alloc_len; i++) {
      // Use a different factor for i than the check_data, so that we can't ever
      // overlap.
      dst_ptr[i] = -static_cast<char>((7 + 2 * i) & 127);
    }

    // Copy between different buffers.
    memcpy(src_ptr, check_data, alloc_len);
    ErrorOrSuccess err = src_ctx->copyToDevice(*src_buf, src_ptr);
    EXPECT_FALSE(err) << err.getError() << "\n";

    DeviceFunction::SignatureBuilder sig =
        DeviceFunction::SignatureBuilder().addBuffer().addBuffer().addUInt64();
    ErrorOr<DeviceFunctionRef> err_fun = src_ctx->loadFunction(
        "my_module", "_Z15p2pMemcpyKernelPfS_m", sig, p2p_copy_ptx);
    EXPECT_FALSE(err_fun) << err_fun.getError() << "\n";
    DeviceFunctionRef device_function = std::move(err_fun.get());
    EXPECT_TRUE(device_function);

    constexpr uint32_t block_dim = 256;

    err = src_ctx->enqueueFunctionExec(
        *device_function, num_elems / block_dim, 1, 1, block_dim, 1, 1, 0,
        *device_function->buildArguments(*dst_buf, *src_buf, num_elems));
    EXPECT_FALSE(err) << err.getError() << "\n";

    err = src_ctx->synchronize();
    EXPECT_FALSE(err) << err.getError() << "\n";

    err = dst_ctx->enqueueCopyFromDevice(dst_ptr, *dst_buf);
    EXPECT_FALSE(err) << err.getError() << "\n";

    // Ensure that all copy operations have finished.
    err = dst_ctx->synchronize();
    err = src_ctx->synchronize();
    EXPECT_FALSE(err) << err.getError() << "\n";

    EXPECT_EQ(memcmp(dst_ptr, check_data, alloc_len), 0);

    free(dst_ptr);
    err = src_ctx->free_host(src_ptr);
    EXPECT_FALSE(err) << err.getError() << "\n";
  }
}

} // namespace
