load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "mojo-parser",
    srcs = glob(["**/*.mojo"]),
    data = [
        "//Kernels/mojo/_mlir:_mlir_srcs",
        "//Kernels/test:mlirc",
        "//open-source/mojo/stdlib/stdlib:stdlib_srcs",
    ],
    env = {
        "MODULAR_MAX_MLIRC_LIB": "$(location //Kernels/test:mlirc)",
        "MODULAR_MOJO_IMPORT_SRCS": "$(locations //Kernels/mojo/_mlir:_mlir_srcs) $(locations //open-source/mojo/stdlib/stdlib:stdlib_srcs)",
    },
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/kgen-translate",
        "//KGEN/tools/mojo",
    ],
)
