//===- Meta.td ------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This is the top level file for the Meta dialect.
//
//===----------------------------------------------------------------------===//

#ifndef META_TD
#define META_TD

include "KGEN/MetaDialect/MetaDialect.td"
include "KGEN/MetaDialect/MetaTypes.td"
include "KGEN/MetaDialect/MetaOps.td"

#endif // KGEN_TD
