load("//bazel:api.bzl", "kgen_kernel", "modular_cc_binary")

package(default_visibility = ["//visibility:public"])

kgen_kernel(
    name = "mojo_build_server",
    src = "mojo_build_server.mojo",
    features = ["-asan"],  # TODO: Fails to link __asan_gen likely only with older clang versions
    deps = [
        "//open-source/mojo/stdlib/stdlib",
    ],
)

modular_cc_binary(
    name = "mojo-build-server",
    srcs = ["empty.c"],
    deps = [
        ":mojo_build_server",
        "//KGEN:CompilerRT",
        "//KGEN:MojoBuild",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
    ],
)
