load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "crash-report-path-info",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//LLCL:Init",
        "//LLCL:RuntimeGlobals.static",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:CrashReporting",
        "//Support:Globals.static",
    ],
)
