//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file is a header-guarded wrapper around LLVM's OptParser.td. Once that
// file is modified to use header guards, this file can be removed.
//
//===----------------------------------------------------------------------===//

#ifndef SUPPORT_OPTION_OPTPARSER_TD
#define SUPPORT_OPTION_OPTPARSER_TD

include "llvm/Option/OptParser.td"

#endif // SUPPORT_OPTION_OPTPARSER_TD
