load("@pip_deps//:requirements.bzl", "requirement")
load("//utils/bazel/build/rules:lit.bzl", "lit_tests")

lit_tests(
    name = "test",
    srcs = glob(["**/*.lldb"]),
    custom_substitutions = {
        # Mirrored from lit.cfg.py to avoid searching $PATH for 'mojo'
        "%repl": "$(rlocationpath //KGEN/tools/mojo) repl --source-quietly -S $(rlocationpath //utils:lit-lldb-init.in)",
        "\\\\$MODULAR_DERIVED_PATH/third-party/llvm-project/build/bin/lldb": "$(rlocationpath //KGEN:mojo-lldb)",
        "source \\\\$MODULAR_DERIVED_PATH/autovenv/bin/activate": "true",
    },
    data = glob(["Inputs/*.mojo"]) + [
        "//:libpython",
        "//KGEN:MojoLLDB",
        "//KGEN:gdb-server",
        "//KGEN:mojo-lldb",
        "//KGEN/tools/mojo-repl-entry-point",
        "//utils:lit-lldb-init.in",
    ],
    env = {
        "LLDB_DEBUGSERVER_PATH": "$(location //KGEN:gdb-server)",
        "MODULAR_MOJO_LLDB_PATH": "$(location //KGEN:mojo-lldb)",
        "MODULAR_MOJO_LLDB_PLUGIN_PATH": "$(location //KGEN:MojoLLDB)",
        "MODULAR_MOJO_REPL_ENTRY_POINT": "$(location //KGEN/tools/mojo-repl-entry-point)",
        "MOJO_PYTHON_LIBRARY": "$(location //:libpython)",
    },
    mojo_deps = [
        "//Kernels/mojo/buffer",
        "//Kernels/mojo/gpu",
        "//Kernels/mojo/runtime",
        "//open-source/mojo/stdlib/stdlib:stdlib",
    ],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],  # __jit_debug_descriptor exists in liblldb and libMojoLLDB
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/mojo",
    ],
    deps = [
        requirement("matplotlib"),
    ],
)
