load("//bazel:api.bzl", "lit_tests", "requirement")

lit_tests(
    name = "test",
    srcs = glob(["**/*.lldb"]),
    custom_substitutions = {
        "%repl": "$(rlocationpath //KGEN/tools/mojo) repl --source-quietly -S $(rlocationpath //utils:lit-lldb-init.in)",
        "%mojo-lldb": "$(rlocationpath //KGEN:mojo-lldb)",
    },
    data = glob(["Inputs/*.mojo"]) + [
        "//KGEN:mojo-lldb",
        "//utils:lit-lldb-init.in",
    ],
    mojo_deps = [
        "//Kernels/mojo/runtime",
        "//open-source/max/mojo/stdlib/stdlib",
    ],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],  # __jit_debug_descriptor exists in liblldb and libMojoLLDB
        "//:tsan": ["@platforms//:incompatible"],
        "//:ubsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/mojo",
    ],
    deps = [
        requirement("matplotlib"),
    ],
)
