load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "kgen-reduce",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
    deps = [
        "//AsyncRT:Init",
        "//AsyncRT:RuntimeGlobals",
        "//KGEN:Compiler",
        "//KGEN:CompilerRT",
        "//KGEN:ExecutionEngine",
        "//KGEN:HLCFDialect",
        "//KGEN:KGENDialect",
        "//KGEN:MojoParser",
        "//KGEN:ObjectCompiler",
        "//KGEN:Pipeline",
        "//KGEN:ToolCommon",
        "//KGEN:TransformUtils",
        "//Support:Base",
        "//Support:Globals",
        "@llvm-project//mlir:MlirOptLib",
    ],
)
