load("@pip_deps//:requirements.bzl", "requirement")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

exports_files([
    "pyproject.toml",
    "shim.py",
])

py_binary(
    name = "mblack_main",
    srcs = ["src/mblack/__main__.py"],
    main = "src/mblack/__main__.py",
    deps = [
        ":mblack",
    ],
)

py_binary(
    name = "mblack",
    srcs = glob(["src/**/*.py"]),
    data = glob(["src/**/*.txt"]),
    imports = ["src"],
    main = "src/mblack/__main__.py",
    deps = [
        requirement("click"),
        requirement("mypy_extensions"),
        requirement("pathspec"),
        requirement("platformdirs"),
        requirement("tomli"),
    ],
)

pkg_files(
    name = "mblack_files",
    srcs = glob(
        ["**"],
        exclude = ["shim.py"],
    ),
    prefix = "mblack",
    strip_prefix = strip_prefix.from_pkg(""),
)
