load("//bazel:api.bzl", "modular_py_binary", "modular_py_library", "modular_py_test", "pkg_files", "requirement", "strip_prefix")

package(default_visibility = ["//visibility:public"])

exports_files([
    "LICENSE",
    "src/mblib2to3/Grammar.txt",
    "src/mblib2to3/PatternGrammar.txt",
])

modular_py_library(
    name = "mblack-lib",
    srcs = glob(
        ["src/**/*.py"],
        exclude = ["src/mblack/__main__.py"],
    ),
    data = glob(["src/**/*.txt"]),
    imports = ["src"],
    deps = [
        requirement("click"),
        requirement("mypy-extensions"),
        requirement("pathspec"),
        requirement("platformdirs"),
        requirement("tomli"),
    ],
)

modular_py_binary(
    name = "mblack",
    srcs = ["src/mblack/__main__.py"],
    main = "src/mblack/__main__.py",
    deps = [":mblack-lib"],
)

modular_py_test(
    name = "unit_tests",
    # One layer deep, don't grab `data`
    srcs = glob(
        ["tests/*.py"],
        exclude = [
            # We don't support blackd or ipynb notebooks.
            "tests/test_blackd.py",
            "tests/test_ipynb.py",
        ],
    ),
    data = glob(["tests/data/**"]) + [
        "pyproject.toml",
        "tests/empty.toml",
        "tests/test.toml",
    ],
    imports = ["."],
    deps = [
        ":mblack",
    ],
)

pkg_files(
    name = "mblack_files",
    srcs = glob(["**"]),
    prefix = "mblack",
    strip_prefix = strip_prefix.from_pkg(""),
)
