load("//bazel:api.bzl", "modular_py_binary", "pkg_files", "requirement", "strip_prefix")

package(default_visibility = ["//visibility:public"])

exports_files([
    "pyproject.toml",
    "shim.py",
])

modular_py_binary(
    name = "mblack",
    srcs = glob(["src/**/*.py"]),
    data = glob(["src/**/*.txt"]),
    imports = ["src"],
    main = "src/mblack/__main__.py",
    tags = ["no-mypy"],  # mypy_extensions conflicts with builtin from mypy
    deps = [
        requirement("click"),
        requirement("mypy-extensions"),
        requirement("pathspec"),
        requirement("platformdirs"),
        requirement("tomli"),
    ],
)

pkg_files(
    name = "mblack_files",
    srcs = glob(
        ["**"],
        exclude = ["shim.py"],
    ),
    prefix = "mblack",
    strip_prefix = strip_prefix.from_pkg(""),
)
