load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "cache-mgr",
    srcs = glob(["*.cpp"]),
    deps = [
        "//AsyncRT:Init",
        "//AsyncRT:RuntimeGlobals",
        "//Cache",
        "//Support:CommonCLOptions",
        "//Support:Globals",
        "@llvm-project//mlir:Support",
    ],
)
