load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
load("//bazel:api.bzl", "modular_cc_library", "modular_relink_object", "modular_shared_library")

bool_flag(
    name = "worker_stats",
    build_setting_default = False,
)

config_setting(
    name = "worker_stats_setting",
    flag_values = {":worker_stats": "true"},
)

modular_cc_library(
    name = "CompilerSupport.headers",
    hdrs = glob([
        "include/AsyncRT/CompilerSupport/*.h",
    ]),
    tags = ["no-clang-tidy-headers"],
    visibility = ["//Support:__subpackages__"],
    deps = [
        ":Runtime.headers",
        "//Support:Threading",
    ],
)

modular_cc_library(
    name = "DeviceContext.headers",
    hdrs = [
        "include/AsyncRT/DeviceContext/DeviceContext.h",
    ],
    visibility = ["//visibility:private"],
    deps = [
        "//Support:Base",
        "//Support:Buffer",
        "//Support:Configuration",
    ],
)

modular_cc_library(
    name = "Runtime.headers",
    hdrs = glob([
        "include/AsyncRT/Runtime/*.h",
        "include/AsyncRT/Runtime/Globals/*.h",
    ]) + [
        "include/AsyncRT/ForwardDecls.h",
    ],
    tags = ["no-clang-tidy-headers"],
    visibility = ["//visibility:private"],
    deps = [
        ":Support.headers",
        "//Support:Profiling.headers",
    ],
)

modular_cc_library(
    name = "Support.headers",
    hdrs = glob(["include/AsyncRT/Support/*.h"]),
    tags = ["no-clang-tidy-headers"],
    visibility = ["//visibility:private"],
)

modular_cc_library(
    name = "CompilerSupport",
    srcs = glob(["lib/CompilerSupport/*.cpp"]),
    hdrs = glob(["include/AsyncRT/CompilerSupport/*.h"]),
    tags = ["no-clang-tidy-headers"],
    deps = [
        ":Runtime",
    ],
)

# Library target exporting the different AsyncRT bindings for Mojo.
modular_shared_library(
    name = "DeviceContext",
    srcs = [
        "lib/DeviceContext/MojoBindings.cpp",
    ],
    hdrs = [
        "include/AsyncRT/DeviceContext/BinaryID.h",
    ],
    local_defines = [
        "MODULAR_BUILDING_LIBRARY",
    ],
    output_name = "AsyncRTMojoBindings",
    deps = [
        ":DeviceContext.headers",
        ":DeviceContextImpl",
        "//Support:BinaryID",
    ],
)

modular_cc_library(
    name = "DeviceContextImpl",
    srcs = [
        "lib/DeviceContext/BufferCache.cpp",
        "lib/DeviceContext/BufferCache.h",
        "lib/DeviceContext/CPU/CpuDeviceContext.cpp",
        "lib/DeviceContext/CPU/CpuDeviceContext.h",
        "lib/DeviceContext/CUDA/CUDADeviceContext.cpp",
        "lib/DeviceContext/CUDA/CUDADeviceContext.h",
        "lib/DeviceContext/CUDA/CUDADriver.cpp",
        "lib/DeviceContext/CUDA/CUDADriver.h",
        "lib/DeviceContext/CUDA/NVML.cpp",
        "lib/DeviceContext/CUDA/NVML.h",
        "lib/DeviceContext/DeviceContext.cpp",
        "lib/DeviceContext/HIP/HIPDeviceContext.cpp",
        "lib/DeviceContext/HIP/HIPDeviceContext.h",
        "lib/DeviceContext/HIP/HIPDriver.cpp",
        "lib/DeviceContext/HIP/HIPDriver.h",
    ],
    visibility = ["//AsyncRT:__subpackages__"],
    deps = [
        ":DeviceContext.headers",
        ":RuntimeGlobals",
        "//Support:ML",
    ] + select({
        "//:linux_x86_64": ["@nvptxcompiler_x86_64//:nvptxcompiler"],
        "//:linux_aarch64": ["@nvptxcompiler_aarch64//:nvptxcompiler"],
        "//conditions:default": [],
    }),
    alwayslink = True,
)

modular_cc_library(
    name = "Runtime",
    srcs = glob(["lib/Runtime/*.cpp"]),
    hdrs = glob([
        "include/AsyncRT/Runtime/Globals/*.h",
        "include/AsyncRT/Runtime/*.h",
    ]) + [
        "include/AsyncRT/ForwardDecls.h",
    ],
    local_defines = select({
        "//:asyncrt_no_affinity_setting": ["ASYNCRT_NO_AFFINITY=1"],
        "//conditions:default": [],
    }) + select({
        ":worker_stats_setting": ["ASYNCRT_WORKER_STATS=1"],
        "//conditions:default": [],
    }),
    deps = [
        ":Runtime.headers",
        ":Support",
        "//Support:ADT",
        "//Support:Profiling",
    ],
)

modular_shared_library(
    name = "RuntimeGlobals",
    srcs = glob(["lib/Runtime/Globals/*.cpp"]),
    output_name = "AsyncRTRuntimeGlobals",
    deps = [
        ":Runtime.headers",
        "//Support:BinaryID",
        "//Support:SymbolExport",
        "//bazel/third-party:tcmalloc",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_library(
    name = "Support",
    srcs = glob(["lib/Support/*.cpp"]),
    hdrs = glob(["include/AsyncRT/Support/*.h"]),
    local_defines = select({
        "@platforms//os:linux": ["MODULAR_HAVE_SEM_TIMEDWAIT"],
        "//conditions:default": [],
    }),
    tags = ["no-clang-tidy-headers"],
    deps = [
        "//Support:MArchTarget",
        "//Support:Threading",
    ],
)

modular_cc_library(
    name = "NIXL",
    srcs = glob(
        [
            "lib/NIXL/**/*.cpp",
        ],
        exclude = [
            "lib/NIXL/plugins/ucx/**",
            "lib/NIXL/utils/ucx/**",
        ],
    ),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/**/*.h",
        ],
        exclude = [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    include_prefix = "",
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//AsyncRT:Support",
        "//Support:Threading",
        "@llvm-project//llvm:Support",
    ],
    # This is needed for `utils/sync-stubfiles.py` to work
    alwayslink = True,
)

modular_shared_library(
    # NOTE: currently the target name is coupled to NIXL's plugin discovery
    # logic, which looks for `libplugin_*.so`.
    name = "plugin_ucx",
    srcs = glob([
        "lib/NIXL/plugins/ucx/**",
        "lib/NIXL/utils/ucx/**",
    ]),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    linkopts = select({
        # This allows us to ignore missing libcuda.so.1 and libnvidia-ml.so.1
        # symbols at link time. But now it requires that they are available at
        # runtime when this plugin is loaded. This shared lib does not automatically
        # load them if they are missing. They should be loaded in advance to loading
        # this plugin.
        "@platforms//os:linux": [
            "-Wl,-z,undefs",
        ],
        "@platforms//os:macos": [
            "-Wl,-undefined,dynamic_lookup",
        ],
    }),
    tags = ["maybe-unused"],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//AsyncRT:DeviceContextImpl",
        "//AsyncRT:NIXL",
        "//AsyncRT:Support",
        "@ucx_prebuilt//:ucx",
    ],
)

modular_relink_object(
    name = "plugin_ucx.fixed",
    src = ":plugin_ucx",
    new_root = "../../lib",
    use_unique_name = True,
    visibility = ["//visibility:public"],
)
