load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
load("//bazel:api.bzl", "cc_autolink_deps", "modular_cc_library", "modular_shared_library")
load("//bazel:config.bzl", "ALLOW_UNUSED_TAG")

bool_flag(
    name = "worker_stats",
    build_setting_default = False,
)

config_setting(
    name = "worker_stats_setting",
    flag_values = {":worker_stats": "true"},
)

modular_cc_library(
    name = "CompilerSupport.headers",
    hdrs = glob([
        "include/AsyncRT/CompilerSupport/*.h",
    ]),
    tags = ["no-clang-tidy-headers"],
    visibility = ["//Support:__subpackages__"],
    deps = [
        ":Runtime.headers",
        "//Support:Threading",
    ],
)

modular_cc_library(
    name = "DeviceContext.headers",
    hdrs = [
        "include/AsyncRT/DeviceContext/DeviceContext.h",
    ],
    visibility = ["//visibility:private"],
    deps = [
        "//Support:Base",
        "//Support:Buffer",
        "//Support:Configuration",
    ],
)

modular_cc_library(
    name = "Runtime.headers",
    hdrs = glob([
        "include/AsyncRT/Runtime/*.h",
        "include/AsyncRT/Runtime/Globals/*.h",
    ]) + [
        "include/AsyncRT/ForwardDecls.h",
    ],
    tags = ["no-clang-tidy-headers"],
    visibility = ["//visibility:private"],
    deps = [
        ":Support.headers",
        "//Support:Profiling.headers",
    ],
)

modular_cc_library(
    name = "Support.headers",
    hdrs = glob(["include/AsyncRT/Support/*.h"]),
    tags = ["no-clang-tidy-headers"],
    visibility = ["//visibility:private"],
)

modular_cc_library(
    name = "CompilerSupport",
    srcs = glob(["lib/CompilerSupport/*.cpp"]),
    hdrs = glob(["include/AsyncRT/CompilerSupport/*.h"]),
    tags = ["no-clang-tidy-headers"],
    deps = [
        ":Runtime",
        "//Support:Context",
    ],
)

# Library target exporting the different AsyncRT bindings for Mojo.
modular_shared_library(
    name = "DeviceContext",
    srcs = [
        "lib/DeviceContext/MojoBindings.cpp",
    ],
    hdrs = [
        "include/AsyncRT/DeviceContext/BinaryID.h",
    ],
    output_name = "AsyncRTMojoBindings",
    deps = [
        ":DeviceContext.headers",
        ":DeviceContextImpl",
        "//Support:BinaryID",
    ],
)

modular_cc_library(
    name = "DeviceContextImpl",
    srcs = [
        "lib/DeviceContext/BufferCache.cpp",
        "lib/DeviceContext/BufferCache.h",
        "lib/DeviceContext/CPU/CpuDeviceContext.cpp",
        "lib/DeviceContext/CPU/CpuDeviceContext.h",
        "lib/DeviceContext/CUDA/CUDACompilationDriver.cpp",
        "lib/DeviceContext/CUDA/CUDACompilationDriver.h",
        "lib/DeviceContext/CUDA/CUDADeviceContext.cpp",
        "lib/DeviceContext/CUDA/CUDADeviceContext.h",
        "lib/DeviceContext/CUDA/CUDADriver.cpp",
        "lib/DeviceContext/CUDA/CUDADriver.h",
        "lib/DeviceContext/CUDA/NVML.cpp",
        "lib/DeviceContext/CUDA/NVML.h",
        "lib/DeviceContext/DeviceContext.cpp",
        "lib/DeviceContext/HIP/HIPDeviceContext.cpp",
        "lib/DeviceContext/HIP/HIPDeviceContext.h",
        "lib/DeviceContext/HIP/HIPDriver.cpp",
        "lib/DeviceContext/HIP/HIPDriver.h",
        "lib/DeviceContext/Metal/MetalDeviceContext.cpp",
        "lib/DeviceContext/Metal/MetalDeviceContext.h",
        "lib/DeviceContext/Metal/MetalImpl.cpp",
        "lib/DeviceContext/Metal/MetalImpl.hpp",
    ],
    visibility = ["//AsyncRT:__subpackages__"],
    deps = [
        ":DeviceContext.headers",
        ":RuntimeGlobals",
        "//Support:ML",
    ] + select({
        "@platforms//os:linux": [":NVPTX"],
        "@platforms//os:macos": ["@metal-cpp//:metal-cpp"],
        "//conditions:default": [],
    }),
    alwayslink = True,
)

modular_cc_library(
    name = "Runtime",
    srcs = glob(["lib/Runtime/*.cpp"]),
    hdrs = glob([
        "include/AsyncRT/Runtime/Globals/*.h",
        "include/AsyncRT/Runtime/*.h",
    ]) + [
        "include/AsyncRT/ForwardDecls.h",
    ],
    local_defines = select({
        "//:asyncrt_no_affinity_setting": ["ASYNCRT_NO_AFFINITY=1"],
        "//conditions:default": [],
    }) + select({
        ":worker_stats_setting": ["ASYNCRT_WORKER_STATS=1"],
        "//conditions:default": [],
    }),
    deps = [
        ":Runtime.headers",
        ":Support",
        "//Support:ADT",
        "//Support:Context",
        "//Support:Profiling",
    ],
)

modular_shared_library(
    name = "RuntimeGlobals",
    srcs = glob(["lib/Runtime/Globals/*.cpp"]),
    output_name = "AsyncRTRuntimeGlobals",
    deps = [
        ":Runtime.headers",
        "//Support:BinaryID",
        "//Support:SymbolExport",
        "//bazel/third-party:tcmalloc",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_library(
    name = "Support",
    srcs = glob(["lib/Support/*.cpp"]),
    hdrs = glob(["include/AsyncRT/Support/*.h"]),
    tags = ["no-clang-tidy-headers"],
    deps = [
        "//Support:MArchTarget",
        "//Support:Threading",
    ],
)

modular_cc_library(
    name = "NIXL",
    data = select({
        "//:linux_x86_64": [
            ":plugin_ucx_cpu",
            ":plugin_ucx_cuda",
            ":plugin_ucx_cuda_verbs",
            ":plugin_ucx_rocm",
            ":plugin_ucx_rocm_verbs",
        ],
        "//conditions:default": [],
    }),
    deps = [
        ":NIXLLibOnly",
        "//AsyncRT:DeviceContext",
    ],
)

modular_cc_library(
    name = "NIXLLibOnly",
    srcs = glob(
        [
            "lib/NIXL/**/*.cpp",
        ],
        exclude = [
            "lib/NIXL/plugins/ucx/**",
            "lib/NIXL/utils/ucx/**",
        ],
    ),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/**/*.h",
        ],
        exclude = [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    include_prefix = "",
    strip_include_prefix = "include",
    tags = ["no-clang-tidy"],  # Copied code doesn't conform to our style
    visibility = ["//visibility:private"],
    deps = [
        "//AsyncRT:Support",
        "//Support:Threading",
        "@llvm-project//llvm:Support",
    ],
    # This is needed for `utils/sync-stubfiles.py` to work
    alwayslink = True,
)

modular_shared_library(
    # NOTE: currently the target name is coupled to NIXL's plugin discovery
    # logic, which looks for `libplugin_*.so`.
    name = "plugin_ucx_cpu",
    srcs = glob([
        "lib/NIXL/plugins/ucx/**",
        "lib/NIXL/utils/ucx/**",
    ]),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    tags = [
        ALLOW_UNUSED_TAG,
        "no-clang-tidy",  # Copied code doesn't conform to our style
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DeviceContextImpl",
        ":NIXLLibOnly",
        ":NVPTX",
        ":Support",
        "@ucx_prebuilt//:ucx_cpu",
    ],
)

modular_shared_library(
    # NOTE: currently the target name is coupled to NIXL's plugin discovery
    # logic, which looks for `libplugin_*.so`.
    name = "plugin_ucx_cuda",
    srcs = glob([
        "lib/NIXL/plugins/ucx/**",
        "lib/NIXL/utils/ucx/**",
    ]),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    linkopts = select({
        # This allows us to ignore missing libcuda.so.1, libnvidia-ml.so.1 etc.
        # symbols at link time. But now it requires that they are available at
        # runtime when this plugin is loaded. This shared lib does not automatically
        # load them if they are missing. They should be loaded in advance to loading
        # this plugin.
        "@platforms//os:linux": [
            "-Wl,-z,undefs",
            "-Wl,-rpath,$ORIGIN/../../lib",
        ],
        "@platforms//os:macos": [
            "-Wl,-undefined,dynamic_lookup",
            "-Wl,-rpath,@loader_path/../../lib",
        ],
    }),
    local_defines = ["PLUGIN_UCX_CUDA"],
    tags = [
        ALLOW_UNUSED_TAG,
        "no-clang-tidy",  # Copied code doesn't conform to our style
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DeviceContextImpl",
        ":NIXLLibOnly",
        ":NVPTX",
        ":Support",
        "@ucx_prebuilt//:ucx_cuda",
    ],
)

modular_shared_library(
    name = "plugin_ucx_cuda_verbs",
    srcs = glob([
        "lib/NIXL/plugins/ucx/**",
        "lib/NIXL/utils/ucx/**",
    ]),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    # Like plugin_ucx_cuda above but with additional Infiniband support.
    # We link libibverb.so directly instead of relying on user to dlopen it at
    # runtime. This is due to a weird bug where `ibv_get_device_list` would return
    # invalid contents if we do it the other way, even though it should functionally
    # be the same. Note that we have added libibverbs.so to sysroot so that the
    # CI machine have this dep at build time.
    linkopts = select({
        "@platforms//os:linux": [
            "-l:libibverbs.so.1",
            "-Wl,-z,undefs",
            "-Wl,-rpath,$ORIGIN/../../lib",
        ],
        "@platforms//os:macos": [
            "-Wl,-undefined,dynamic_lookup",
            "-Wl,-rpath,@loader_path/../../lib",
        ],
    }),
    local_defines = ["PLUGIN_UCX_CUDA"],
    tags = [
        ALLOW_UNUSED_TAG,
        "no-clang-tidy",  # Copied code doesn't conform to our style
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DeviceContextImpl",
        ":NIXLLibOnly",
        ":NVPTX",
        ":Support",
        "@ucx_prebuilt//:ucx_cuda_verbs",
    ],
)

modular_shared_library(
    # NOTE: currently the target name is coupled to NIXL's plugin discovery
    # logic, which looks for `libplugin_*.so`.
    name = "plugin_ucx_rocm",
    srcs = glob([
        "lib/NIXL/plugins/ucx/**",
        "lib/NIXL/utils/ucx/**",
    ]),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    linkopts = select({
        # Tolerate undefined symbols at build time:
        # This allows us to ignore missing libamdhip64.so.1 etc.
        # symbols at link time. But now it requires that they are available at
        # runtime when this plugin is loaded. This shared lib does not
        # automatically load them if they are missing. They should be loaded in
        # advance to loading this plugin.
        "@platforms//os:linux": [
            "-Wl,-z,undefs",
        ],
        "@platforms//os:macos": [
            "-Wl,-undefined,dynamic_lookup",
        ],
    }),
    local_defines = ["PLUGIN_UCX_ROCM"],
    tags = [
        ALLOW_UNUSED_TAG,
        "no-clang-tidy",  # Copied code doesn't conform to our style
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DeviceContextImpl",
        ":NIXLLibOnly",
        ":Support",
        "@ucx_prebuilt//:ucx_rocm",
    ],
)

modular_shared_library(
    name = "plugin_ucx_rocm_verbs",
    srcs = glob([
        "lib/NIXL/plugins/ucx/**",
        "lib/NIXL/utils/ucx/**",
    ]),
    hdrs = glob(
        [
            "include/AsyncRT/NIXL/plugins/ucx/**",
            "include/AsyncRT/NIXL/utils/ucx/**",
        ],
    ),
    # Like plugin_ucx_rocm above but with additional Infiniband support.
    # We link libibverb.so directly instead of relying on user to dlopen it at
    # runtime. This is due to a weird bug where `ibv_get_device_list` would return
    # invalid contents if we do it the other way, even though it should functionally
    # be the same. Note that we have added libibverbs.so to sysroot so that the
    # CI machine have this dep at build time.
    linkopts = select({
        "@platforms//os:linux": [
            "-l:libibverbs.so.1",
            "-Wl,-z,undefs",
        ],
        "@platforms//os:macos": [
            "-Wl,-undefined,dynamic_lookup",
        ],
    }),
    local_defines = ["PLUGIN_UCX_ROCM"],
    tags = [
        ALLOW_UNUSED_TAG,
        "no-clang-tidy",  # Copied code doesn't conform to our style
    ],
    target_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":DeviceContext",
        ":NIXLLibOnly",
        ":NVPTX",
        ":Support",
        "@ucx_prebuilt//:ucx_rocm_verbs",
    ],
)

cc_autolink_deps(
    name = "nvptx_alwayslink_deps",
    deps = select({
        "//:linux_x86_64": ["@nvptxcompiler_x86_64//:nvptxcompiler"],
        "//:linux_aarch64": ["@nvptxcompiler_aarch64//:nvptxcompiler"],
        "//conditions:default": [],
    }),
)

modular_shared_library(
    name = "NVPTX",
    srcs = [],
    deps = [":nvptx_alwayslink_deps"],
)
