[project]
name = "modular-design-docs"
version = "0.1.0"
description = "Modular engineering design documents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.6.14",
    "pymdown-extensions>=10.15",
]
