//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file provides support for generating debug information based on a given
// IR, either via parsing or snapshotting.
//
//===----------------------------------------------------------------------===//

#ifndef SUPPORT_DEBUGINFODIALECT_TRANSFORMS_SNAPSHOTDEBUGINFO_H
#define SUPPORT_DEBUGINFODIALECT_TRANSFORMS_SNAPSHOTDEBUGINFO_H

#include "Support/LLVMCompilerForwardDecls.h"
#include "mlir/Pass/Pass.h"

namespace llvm {
class SourceMgr;
} // namespace llvm

namespace mlir {
class ParserConfig;
} // namespace mlir

namespace M::DebugInfo {
//===----------------------------------------------------------------------===//
// Entry Points
//===----------------------------------------------------------------------===//

/// Parse a source file contained within the given source manager, and attach
/// artificial debug information that describes the input IR.
OwningOpRef<ModuleOp>
parseSourceFileWithDebugInfo(llvm::SourceMgr &sourceMgr,
                             const mlir::ParserConfig &config);

/// Generate debug information for the .mlir represented by the given
/// operation. Debug information is generated by snapshotting the IR to the
/// provided file, or a temporary file if `filename` is empty.
LogicalResult snapshotDebugInfo(Operation *op, StringRef filename = "");

//===----------------------------------------------------------------------===//
// ODS-Generated Declarations
//===----------------------------------------------------------------------===//

#define GEN_PASS_DECL_DEBUGINFOSNAPSHOT
#define GEN_PASS_REGISTRATION
#include "Support/DebugInfoDialect/Transforms/Passes.h.inc"

} // namespace M::DebugInfo

#endif // SUPPORT_DEBUGINFODIALECT_TRANSFORMS_SNAPSHOTDEBUGINFO_H
