load("//bazel:api.bzl", "modular_py_library", "modular_py_test", "requirement")

package(default_visibility = [
    "//:__pkg__",
    "//max/tests:__subpackages__",
    "//oss/modular/max/tests:__subpackages__",
])

modular_py_library(
    name = "tiny_config",
    testonly = True,
    srcs = ["_tiny_config.py"],
    imports = ["."],
    deps = [
        "//max/python/max/dtype",
        "//max/python/max/graph",
        "//max/python/max/pipelines/architectures/nemotron_h_modulev3",
        "//max/python/max/pipelines/lib",
        requirement("transformers"),
    ],
)

modular_py_test(
    name = "tests",
    srcs = glob(["test_*.py"]),
    deps = [
        ":tiny_config",
        "//max/python/max:tensor",
        "//max/python/max/driver",
        "//max/python/max/dtype",
        "//max/python/max/graph",
        "//max/python/max/nn",
        "//max/python/max/pipelines/architectures/nemotron_h_modulev3",
        "//max/python/max/pipelines/kv_cache",
        "//max/python/max/pipelines/lib",
        "//max/python/max/pipelines/weights",
        requirement("numpy"),
    ],
)
