//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#ifndef CACHE_TD
#define CACHE_TD

include "Support/CacheDialect/CacheAttrs.td"
include "Support/CacheDialect/CacheDialect.td"
include "Support/CacheDialect/CacheOps.td"

#endif // CACHE_TD
