load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@mojo-lsp-server-node-tests//:defs.bzl", "npm_link_all_packages")
load(":mocha.bzl", "mocha_test")

npm_link_all_packages(name = "node_modules")

mocha_test(
    name = "test",
    srcs = [":compile"],
    data = [
        "//KGEN/tools/mojo-lsp-server",
    ],
    env = {
        "MODULAR_MOJO_MAX_LSP_SERVER_PATH": "$(rootpath //KGEN/tools/mojo-lsp-server:mojo-lsp-server)",
    },
)

ts_project(
    name = "compile",
    srcs = glob(["*.ts"]),
    transpiler = "tsc",
    tsconfig = {
        "compilerOptions": {
            "inlineSourceMap": True,
        },
    },
    deps = [
        ":node_modules/@types/mocha",
        ":node_modules/@types/node",
        ":node_modules/mocha",
        ":node_modules/mocha-junit-reporter",
        ":node_modules/vscode-languageserver",
        ":node_modules/vscode-languageserver-protocol",
    ],
)
