# ===----------------------------------------------------------------------=== #
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

"""Pins Qwen3VL clip preprocessing to the Transformers reference.

A clip is not a sequence of independent images, and the two rules that make it
different are both invisible to the image path:

- the resize depends on the frame count, so the same source resolution lands on
  a different ``(h_bar, w_bar)`` at 16 frames than at 32, and therefore on a
  different token count. The 720x1280 pair below (7040 tokens against 11520)
  is the case a ``(width, height)``-only sizing call cannot express.
- each patch row spans two DISTINCT consecutive frames. The image path fills
  the same 1536-wide row by repeating its single frame; reusing that line for
  video discards all motion and leaves the model answering from frame 0.

The golden table was generated by executing
``transformers.models.qwen3_vl.video_processing_qwen3_vl.smart_resize`` (5.12.1
-- the version ``RadixArk/Qwen3.8-27B-NVFP4`` declares), parameterized by that
checkpoint's own ``video_preprocessor_config.json``, and is pinned here rather
than recomputed so the test fails if our arithmetic drifts from it.
"""

from __future__ import annotations

import io
from collections.abc import Sequence

import av
import numpy as np
import numpy.typing as npt
import pytest
from max.pipelines.architectures.qwen3vl_moe.nn.video_processing import (
    QWEN3VL_DEFAULT_CONTAINER_FPS,
    QWEN3VL_VIDEO_MAX_PIXELS,
    clip_grid,
    clip_timestamps,
    decode_clip,
    patchify_clip,
    preprocess_clip,
    sample_frame_indices,
    video_smart_resize,
)
from PIL import Image

PATCH_SIZE = 16
MERGE_SIZE = 2
TEMPORAL_PATCH_SIZE = 2

# (frames, height, width, h_bar, w_bar, grid_t, grid_h, grid_w, rows, tokens)
REFERENCE_GOLDENS = [
    (16, 64, 64, 64, 64, 8, 4, 4, 128, 32),
    (16, 720, 1280, 704, 1280, 8, 44, 80, 28160, 7040),
    (16, 1080, 1920, 928, 1664, 8, 58, 104, 48256, 12064),
    (8, 480, 640, 480, 640, 4, 30, 40, 4800, 1200),
    (4, 224, 224, 224, 224, 2, 14, 14, 392, 98),
    (2, 256, 256, 256, 256, 1, 16, 16, 256, 64),
    (1, 336, 336, 320, 320, 1, 20, 20, 400, 100),
    (32, 720, 1280, 640, 1152, 16, 40, 72, 46080, 11520),
    (64, 360, 640, 352, 640, 32, 22, 40, 28160, 7040),
    (768, 720, 1280, 128, 224, 384, 8, 14, 43008, 10752),
    (5, 100, 400, 96, 384, 3, 6, 24, 432, 108),
    (3, 480, 480, 480, 480, 2, 30, 30, 1800, 450),
]


@pytest.mark.parametrize("golden", REFERENCE_GOLDENS, ids=lambda g: f"{g[0]}f")
def test_clip_layout_matches_reference(
    golden: tuple[int, ...],
) -> None:
    """Resize, grid and token count agree with the executed reference."""
    frames, height, width = golden[:3]
    h_bar, w_bar, grid_t, grid_h, grid_w, rows, tokens = golden[3:]

    assert video_smart_resize(frames, height, width) == (h_bar, w_bar)

    grid, resized = clip_grid(frames, height, width)
    assert grid == (grid_t, grid_h, grid_w)
    assert resized == (h_bar, w_bar)
    assert grid_t * grid_h * grid_w == rows
    assert rows // MERGE_SIZE**2 == tokens


def test_frame_count_changes_the_resize() -> None:
    """The load-bearing pair: one source resolution, two frame counts.

    Sizing a clip per-frame would give both of these the same layout, and the
    router would splice placeholders for the wrong token count.
    """
    sixteen = clip_grid(16, 720, 1280)
    thirty_two = clip_grid(32, 720, 1280)
    assert sixteen[1] != thirty_two[1]
    assert np.prod(sixteen[0]) // 4 == 7040
    assert np.prod(thirty_two[0]) // 4 == 11520


@pytest.mark.parametrize("golden", REFERENCE_GOLDENS, ids=lambda g: f"{g[0]}f")
def test_clip_budget_binds_on_the_whole_clip(golden: tuple[int, ...]) -> None:
    """The ceiling applies to ``t_bar * h_bar * w_bar``, never to one frame."""
    grid_t, h_bar, w_bar = golden[5], golden[3], golden[4]
    assert (
        grid_t * TEMPORAL_PATCH_SIZE * h_bar * w_bar <= QWEN3VL_VIDEO_MAX_PIXELS
    )


def test_a_long_clip_is_driven_below_its_native_frame_size() -> None:
    """What the whole-clip ceiling buys, at the frame count where it bites.

    A per-frame budget would leave a 768-frame 720x1280 clip at its native
    44x80 grid -- 1351680 patch rows against the 43008 the clip ceiling allows,
    31x the embeddings a router spliced placeholders for. The factor scales
    with the frame count, so it is ~1x for a short clip at the same
    resolution: this is not a fixed multiple.
    """
    (grid_t, grid_h, grid_w), _ = clip_grid(768, 720, 1280)
    _, native_h, native_w = clip_grid(2, 720, 1280)[0]
    assert (native_h, native_w) == (44, 80)
    assert grid_t * native_h * native_w == 1351680
    assert grid_t * grid_h * grid_w == 43008


def test_side_below_one_factor_is_rejected() -> None:
    """A side under 32 raises; the image ``smart_resize`` clamps up instead."""
    with pytest.raises(ValueError, match="must be larger than"):
        video_smart_resize(8, 16, 640)


def test_extreme_aspect_ratio_is_rejected() -> None:
    with pytest.raises(ValueError, match="aspect ratio"):
        video_smart_resize(8, 32, 32 * 201)


def test_sampling_uses_round_half_to_even() -> None:
    """Sampling rounds midpoints to even, as ``numpy.round`` does.

    Not a stylistic detail: ``total=11`` at 4 fps puts a sampled index exactly
    on a midpoint, and half-up rounding picks frame 3 where the reference picks
    frame 2. That shifts which frames a clip is answered from.
    """
    indices = sample_frame_indices(11, 4.0)
    np.testing.assert_array_equal(indices, [0, 2, 5, 8, 10])

    raw = np.linspace(0, 10, 5)
    half_up = np.floor(raw + 0.5).astype(np.int64)
    np.testing.assert_array_equal(half_up, [0, 3, 5, 8, 10])


def test_sampling_bounds() -> None:
    """The floor, the ceiling and the clip's own length all bind."""
    # 2 s at 30 fps -> 4 sampled frames, at the floor.
    np.testing.assert_array_equal(
        sample_frame_indices(60, 30.0), [0, 20, 39, 59]
    )
    # Shorter than the floor: capped by the clip itself.
    assert len(sample_frame_indices(3, 30.0)) == 3
    # Far past the ceiling.
    assert len(sample_frame_indices(100_000, 30.0)) == 768
    # No declared frame rate falls back to the reference's assumed 24.
    assert np.array_equal(
        sample_frame_indices(240, None), sample_frame_indices(240, 24.0)
    )
    assert QWEN3VL_DEFAULT_CONTAINER_FPS == 24.0

    with pytest.raises(ValueError, match="no decodable frames"):
        sample_frame_indices(0, 30.0)


def _solid_frame(size: tuple[int, int], value: int) -> Image.Image:
    """A ``(width, height)`` frame of one flat colour."""
    return Image.new("RGB", size, (value, value, value))


def _row_temporal_slots(
    pixel_values: npt.NDArray[np.float32], row: int
) -> tuple[npt.NDArray[np.float32], npt.NDArray[np.float32]]:
    """The two temporal halves of one patch row.

    A row is ``[channel][temporal][py][px]``, so the temporal axis is the
    second of the four.
    """
    reshaped = pixel_values[row].reshape(
        3, TEMPORAL_PATCH_SIZE, PATCH_SIZE, PATCH_SIZE
    )
    return reshaped[:, 0], reshaped[:, 1]


def test_temporal_slots_hold_two_distinct_consecutive_frames() -> None:
    """Row ``t``'s two slots are frames ``2t`` and ``2t + 1``.

    This is the motion-discarding bug in test form: filling both slots from one
    frame (as the image path legitimately does) leaves the two halves
    identical, so the model sees a still.
    """
    frames = [_solid_frame((64, 64), 10 * (i + 1)) for i in range(4)]
    pixel_values, grid = patchify_clip(frames)
    grid_t, grid_h, grid_w = grid
    assert grid_t == 2

    for t in range(grid_t):
        first, second = _row_temporal_slots(pixel_values, t * grid_h * grid_w)
        assert not np.array_equal(first, second), (
            f"temporal patch {t} filled both slots from one frame"
        )
        # Normalization is (x - 0.5 * 255) / (0.5 * 255) with mean = std = 0.5.
        for slot, frame_idx in ((first, 2 * t), (second, 2 * t + 1)):
            expected = (10 * (frame_idx + 1) - 127.5) / 127.5
            np.testing.assert_allclose(slot, expected, atol=1e-6)


def test_repeated_frame_makes_the_slots_identical() -> None:
    """The inverted control for the test above.

    Feeding the same frame twice MUST collapse the two slots. If it does not,
    the previous test is passing for some reason other than temporal
    provenance.
    """
    frame = _solid_frame((64, 64), 90)
    pixel_values, _ = patchify_clip([frame, frame])
    first, second = _row_temporal_slots(pixel_values, 0)
    np.testing.assert_array_equal(first, second)


def test_odd_frame_count_pads_with_the_last_frame() -> None:
    """An odd count fills the final temporal patch by repeating the last frame."""
    frames = [_solid_frame((64, 64), 10 * (i + 1)) for i in range(3)]
    pixel_values, grid = patchify_clip(frames)
    grid_t, grid_h, grid_w = grid
    assert grid_t == 2

    first, second = _row_temporal_slots(pixel_values, grid_h * grid_w)
    np.testing.assert_array_equal(first, second)
    np.testing.assert_allclose(first, (30 - 127.5) / 127.5, atol=1e-6)


def test_patch_row_shape_and_dtype() -> None:
    """Rows are ``grid_t`` outermost and 1536 wide."""
    frames = [_solid_frame((96, 64), 40) for _ in range(6)]
    pixel_values, grid = patchify_clip(frames)
    assert grid == (3, 4, 6)
    assert pixel_values.shape == (3 * 4 * 6, 3 * TEMPORAL_PATCH_SIZE * 16 * 16)
    assert pixel_values.dtype == np.float32


def test_frames_must_share_one_size() -> None:
    with pytest.raises(ValueError, match="share one size"):
        patchify_clip([_solid_frame((64, 64), 10), _solid_frame((96, 64), 10)])


def test_timestamps_average_each_temporal_patch() -> None:
    """One label per temporal patch, the mean of its two frame timestamps."""
    assert clip_timestamps([0, 12, 24, 36], 12.0) == [0.5, 2.5]
    # An odd count pads by repeating the last index, as the frames do, so the
    # final label is that frame's own timestamp rather than an extrapolation.
    assert clip_timestamps([0, 12, 24], 12.0) == [0.5, 2.0]
    # No declared frame rate falls back to 24.
    assert clip_timestamps([0, 24], None) == [0.5]


def _encode_clip(
    frames: Sequence[Image.Image], fps: int, codec: str = "libx264"
) -> bytes:
    """Encodes frames into an in-memory MP4, for the decode path's tests."""
    buffer = io.BytesIO()
    with av.open(buffer, mode="w", format="mp4") as container:
        stream = container.add_stream(codec, rate=fps)
        assert isinstance(stream, av.video.stream.VideoStream)
        stream.width, stream.height = frames[0].size
        stream.pix_fmt = "yuv420p"
        for frame in frames:
            for packet in stream.encode(
                av.VideoFrame.from_image(frame.convert("RGB"))
            ):
                container.mux(packet)
        for packet in stream.encode():
            container.mux(packet)
    return buffer.getvalue()


def test_decode_clip_samples_at_two_fps() -> None:
    """A real encoded clip decodes to the sampler's chosen frames.

    ``int(total / container_fps * 2)``: 24 frames at 12 fps is 2 s of source,
    so 4 sampled frames -- not 24, and not the frame count a fixed-count
    sampler would take.
    """
    source = [_solid_frame((64, 64), 8 * i) for i in range(24)]
    frames, indices, container_fps = decode_clip(_encode_clip(source, fps=12))

    assert container_fps == pytest.approx(12.0)
    np.testing.assert_array_equal(indices, [0, 8, 15, 23])
    assert len(frames) == 4
    assert frames[0].size == (64, 64)


def test_preprocess_clip_end_to_end() -> None:
    """Bytes in, patch rows + grid + one timestamp per placeholder run out."""
    source = [_solid_frame((64, 96), 4 * i) for i in range(48)]
    pixel_values, grid, timestamps = preprocess_clip(
        _encode_clip(source, fps=12)
    )

    grid_t, grid_h, grid_w = grid
    assert (grid_h, grid_w) == (6, 4)
    assert pixel_values.shape == (
        grid_t * grid_h * grid_w,
        3 * TEMPORAL_PATCH_SIZE * PATCH_SIZE**2,
    )
    # One label per temporal patch, which is one per placeholder run.
    assert len(timestamps) == grid_t
    assert timestamps == sorted(timestamps)

    # Distinct source frames must still land in distinct temporal slots after
    # a real decode; a lossy codec shifts values but cannot equalize them.
    first, second = _row_temporal_slots(pixel_values, 0)
    assert not np.array_equal(first, second)
