load("//bazel:api.bzl", "modular_cc_library")

modular_cc_library(
    name = "Cache",
    srcs = glob(["lib/**/*.cpp"]),
    hdrs = glob(["include/Cache/**/*.h"]),
    deps = [
        "//AsyncRT:CompilerSupport",
        "//AsyncRT:Runtime",
        "//Support:Base",
        "//Support:Base64",
        "//Support:Buffer",
        "//Support:Compiler",
        "//Support:Configuration",
        "//Support:Context",
        "//Support:HTTP",
        "//Support:HashUtils",
        "//Support:Telemetry",
        "//Support:URI",
        "@llvm-project//mlir:BytecodeWriter",
        "@llvm-project//mlir:Pass",
    ],
)
