package(default_visibility = ["//visibility:public"])

cc_library(
    name = "Cache",
    srcs = glob(["lib/**/*.cpp"]),
    hdrs = glob(["include/Cache/**/*.h"]),
    copts = [
        # TODO(35394): This isn't what cmake is doing
        '-DMODULAR_DERIVED_DIR=\\"/tmp/modularderived\\"',
    ],
    strip_include_prefix = "include",
    deps = [
        "//LLCL:CompilerSupport",
        "//LLCL:Runtime",
        "//Support:Base",
        "//Support:Base64",
        "//Support:Buffer",
        "//Support:Compiler",
        "//Support:Configuration",
        "//Support:HMAC",
        "//Support:HTTPHeaders",
        "//Support:Telemetry",
        "//Support:URI",
    ],
)

cc_test(
    name = "CacheTest",
    srcs = glob(["unittests/*.cpp"]),
    deps = [
        ":Cache",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "@com_github_google_googletest//:gtest_main",
        "@llvm-project//mlir:BytecodeWriter",
        "@llvm-project//mlir:FuncDialect",
    ],
)
