##===----------------------------------------------------------------------===##
#
# This file is Modular Inc proprietary.
#
##===----------------------------------------------------------------------===##

add_subdirectory(include/Cache/CacheDialect)
add_subdirectory(include/Cache/CachePasses)
add_subdirectory(lib)
add_subdirectory(tools/cache-opt)
add_subdirectory(test)
add_subdirectory(unittests)
