load("//bazel:api.bzl", "lit_tests")

_DATA = [
    "**/inputs/**/*.mojo",
    "**/debuginfo_module.mojo",
    "**/docs_package/**/*.mojo",
    "**/imported_cached_module.mojo",
    "**/imported_module.mojo",
    "**/test_bad_package/**",
    "**/test_package.foo",
    "**/test_package/**",
    "**/target/**",
    "**/test_dependency/**",
    "**/test_package_user/**/*.mojo",
]

lit_tests(
    name = "mojo-isolated",
    srcs = glob(
        [
            "**/*.mojo",
            "**/*.test",
        ],
        exclude = _DATA,
    ),
    data = ["//KGEN/test/test-packages"] + glob(_DATA),
    generate_litcfg = False,
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/kgen-translate",
        "//KGEN/tools/mojo:mojo-compiler-only",
    ],
)
