# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #
#
# Generate a "*CASID.h" header file from cache-mgr outputs.
#
# ===----------------------------------------------------------------------=== #

import pathlib
import re
import subprocess
import tempfile

import attrs
import click
import jinja2

from modular.utils.typing import List, Optional, Tuple


@attrs.define(kw_only=True)
class HashedInput:
    name: str
    path: pathlib.Path
    hash: str


jinja_env = jinja2.Environment(keep_trailing_newline=True)
header_template = jinja_env.from_string(
    """\
//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
// THIS FILE IS AUTOGENERATED
//===----------------------------------------------------------------------===//

#ifndef {{ header_guard }}
#define {{ header_guard }}

#include "llvm/ADT/StringRef.h"

namespace M::CASID {

{% for hashed_input in hashed_inputs -%}
inline constexpr llvm::StringLiteral {{
  hashed_input.name }} = "{{ hashed_input.hash }}";
{% endfor -%}
{{ "" }}
}  // namespace M::CASID

#endif // {{ header_guard }}
"""
)


@click.command()
@click.option(
    "--output-relative-path",
    required=True,
    help="Relative path to output file for use in header guard.",
)
@click.option(
    "--output-header-file",
    required=True,
    type=click.Path(dir_okay=False, writable=True, path_type=pathlib.Path),
    help="Path to output *CASID.h header to.",
)
@click.option(
    "--cache-mgr",
    required=True,
    type=click.Path(
        exists=True, executable=True, dir_okay=False, path_type=pathlib.Path
    ),
    help="Path to cache-mgr binary.",
)
@click.option(
    "--cas-base-dir",
    required=True,
    type=click.Path(file_okay=False, path_type=pathlib.Path),
    help="CAS base directory, forwarded to cache-mgr.",
)
@click.option(
    "--backend-version",
    required=True,
    help="Backend version, forwarded to cache-mgr.",
)
@click.option(
    "--input-name",
    "input_names",
    multiple=True,
    help=(
        "C++ identifier names for each of the inputs.  "
        "Pass multiple times for multiple inputs."
    ),
)
@click.argument(
    "inputs", nargs=-1, type=click.Path(exists=True, path_type=pathlib.Path)
)
@click.pass_context
def cli(
    ctx: click.Context,
    output_relative_path: str,
    output_header_file: pathlib.Path,
    cache_mgr: pathlib.Path,
    cas_base_dir: pathlib.Path,
    backend_version: str,
    input_names: Tuple[str, ...],
    inputs: Tuple[pathlib.Path, ...],
) -> None:
    """Generate a "*CASID.h" header file from cache-mgr outputs.

    Inputs is the list of files to put into the CAS.  Other options dictate the
    output file, as well as options to pass to cache-mgr.
    """
    if len(input_names) != len(inputs):
        ctx.fail("Must pass the same number of input names as inputs")
    hashed_inputs: List[HashedInput] = []
    for input_name, input_path in zip(input_names, inputs):
        input_hash = (
            subprocess.check_output(
                [
                    f"{cache_mgr}",
                    f"-base-dir={cas_base_dir}",
                    f"-input={input_path}",
                    f"-backend-version={backend_version}",
                ]
            )
            .decode("ascii")
            .strip()
        )
        hashed_inputs.append(
            HashedInput(name=input_name, path=input_path, hash=input_hash)
        )
    header_guard = re.sub("[^A-Za-z0-9]+", "_", output_relative_path).upper()
    output = header_template.render(
        header_guard=header_guard, hashed_inputs=hashed_inputs
    )
    # N.B.: We do not want CMake "copy_on_different" behavior -- it will cause
    # CMake to continue to think the output file is out-of-date w.r.t. its
    # input files.
    output_header_file.write_text(output, "ascii")


if __name__ == "__main__":
    cli()
