"""The row-wise reduction graphs precompiled to MEFs, one name per graph.

Keep this list in sync with the ``SPECS_BY_NAME`` registry in
``_rowwise_reduction_specs.py``, which is the source of truth. Drift is caught
in both directions: a name here that the registry lacks fails the producer
build action, and a name in the registry that is missing here fails the test
with a KeyError on its MEF.
"""

ROWWISE_REDUCTION_SPECS = [
    "argmax_bf16_inner_cpu",
    "argmax_bf16_inner_gpu",
    "argmax_bf16_noninner_cpu",
    "argmax_bf16_noninner_gpu",
    "argmax_f32_inner_gpu",
    "argmax_f64_inner_cpu",
    "argmax_f64_noninner_cpu",
    "argmax_i64_inner_cpu",
    "argmax_i64_noninner_cpu",
    "argmin_f32_inner_gpu",
    "argmin_f64_inner_cpu",
    "argmin_f64_noninner_cpu",
    "argmin_i64_inner_cpu",
    "argmin_i64_noninner_cpu",
    "layer_norm_bf16_inner_cpu",
    "layer_norm_bf16_inner_gpu",
    "layer_norm_f16_inner_cpu",
    "layer_norm_f16_inner_gpu",
    "layer_norm_f32_inner_cpu",
    "layer_norm_f32_inner_gpu",
    "reduce_max_bf16_inner_cpu",
    "reduce_max_bf16_inner_gpu",
    "reduce_max_bf16_noninner_cpu",
    "reduce_max_bf16_noninner_gpu",
    "reduce_max_bool_inner_gpu",
    "reduce_max_f32_inner_gpu",
    "reduce_max_f64_inner_cpu",
    "reduce_max_f64_noninner_cpu",
    "reduce_max_i64_inner_cpu",
    "reduce_max_i64_noninner_cpu",
    "reduce_mean_f64_inner_cpu",
    "reduce_mean_f64_noninner_cpu",
    "reduce_min_and_max_bf16_inner_cpu",
    "reduce_min_and_max_bf16_inner_gpu",
    "reduce_min_and_max_bf16_noninner_cpu",
    "reduce_min_and_max_bf16_noninner_gpu",
    "reduce_min_and_max_f64_inner_cpu",
    "reduce_min_and_max_f64_noninner_cpu",
    "reduce_min_and_max_i64_inner_cpu",
    "reduce_min_and_max_i64_noninner_cpu",
    "reduce_min_bool_inner_gpu",
    "reduce_min_f64_inner_cpu",
    "reduce_min_f64_noninner_cpu",
    "reduce_min_i64_inner_cpu",
    "reduce_min_i64_noninner_cpu",
    "reduce_product_bf16_inner_cpu",
    "reduce_product_bf16_inner_gpu",
    "reduce_product_bf16_noninner_cpu",
    "reduce_product_bf16_noninner_gpu",
    "reduce_product_f16_inner_cpu",
    "reduce_product_f16_inner_gpu",
    "reduce_product_f32_inner_cpu",
    "reduce_product_f32_inner_gpu",
    "reduce_product_f64_inner_cpu",
    "reduce_product_f64_noninner_cpu",
    "reduce_sum_bf16_inner_cpu",
    "reduce_sum_bf16_inner_gpu",
    "reduce_sum_bf16_noninner_cpu",
    "reduce_sum_bf16_noninner_gpu",
    "reduce_sum_f16_inner_cpu",
    "reduce_sum_f16_inner_gpu",
    "reduce_sum_f32_inner_cpu",
    "reduce_sum_f32_inner_gpu",
    "reduce_sum_f32_noninner_cpu",
    "reduce_sum_f32_noninner_gpu",
    "reduce_sum_f64_inner_cpu",
    "reduce_sum_f64_noninner_cpu",
    "reduce_sum_i64_inner_cpu",
    "reduce_sum_i64_noninner_cpu",
    "rms_norm_bf16_inner_cpu",
    "rms_norm_bf16_inner_gpu",
    "rms_norm_f16_inner_cpu",
    "rms_norm_f16_inner_gpu",
    "rms_norm_f32_inner_cpu",
    "rms_norm_f32_inner_gpu",
    "row_mean_of_squares_bf16_inner_cpu",
    "row_mean_of_squares_bf16_inner_gpu",
    "row_mean_of_squares_f16_inner_cpu",
    "row_mean_of_squares_f16_inner_gpu",
    "row_mean_of_squares_f32_inner_cpu",
    "row_mean_of_squares_f32_inner_gpu",
    "softmax_bf16_inner_cpu",
    "softmax_bf16_inner_gpu",
    "softmax_f16_inner_cpu",
    "softmax_f16_inner_gpu",
    "softmax_f32_inner_cpu",
    "softmax_f32_inner_gpu",
]
