load("//bazel:api.bzl", "modular_cc_test")

modular_cc_test(
    name = "unittests",
    srcs = glob(["*.cpp"]),
    deps = [
        "//AsyncRT:RuntimeGlobals",
        "//Cache",
        "//Support:Globals",
        "@llvm-project//mlir:BytecodeWriter",
        "@llvm-project//mlir:FuncDialect",
    ],
)
