load("//bazel:api.bzl", "modular_cc_test")

# gazelle:default_visibility //visibility:private

package(
    default_visibility = ["//visibility:private"],
    features = [
        "layering_check",
        "parse_headers",
    ],
)

modular_cc_test(
    name = "AllocatorTest",
    timeout = "short",
    srcs = ["AllocatorTest.cpp"],
    deps = [
        "//MLRT:AsyncRT/Runtime",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "AsyncValueTest",
    size = "small",
    srcs = ["AsyncValueTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//MLRT:AsyncRT/Runtime",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//MLRT:AsyncRT/Support",
        "//Support:Globals",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "DebuggingAllocatorsTest",
    size = "small",
    srcs = ["DebuggingAllocatorsTest.cpp"],
    deps = [
        "//MLRT:AsyncRT/Runtime",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "RuntimeTest",
    size = "small",
    srcs = ["RuntimeTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//MLRT:AsyncRT/Runtime",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "WorkQueueTest",
    size = "small",
    srcs = ["WorkQueueTest.cpp"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//MLRT:AsyncRT/Runtime",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//MLRT:Driver/DeviceContextImpl",
    ],
)

modular_cc_test(
    name = "TypeIDTest",
    size = "small",
    srcs = ["TypeIDTest.cpp"],
    deps = [
        "//MLRT:AsyncRT/Support",
        "//Support:Base",
        "//Support:Globals",
        "//Support:TypeID",
    ],
)

modular_cc_test(
    name = "TimerHeapTest",
    size = "small",
    srcs = ["TimerHeapTest.cpp"],
    deps = [
        "//MLRT:AsyncRT/Runtime",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//MLRT:AsyncRT/Support",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "cppzmqTest",
    size = "small",
    srcs = ["cppzmq.cpp"],
    # Requires two machines to run
    tags = ["manual"],
    deps = [
        "//MLRT:AsyncRT/cppzmq",
    ],
)
