load("//bazel:api.bzl", "kgen_kernel", "modular_cc_test")

kgen_kernel(
    name = "test_kernels",
    testonly = True,
    src = "test_kernels.mlir",
)

modular_cc_test(
    name = "unittests",
    srcs = glob(["*.cpp"]),
    deps = [":test_kernels"],
)

modular_cc_test(
    name = "KGENDialectTest",
    srcs = glob(["kgen-dialect/*.cpp"]),
    deps = [
        "//KGEN:KGENDialect",
        "//KGEN:LITDialect",
    ],
)
