load("//bazel:api.bzl", "modular_cc_test")
load("//utils/bazel/build/rules:kgen.bzl", "kgen_kernel")

kgen_kernel(
    name = "test_kernels",
    src = "test_kernels.mlir",
)

modular_cc_test(
    name = "unittests",
    srcs = glob(["*.cpp"]),
    deps = [
        ":test_kernels",
        "@com_github_google_googletest//:gtest_main",
    ],
)

# TODO: Remove this and fix the weird import in Support.h
cc_library(
    name = "include_shim",
    includes = ["."],
    visibility = ["//KGEN/unittests:__subpackages__"],
)
