# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #

from LLDBTestBase import LLDBTestBase


class TestPointer(LLDBTestBase):
    def test_pointer_child(self):
        """Ensures that the child of a pointer type is correctly generated by
        the typesystem and has a valid name.
        There are two ways to access the pointee type: GetChildAtIndex(0) and
        Dereference(). They are equivalent."""

        with self.build_and_launch("pointer.mojo") as ctx:
            var = ctx.frame.FindVariable("int_pointer")
            child = var.GetChildAtIndex(0)
            assert child.GetName() == "*int_pointer"
            assert child.GetValue() == "101"
            assert var.Dereference().GetValue() == "101"

    def test_invalid_pointer(self):
        """Ensures that the a DType.invalid pointer is correctly parsed."""

        with self.build_and_launch("invalid_pointer.mojo") as ctx:
            var = ctx.frame.FindVariable("ptr")
            assert var.GetValue() == "0x0000000000000000"
            assert var.GetTypeName() == "!kgen.pointer<scalar<invalid>>"
