load("//bazel:api.bzl", "modular_cc_binary")

package(default_visibility = ["//KGEN:consumers"])

modular_cc_binary(
    name = "mojo-repl-entry-point",
    srcs = glob(["*.cpp"]),
    # We need to prevent inline function expansion to guarantee our entry
    # point function is correctly invoked.
    copts = [
        "-O0",
        "-g0",
    ],
    linkopts = select({
        "@platforms//os:linux": [
            # Make sure this never gets stripped because it is used as a lldb breakpoint
            "-Wl,--export-dynamic-symbol=mojo_repl_main",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "//Init",
        "//KGEN:CompilerRT",
        "//KGEN:MojoParser",
        "//KGEN:MojoTooling",
        "//KGEN:ObjectCompiler",
        "//KGEN:Pipeline",
        "//KGEN:ToolCommon",
        "//Support:Base",
        "//Support:Context",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:MlirLspServerLib",
    ],
)
