//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

type FrameId = number;
type RequestId = number;
type SessionId = string;
/**
 * This is a display name generated by LLDB that attempts to be unique.
 */
type VariableDisplayName = string;
/**
 * This name is an LLDB variable path that could collide in case of shadowing.
 */
type VariableEvaluateName = string;

type Variable = {
  name: VariableDisplayName; evaluateName : VariableEvaluateName;
  value : string;
  /**
   * This is an extension to the protocol.
   */
  declaration?: {path : string; line?: number; column?: number;};
};

type DAPScopesRequest = {
  command: "scopes"; seq : RequestId; arguments : {frameId : FrameId};
};

type DAPVariablesRequest = {
  command: "variables"; seq : RequestId;
  arguments : {variablesReference : number};
};

type DAPVariablesResponse = {
  command: "variables"; request_seq : RequestId;
  body : {variables : Variable[]};
};
