load("//bazel:api.bzl", "modular_cc_test")

cc_library(
    name = "Support",
    srcs = ["Support.cpp"],
    hdrs = ["Support.h"],
    deps = [
        "//KGEN:liblldb.wrapper",
        "//KGEN:lldb19.0.0git",
        "//KGEN/tools/mojo-lsp-test-client",
        "//KGEN/unittests:include_shim",
        "@googletest//:gtest",
    ],
)

modular_cc_test(
    name = "unittests",
    srcs = glob(
        ["*.cpp"],
        exclude = ["Support.cpp"],
    ),
    data = glob([
        "inputs/*.mojo",
    ]) + [
        "//KGEN:CompilerRT.distributable",
        "//KGEN:CompilerRT.shared.file",
        "//KGEN:MojoLLDB.shared.file",
        "//KGEN:gdb-server",
        "//KGEN/tools/mojo:mojo.opt",
        "//Kernels/mojo/stdlib",
        "//utils:lit-lldb-init.in",
        "@llvm-project//compiler-rt:orc_rt",
    ],
    env = {
        "LLDB_DEBUGSERVER_PATH": "$(location //KGEN:gdb-server)",
        "MODULAR_MOJO_COMPILERRT_PATH": "$(location //KGEN:CompilerRT.shared.file)",
        "MODULAR_MOJO_COMPILERRT_STATIC_PATH": "$(location //KGEN:CompilerRT.distributable)",
        "MODULAR_MOJO_DRIVER_PATH": "$(location //KGEN/tools/mojo:mojo.opt)",
        "MODULAR_MOJO_IMPORT_PATH": "Kernels/mojo/stdlib",
        "MODULAR_MOJO_LLDB_PLUGIN_PATH": "$(location //KGEN:MojoLLDB.shared.file)",
        "MODULAR_MOJO_ORCRT_PATH": "$(location @llvm-project//compiler-rt:orc_rt)",
        "MODULAR_PATH": ".",
    },
    # TODO: Disable only ODR checks when https://github.com/bazelbuild/bazel/pull/22420 is in
    # __jit_debug_descriptor exists in liblldb and libMojoLLDB
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":Support",
        "//Support:Globals",
    ],
)
