//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include "Support.h"
#include "gtest/gtest.h"

using namespace M;
using namespace lldb;
using namespace ::testing::internal;

TEST(PrimitiveTypesTest, testBool) {
  // There's no SB API for getting the bit size of a type, but the byte size
  // should be 1.

  StopContext ctx = buildAndLaunch("bool.mojo");
  SBValue trueVar = ctx.frame.FindVariable("true");
  EXPECT_STREQ(trueVar.GetTypeName(), "i1");
  EXPECT_EQ((int)trueVar.GetByteSize(), 1);
  EXPECT_EQ((int)trueVar.GetValueAsUnsigned(2), 1);
  EXPECT_STREQ(trueVar.GetSummary(), "True");

  SBValue falseVar = ctx.frame.FindVariable("false");
  EXPECT_STREQ(falseVar.GetTypeName(), "i1");
  EXPECT_EQ((int)falseVar.GetByteSize(), 1);
  EXPECT_EQ((int)falseVar.GetValueAsUnsigned(2), 0);
  EXPECT_STREQ(falseVar.GetSummary(), "False");

  SBValue otherVar = ctx.frame.FindVariable("other");
  EXPECT_STREQ(otherVar.GetTypeName(), "i1");
  EXPECT_EQ((int)otherVar.GetByteSize(), 1);
  EXPECT_EQ((int)otherVar.GetValueAsUnsigned(2), 1);
  EXPECT_STREQ(otherVar.GetSummary(), "True");
}

TEST(PrimitiveTypesTest, testInvalidScalar) {
  /// Ensures that `scalar<invalid>` is correctly considered as having 0
  /// bytes. It also expects to have an inner data type of `None`.
  /// A very common case where this is found is `Dict`, so we start with a
  /// `Dict` variable and navigate its members until reaching the invalid value.

  StopContext ctx = buildAndLaunch("invalid.mojo");
  SBValue a = ctx.frame.FindVariable("a");
  SBValue x = a.GetChildMemberWithName("x");
  EXPECT_STREQ(x.GetTypeName(), "!kgen.pointer<scalar<invalid>>");
  SBValue invalid = x.GetChildAtIndex(0);
  EXPECT_STREQ(invalid.GetTypeName(), "!kgen.none");
  EXPECT_EQ((int)invalid.GetByteSize(), 0);
}

TEST(PrimitiveTypesTest, testPointerChild) {
  /// Ensures that the child of a pointer type is correctly generated by
  /// the typesystem and has a valid name.
  /// There are two ways to access the pointee type: GetChildAtIndex(0) and
  /// Dereference(). They are equivalent.

  StopContext ctx = buildAndLaunch("pointer.mojo");
  SBValue var = ctx.frame.FindVariable("int_pointer");
  SBValue child = var.GetChildAtIndex(0);
  EXPECT_STREQ(child.GetName(), "*int_pointer");
  EXPECT_STREQ(child.GetValue(), "101");
  EXPECT_STREQ(var.Dereference().GetValue(), "101");
}

TEST(PrimitiveTypesTest, testInvalidPointer) {
  /// Ensures that the a DType.invalid pointer is correctly parsed.

  StopContext ctx = buildAndLaunch("invalid_pointer.mojo");
  SBValue var = ctx.frame.FindVariable("ptr");
  EXPECT_STREQ(var.GetTypeName(), "!kgen.pointer<scalar<invalid>>");
}

static void checkIntPair(SBValue &strct, int fst, int snd) {
  EXPECT_STREQ(strct.GetDisplayTypeName(), "MyPair");
  ASSERT_EQ((int)strct.GetNumChildren(), 2);
  SBValue firstField = strct.GetChildAtIndex(0);
  EXPECT_EQ((int)firstField.GetValueAsSigned(fst - 1), fst);
  SBValue secondField = strct.GetChildAtIndex(1);
  EXPECT_EQ((int)secondField.GetValueAsSigned(snd - 1), snd);
}

TEST(PrimitiveTypesTest, testStructAccess) {
  /// Ensures that the a DType.invalid pointer is correctly parsed.

  StopContext ctx = buildAndLaunch("struct_access.mojo");
  SBValue p = ctx.frame.FindVariable("p");
  checkIntPair(p, 1, 2);

  ctx.resume();
  p = ctx.frame.FindVariable("p");
  checkIntPair(p, 3, 4);

  ctx.resume();
  SBValue pp = ctx.frame.FindVariable("pp");
  EXPECT_STREQ(pp.GetDisplayTypeName(), "MyPairPair");
  ASSERT_EQ((int)pp.GetNumChildren(), 2);
  SBValue ppFirst = pp.GetChildAtIndex(0);
  checkIntPair(ppFirst, 5, 6);
  SBValue ppSecond = pp.GetChildAtIndex(1);
  checkIntPair(ppSecond, 7, 8);
}

TEST(PrimitiveTypesTest, testStructFieldOffset) {
  /// Make sure struct field offset calculation is correct by accessing struct
  /// members.

  StopContext ctx = buildAndLaunch("struct_field_offset.mojo");
  SBValue strct = ctx.frame.FindVariable("p");
  ASSERT_EQ((int)strct.GetNumChildren(), 2);
  SBValue first = strct.GetChildAtIndex(0);
  EXPECT_EQ((int)first.GetChildAtIndex(0).GetValueAsSigned(-1), 42);
  SBValue second = strct.GetChildAtIndex(1);
  EXPECT_EQ(second.GetChildAtIndex(0).GetValueAsSigned(-1), 3735928559);
}

TEST(PrimitiveTypesTest, testRecursiveStruct) {
  /// Make sure pointer to self type can be seen and doesn't crash.

  StopContext ctx = buildAndLaunch("recursive-struct.mojo");

  SBValue strct = ctx.frame.FindVariable("f2");
  ASSERT_EQ((int)strct.GetNumChildren(), 2);
  SBValue second = strct.GetChildAtIndex(1);
  EXPECT_STREQ(second.GetTypeName(), "!kgen.pointer<none>");

  SBValue strct2 = ctx.frame.FindVariable("b2");
  ASSERT_EQ((int)strct2.GetNumChildren(), 2);
  SBValue second2 = strct2.GetChildAtIndex(1);
  EXPECT_STREQ(second2.GetTypeName(), "!kgen.pointer<none>");
}

TEST(PrimitiveTypesTest, testTupleAndSIMD) {
  // Test that we can parse a StaticTuple and a SIMD with similar entries.
  // In DWARF, they are both array types but SIMD is marked as vector, which
  // means that the layout is different.

  StopContext ctx = buildAndLaunch("static_tuple.mojo");
  CommandResult result = ctx.runCommand("v");

  EXPECT_TRUE(
      StringRef(result.output).contains(R"((array<4, scalar<si16>>) tuple = {
  [0] = ([0] = 1)
  [1] = ([0] = 2)
  [2] = ([0] = 3)
  [3] = ([0] = 4)
}
(simd<4, si16>) simd = ([0] = 1, [1] = 2, [2] = 3, [3] = 4))"));
}

TEST(PrimitiveTypesTest, testBuiltinTypes) {
  StopContext ctx = buildAndLaunch("builtin-types.mojo");
  EXPECT_EQ(ctx.runCommand("v a_var_index").output,
            "(index) a_var_index = 48\n");
  EXPECT_EQ(ctx.runCommand("v a_register_passable_struct").output,
            R"((ARegisterPassableStruct) a_register_passable_struct = {
  int = -101
  f32 = ([0] = 24.125)
  another_int = 101
  float16 = ([0] = 25.125)
  uint8 = ([0] = 123)
  simd = ([0] = -0.125, [1] = -1.5, [2] = -1, [3] = 5.7266)
  none = None
  uint16 = ([0] = 123)
  int32 = ([0] = 485)
}
)");
  EXPECT_EQ(ctx.runCommand("v a_struct").output,
            R"((AStruct) a_struct = {
  int = ([0] = 12)
  tuple = {
    storage = {
      [0] = 1
      [1] = ([0] = 87)
      [2] = ([0] = 123.125)
    }
  }
}
)");
  EXPECT_EQ(
      ctx.runCommand("v p_struct_int").output,
      R"((ParamStruct[_"stdlib::builtin::int::Int"]) p_struct_int = (t = 8)
)");
  EXPECT_TRUE(RE::PartialMatch(ctx.runCommand("v p_struct_stringref").output,
                               "length = 5"));
  EXPECT_EQ(ctx.runCommand("v an_int").output, "(index) an_int = 123\n");
  EXPECT_EQ(ctx.runCommand("v a_literal_float").output,
            "(scalar<f64>) a_literal_float = ([0] = 3.125)\n");
  EXPECT_EQ(ctx.runCommand("v a_float").output,
            "(scalar<f32>) a_float = ([0] = 3.125)\n");
  EXPECT_EQ(ctx.runCommand("v another_float").output,
            "(scalar<f32>) another_float = ([0] = 4.125)\n");
  EXPECT_STREQ(ctx.frame.FindVariable("^ uncommon name").GetValue(), "1123123");
  EXPECT_EQ(ctx.runCommand("v a_string_literal").output,
            "(string) a_string_literal = \"fofofo\"\n");
  // FIXME(37682): Reenable list printing
  // (*index, scalar<f64>, index) a_list = {
  //   [0] = 1
  //   [1] = ([0] = 2.125)
  //   [2] = 3
  // }
  EXPECT_EQ(ctx.runCommand("v a_simd").output,
            "(simd<4, f16>) a_simd = ([0] = 1.125, [1] = 2.5, [2] = 0, [3] = "
            "-3.7246)\n");
  EXPECT_EQ(ctx.runCommand("v b_simd").output,
            R"((simd<32, si64>) b_simd = {
  [0] = 1
  [1] = 2
  [2] = 3
  [3] = 4
  [4] = 5
  [5] = 6
  [6] = 7
  [7] = 8
  [8] = 9
  [9] = 10
  [10] = 11
  [11] = 12
  [12] = 13
  [13] = 14
  [14] = 15
  [15] = 16
  [16] = -1
  [17] = -2
  [18] = -3
  [19] = -4
  [20] = -5
  [21] = -6
  [22] = -7
  [23] = -8
  [24] = -9
  [25] = -10
  [26] = -11
  [27] = -12
  [28] = -13
  [29] = -14
  [30] = -15
  [31] = -16
}
)");
  EXPECT_EQ(ctx.runCommand("v c_simd").output,
            "(simd<2, index>) c_simd = ([0] = 5, [1] = 6)\n");
  EXPECT_EQ(
      ctx.runCommand("v a_float_or_bool_or_simd").output,
      R"((variant<scalar<f64>, i1, simd<2, index>>) a_float_or_bool_or_simd = {
  variant[2] = ([0] = 5, [1] = 6)
}
)");
  EXPECT_EQ(ctx.runCommand("v none").output, "(None) none = None\n");
}
