load("//bazel:api.bzl", "modular_cc_library", "modular_cc_test")

modular_cc_library(
    name = "Support",
    testonly = True,
    srcs = glob(["Support.*"]),
    deps = [
        "//KGEN/tools/mojo-lsp-test-client",
        "//KGEN/unittests:include_shim",
        "@llvm-project//third-party/unittest:gtest",
    ],
)

modular_cc_test(
    name = "unittests",
    srcs = glob(
        ["*.cpp"],
        exclude = ["Support.cpp"],
    ),
    data = glob(["inputs/*.mojo"]) + [
        "//KGEN/tools/mojo-lsp-server",
        "//open-source/mojo/stdlib/stdlib:stdlib_srcs",
        "@crashpad//:modular-crashpad-handler",
    ],
    env = {
        "MODULAR_MOJO_MAX_IMPORT_PATH": "open-source/mojo/stdlib",
        "MODULAR_PATH": ".",
    },
    tags = [
        "no-sandbox",  # The LSP server currently has issues with symlinks and non-canonical paths
    ],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":Support",
        "//Support:Globals",
    ],
)
