load("//bazel:api.bzl", "modular_cc_library")
load(":lsp-tests.bzl", "lsp_test")

modular_cc_library(
    name = "Support",
    testonly = True,
    srcs = glob(["Support.*"]),
    deps = [
        "//KGEN/tools/mojo-lsp-server",
        "//KGEN/tools/mojo-lsp-test-client",
        "@llvm-project//third-party/unittest:gtest",
    ],
)

# Some tests are very slow, because of which we split all the tests among
# different test targets to allow parallel execution.
# You can execute all of them with
#    bt //KGEN/unittests/mojo-lsp-server/...
inputs = [
    "CodeActionTest",
    "CodeBlockTest",
    "CompletionTest",
    "DefinitionTest",
    "DiagnosticsTest",
    "DocumentSymbolTest",
    "FoldingRangeTest",
    "HoverTest",
    "InitFileTest",
    "MOGGAnnotateDiags",
    "NotebookTest",
    "ReferencesTest",
    "RenameTest",
    "SampleTest",
    "SemanticTokensTest",
    "SignatureHelpTest",
]

[
    lsp_test(
        name = X,
        pattern = (X + ".cpp"),
    )
    for X in inputs
]
