// RUN: kgen-opt %s -split-input-file -lower-coroutines-async -allow-unregistered-dialect -mlir-print-debuginfo | FileCheck %s

// CHECK: #[[SUSPEND_LOC:.*]] = loc("foo.mlir":10:5)

module attributes {M.target_info = #M.target<triple="", cpu="", features="", data_layout="", simd_bit_width=128>} {

// CHECK-LABEL: llvm.func @coro_promise
llvm.func @coro_promise() {
  %0 = "make_handle"() : () -> !pop.coroutine<() -> (i32, i64)>
  // CHECK: %2 = llvm.getelementptr inbounds %1[24] : (!llvm.ptr<i8>) -> !llvm.ptr<struct<(i32, i64)>>
  %1 = pop.coroutine.promise %0 : <() -> (i32, i64)>
  // CHECK: "use"(%2)
  "use"(%1) : (!kgen.pointer<struct<i32, i64>>) -> ()
  llvm.return
}

// CHECK-LABEL: llvm.func @coro_resume
llvm.func @coro_resume() {
  %0 = "make_handle"() : () -> !pop.coroutine<() -> (i32, i64)>
  // CHECK: %2 = llvm.bitcast %1
  // CHECK: %3 = llvm.load %2
  // CHECK-NEXT: llvm.call %3(%1)
  pop.coroutine.resume %0 : !pop.coroutine<() -> (i32, i64)>
  llvm.return
}

// CHECK-LABEL: llvm.func @coro_destroy
llvm.func @coro_destroy() {
  %0 = "make_handle"() : () -> !pop.coroutine<() -> (i32, i64)>
  // CHECK: pop.aligned_free {{.*}} : <i8>
  pop.coroutine.destroy %0 : !pop.coroutine<() -> (i32, i64)>
  llvm.return
}

// CHECK-LABEL: llvm.func internal @async_fn_af.suspend
// CHECK-SAME: (%arg0: i64 loc({{.*}}))
// CHECK-NEXT:   %0 = builtin.unrealized_conversion_cast %arg0 : i64 to index
// CHECK-NEXT:   "do_something"(%0)
// CHECK-NEXT:   llvm.return loc(#[[SUSPEND_LOC]])
// CHECK-NEXT: } loc(#[[SUSPEND_LOC]])


// CHECK-LABEL: llvm.func @async_fn_af
// CHECK-SAME: (%arg0: !llvm.ptr<i8> loc({{.*}}))
llvm.func @async_fn(%arg0: i32) -> !llvm.ptr<i8> {
  // CHECK: %[[C32:.*]] = llvm.mlir.constant(40 : i32)
  // CHECK: %[[C1:.*]] = llvm.mlir.constant(8 : i32)
  // CHECK: %[[C0:.*]] = llvm.mlir.constant(0 : i32)
  // CHECK: %[[AFP:.*]] = llvm.mlir.addressof @async_fn_afp
  // CHECK: %[[AFP_CAST:.*]] = llvm.bitcast %[[AFP]]
  // CHECK: %[[TOK:.*]] = llvm.call_intrinsic "llvm.coro.id.async"(%[[C32]], %[[C1]], %[[C0]], %[[AFP_CAST]])
  // CHECK: %[[HDL:.*]] = llvm.intr.coro.begin %[[TOK]]
  %hdl = pop.coroutine.handle : <() -> (i64)>
  // CHECK: %[[BASE_CTXT_HDL:.*]] = llvm.getelementptr inbounds %[[HDL]][-40]
  // CHECK: %[[CTXT_PTR_HDL:.*]] = llvm.bitcast %[[BASE_CTXT_HDL]]
  // CHECK-NEXT: unrealized_conversion_cast %[[CTXT_PTR_HDL]]
  %0 = builtin.unrealized_conversion_cast %hdl : !pop.coroutine<() -> (i64)> to !llvm.ptr<i8>
  // CHECK: %[[BASE_CTXT_ARG:.*]] = llvm.getelementptr inbounds %[[HDL]][-40]
  // CHECK: %[[ARG_PTR:.*]] = llvm.getelementptr inbounds %[[BASE_CTXT_ARG]][0, 3]
  // CHECK: %[[ARG:.*]] = llvm.load %[[ARG_PTR]]
  // CHECK: "use"(%[[ARG]])
  "use"(%arg0) : (i32) -> ()
  %idx1 = index.constant 1
  // CHECK: %[[CAPTURED:.*]] = builtin.unrealized_conversion_cast %idx1
  // CHECK: %[[RESUME_FN:.*]] = llvm.call_intrinsic "llvm.coro.async.resume"
  // CHECK: %[[BASE_CTXT_RESUME:.*]] = llvm.getelementptr inbounds %[[HDL]][-40]
  // CHECK: %[[RESUME_FN_PTR:.*]] = llvm.getelementptr inbounds %[[BASE_CTXT_RESUME]][0, 0]
  // CHECK: llvm.store %[[RESUME_FN]], %[[RESUME_FN_PTR]]
  // CHECK: %[[C0:.*]] = llvm.mlir.constant(0 : i32)
  // CHECK: %[[PROJ_FN:.*]] = llvm.mlir.addressof @__kgen_coro_ctxt_proj_fn
  // CHECK: %[[PROJ_FN_OPAQUE:.*]] = llvm.bitcast %[[PROJ_FN]]
  // CHECK: %[[SUSPEND_FN:.*]] = llvm.mlir.addressof @async_fn_af.suspend
  // CHECK-NEXT: external_call @llvm.coro.suspend.async.sl_p0p0p0s
  // CHECK-SAME: (%[[C0]], %[[RESUME_FN]], %[[PROJ_FN_OPAQUE]], %[[SUSPEND_FN]], %[[CAPTURED]])
  pop.coroutine.await {
  ^bb0:
    "do_something"(%idx1) : (index) -> ()
  } loc(callsite("foo.mlir":10:5 at "bar.mlir":12:7))
  // CHECK: %[[BASE_CTXT:.*]] = llvm.getelementptr inbounds %[[HDL]][-40]
  // CHECK: %[[FALSE:.*]] = llvm.mlir.constant(false)
  // CHECK: %[[END_FN:.*]] = llvm.mlir.addressof @__kgen_coro_end_fn
  // CHECK: llvm.call_intrinsic "llvm.coro.end.async"(%[[HDL]], %[[FALSE]], %[[END_FN]], %[[BASE_CTXT]])
  llvm.return %0 : !llvm.ptr<i8>
}

// CHECK-LABEL: llvm.mlir.global internal constant @async_fn_afp
// CHECK-SAME: !llvm.struct<(i32, i32)> {
// CHECK-NEXT: %[[UNDEF:.*]] = llvm.mlir.undef : !llvm.struct<(i32, i32)>
// CHECK-NEXT: %[[AFP:.*]] = llvm.mlir.addressof @async_fn_afp : !llvm.ptr<struct<(i32, i32)>>
// CHECK-NEXT: %[[AFP_VALUE:.*]] = llvm.getelementptr inbounds %[[AFP]][0, 1] : (!llvm.ptr<struct<(i32, i32)>>) -> !llvm.ptr<i32>
// CHECK-DAG: %[[AF:.*]] = llvm.mlir.addressof @async_fn_af : !llvm.ptr<func<void (ptr<i8>)>>
// CHECK-DAG: %[[AF_INT:.*]] = llvm.ptrtoint %[[AF]] : !llvm.ptr<func<void (ptr<i8>)>> to i64
// CHECK-DAG: %[[AFP_INT:.*]] = llvm.ptrtoint %[[AFP_VALUE]] : !llvm.ptr<i32> to i64
// CHECK-NEXT: %[[OFFSET_i32:.*]] = llvm.sub %[[AF_INT]], %[[AFP_INT]]  : i64
// CHECK-NEXT: %[[OFFSET:.*]] = llvm.trunc %[[OFFSET_i32]] : i64 to i32
// CHECK-NEXT: %[[V0:.*]] = llvm.insertvalue %[[OFFSET]], %[[UNDEF]][0] : !llvm.struct<(i32, i32)>
// CHECK-NEXT: %[[CTXT_SZ:.*]] = llvm.mlir.constant(40 : i32) : i32
// CHECK-NEXT: %[[RESULT:.*]] = llvm.insertvalue %[[CTXT_SZ]], %[[V0]][1] : !llvm.struct<(i32, i32)>
// CHECK-NEXT: llvm.return %[[RESULT]] : !llvm.struct<(i32, i32)>

// CHECK-LABEL: llvm.func @async_fn(%arg0: i32 loc({{.*}})) -> !llvm.ptr<i8>
// CHECK-NEXT: %[[AFP:.*]] = llvm.mlir.addressof @async_fn_afp
// CHECK-NEXT: %[[AFP_i8ptr:.*]] = llvm.bitcast %[[AFP]]
// CHECK-NEXT: %[[AFP_PREPARE:.*]] = llvm.call_intrinsic "llvm.coro.prepare.async"(%[[AFP_i8ptr]])
// CHECK-NEXT: %[[AFP_CASTED:.*]] = llvm.bitcast %[[AFP_PREPARE]]
// CHECK-NEXT: %[[CTXT_SZ_PTR:.*]] = llvm.getelementptr inbounds %[[AFP_CASTED]][0, 1]
// CHECK-NEXT: %[[CTXT_SZ_i32:.*]] = llvm.load %[[CTXT_SZ_PTR]]
// CHECK-NEXT: %[[CTXT_ALIGN:.*]] = llvm.mlir.constant(8 : i64) : i64
// CHECK-NEXT: %[[CTXT_ALIGN_INDEX:.*]] = builtin.unrealized_conversion_cast %[[CTXT_ALIGN]] : i64 to index
// CHECK-NEXT: %[[CTXT_SZ:.*]] = llvm.zext %[[CTXT_SZ_i32]] : i32 to i64
// CHECK-NEXT: %[[CTXT_SZ_INDEX:.*]] = builtin.unrealized_conversion_cast %[[CTXT_SZ]] : i64 to index
// CHECK-NEXT: %[[MEM_I8:.*]] = pop.aligned_alloc %[[CTXT_ALIGN_INDEX]], %[[CTXT_SZ_INDEX]] : <i8>
// CHECK-NEXT: %[[MEM:.*]] = builtin.unrealized_conversion_cast %[[MEM_I8]]
// CHECK-NEXT: %[[FRAME:.*]] = llvm.bitcast %[[MEM]]
// CHECK-DAG: %[[AF:.*]] = llvm.mlir.addressof @async_fn_af
// CHECK-DAG: %[[RESUME_FN_PTR:.*]] = llvm.getelementptr inbounds %[[FRAME]][0, 0]
// CHECK-NEXT: llvm.store %[[AF]], %[[RESUME_FN_PTR]]
// CHECK-NEXT: %[[ARG_PTR:.*]] = llvm.getelementptr inbounds %[[FRAME]][0, 3]
// CHECK-NEXT: llvm.store %arg0, %[[ARG_PTR]]
// CHECK-NEXT: %[[RESULT:.*]] = llvm.bitcast %[[FRAME]]
// CHECK-NEXT: llvm.return %[[RESULT]] : !llvm.ptr<i8>

// CHECK-LABEL: llvm.func internal @__kgen_coro_end_fn(%arg0: !llvm.ptr<i8> loc({{.*}}))
// CHECK-NEXT: %[[CLOSURE:.*]] = llvm.getelementptr inbounds %arg0[8] : (!llvm.ptr<i8>) -> !llvm.ptr<struct<(ptr<func<void (ptr<i8>)>>, ptr<i8>)>>
// CHECK-NEXT: %[[FN_PTR:.*]] = llvm.getelementptr inbounds %[[CLOSURE]][0, 0]
// CHECK-NEXT: %[[FN:.*]] = llvm.load %[[FN_PTR]]
// CHECK-NEXT: %[[ARG_PTR:.*]] = llvm.getelementptr inbounds %[[CLOSURE]][0, 1]
// CHECK-NEXT: %[[ARG:.*]] = llvm.load %[[ARG_PTR]]
// CHECK-NEXT: llvm.call %[[FN]](%[[ARG]])
// CHECK-NEXT: llvm.return

// CHECK-LABEL: llvm.func internal @__kgen_coro_ctxt_proj_fn(%arg0: !llvm.ptr<i8> loc({{.*}})) -> !llvm.ptr<i8>
// CHECK-NEXT: llvm.return %arg0 : !llvm.ptr<i8>

}

// -----

!basic = !debuginfo.basic<i64 {sizeInBits = 64, alignInBits = 64, encoding = DW_ATE_unsigned}>
!member = !debuginfo.member<value: !basic>
!struct = !debuginfo.struct<"$builtin::$int::Int"(!member)>
!subroutine = !debuginfo.subroutine<() -> (!struct): DW_CC_normal>
#file = #debuginfo.file<"foo.mlir" in "/">
#compile_unit = #debuginfo.compile_unit<sourceLanguage = DW_LANG_C, file = #file, producer = "Mojo", isOptimized = true, emissionKind = Full>

// CHECK-DAG: #[[SP_AF:.*]] = #debuginfo.subprogram<{{.*}}, name = "foo_af", linkageName = "foo_af", file = #file, line = 41, scopeLine = 41
// CHECK-DAG: #[[LOC0:.*]] = loc("foo.mlir":41:11)
// CHECK-DAG: #[[LOC_AF:.*]] = loc(fused<#[[SP_AF]]>[#[[LOC0]]])
#subprogram = #debuginfo.subprogram<compileUnit = #compile_unit, scope = #file, name = "foo", linkageName = "foo", file = #file, line = 41, scopeLine = 41, subprogramFlags = "Definition|Optimized"> : !subroutine
#loc8 = loc(fused<#subprogram>["foo.mlir":41:11])

module attributes {M.target_info = #M.target<triple="", cpu="", features="", data_layout="", simd_bit_width=128>} {
  llvm.func internal @foo() -> !llvm.ptr<i8> {
    %0 = pop.coroutine.handle : <() -> index> loc(#loc8)
    %1 = builtin.unrealized_conversion_cast %0 : !pop.coroutine<() -> index> to !llvm.ptr<i8> loc(#loc8)

    // CHECK-LABEL: llvm.func internal @foo_af.suspend()
    // CHECK-NEXT:    %0 = llvm.mlir.constant(1 : i64) : i64 loc(#[[LOC1_INL:.*]])
    // CHECK-NEXT:    llvm.return loc(#[[LOC_SUSP1:.*]])
    // CHECK-NEXT:  } loc(#[[LOC_SUSP1]])
    pop.coroutine.await {
      %2 = llvm.mlir.constant(1 : i64) : i64 loc(#loc11)
    } loc(#loc11)

    // CHECK-LABEL: llvm.func internal @foo_af.suspend_0()
    // CHECK-NEXT:    %0 = llvm.mlir.constant(2 : i64) : i64 loc(#[[LOC2_INL:.*]])
    // CHECK-NEXT:    llvm.return loc(#[[LOC_SUSP2:.*]])
    // CHECK-NEXT:  } loc(#[[LOC_SUSP2]])
    pop.coroutine.await {
      %2 = llvm.mlir.constant(2 : i64) : i64 loc(#loc13)
    } loc(#loc13)

    llvm.return %1 : !llvm.ptr<i8> loc(#loc8)
  } loc(#loc8)
}

// CHECK-DAG: ![[SUSP_TYPE:.*]] = !debuginfo.subroutine<() -> (): DW_CC_normal>
// CHECK-DAG: #[[SP1:.*]] = #debuginfo.subprogram<{{.*}}, name = "foo_af.suspend", linkageName = "foo_af.suspend", file = #file, line = 44, scopeLine = 44, subprogramFlags = Definition> : ![[SUSP_TYPE]]
// CHECK-DAG: #[[SP2:.*]] = #debuginfo.subprogram<{{.*}}, name = "foo_af.suspend_0", linkageName = "foo_af.suspend_0", file = #file, line = 42, scopeLine = 42, subprogramFlags = Definition> : ![[SUSP_TYPE]]

// CHECK-DAG: #[[LOC1:.*]] = loc("foo.mlir":44:38)
// CHECK-DAG: #[[LOC2:.*]] = loc("foo.mlir":42:41)
// CHECK-DAG: #[[LOC_SUSP1]] = loc(fused<#[[SP1]]>[#[[LOC1]]])
// CHECK-DAG: #[[LOC_SUSP2]] = loc(fused<#[[SP2]]>[#[[LOC2]]])
// CHECK-DAG: #[[LOC_CALLEE1:.*]] = loc(fused<#[[SP_AF]]>[#[[LOC1]]])
// CHECK-DAG: #[[LOC_CALLEE2:.*]] = loc(fused<#[[SP_AF]]>[#[[LOC2]]])
// CHECK-DAG: #[[LOC1_INL]] = loc(callsite(#[[LOC_CALLEE1]] at #[[LOC_SUSP1]]))
// CHECK-DAG: #[[LOC2_INL]] = loc(callsite(#[[LOC_CALLEE2]] at #[[LOC_SUSP2]]))

#loc10 = loc(fused<#subprogram>["foo.mlir":42:16])
#loc11 = loc(fused<#subprogram>["foo.mlir":44:38])
#loc13 = loc(fused<#subprogram>["foo.mlir":42:41])
