// RUN: kgen-opt %s -elaborate-generators -lower-kgen-to-llvm | FileCheck %s

// COM: This file specifically tests that the interpretation of
// COM: `pop.string.address` matches the address generated by the lowering.

kgen.generator @string_address(%arg0: !kgen.string) -> !pop.pointer<scalar<si8>> {
  %0 = pop.string.address %arg0
  kgen.return %0 : !pop.pointer<scalar<si8>>
}

// CHECK-LABEL: llvm.func @check_string_table
kgen.generator export @check_string_table() -> (!pop.pointer<scalar<si8>>, !kgen.string) {
  kgen.param.declare value: string = <"hello">
  // CHECK: llvm.mlir.addressof @static_string :
  %0 = kgen.param.constant: !pop.pointer<scalar<si8>> = <apply(
    :(!kgen.string) -> !pop.pointer<scalar<si8>> @string_address, value)>
  // CHECK: llvm.mlir.addressof @static_string :
  %1 = kgen.param.constant: string = <value>
  kgen.return %0, %1 : !pop.pointer<scalar<si8>>, !kgen.string
}

// CHECK: llvm.mlir.global internal constant @static_string("hello\00")
// CHECK-NOT: llvm.mlir.global
