//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include "KGEN/MojoParser/EntryPoint.h"
#include "AsyncRT/Runtime/Runtime.h"
#include "KGEN/KGENDialect/KGENOps.h"
#include "KGEN/LITDialect/LITOps.h"
#include "KGEN/MojoParser/ASTDecl.h"
#include "KGEN/MojoParser/SharedState.h"
#include "KGEN/Support/CompilerProfiling.h"
#include "KGEN/ToolCommon/CompilationOptions.h"
#include "Support/Compiler/BytecodeReaderWriter.h"
#include "Support/Filesystem/Paths.h"
#include "Support/Telemetry/Telemetry.h"
#include "mlir/Bytecode/Encoding.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Support/Timing.h"
#include "llvm/Support/SourceMgr.h"

using namespace M;
using namespace KGEN;
using namespace LIT;

//===----------------------------------------------------------------------===//
// Driver Entry Points
//===----------------------------------------------------------------------===//

/// Sort the order of uses of the given value using the given set of operation
/// IDs. This ensures a deterministic order of uses.
static void sortValueUses(Value value,
                          DenseMap<Operation *, unsigned> &operationIDs) {
  if (value.use_empty() || value.hasOneUse())
    return;

  // The current use list order for each of the uses of the value.
  SmallVector<std::pair<unsigned, uint64_t>> currentOrder;

  // Functor to record a new use to the current order.
  auto addUse = [&](unsigned index, OpOperand &operand) {
    uint64_t nextID =
        mlir::bytecode::getUseID(operand, operationIDs.at(operand.getOwner()));
    currentOrder.emplace_back(index, nextID);
    return nextID;
  };

  // Compute the current order of the use-list with respect to the global
  // ordering. Detect if the order is already sorted while doing so.
  uint64_t currentID = addUse(0, *value.use_begin());
  bool isSorted = true;
  for (auto it : llvm::drop_begin(llvm::enumerate(value.getUses()))) {
    uint64_t nextID = addUse(it.index(), it.value());
    isSorted &= std::exchange(currentID, nextID) >= nextID;
  }
  // If we know the list is already sorted, there is nothing left to do.
  if (isSorted)
    return;

  // Sort the order based on the operation user, and build the shuffled order
  // mapping.
  llvm::sort(currentOrder, [](auto elem1, auto elem2) {
    return elem1.second > elem2.second;
  });
  SmallVector<unsigned> shuffledOrder(currentOrder.size());
  for (unsigned i = 0, e = currentOrder.size(); i != e; ++i)
    shuffledOrder[currentOrder[i].first] = i;
  value.shuffleUseList(shuffledOrder);
}

/// Sort the order of uses of values defined within the given top level
/// operation. This enforces a deterministic order to the uses, and ensures that
/// any generated bytecode is stable across compilations (regardless of how the
/// IR was parsed).
static void sortValueUses(Operation *topLevelOp) {
  unsigned operationID = 0;
  DenseMap<Operation *, unsigned> operationIDs;
  topLevelOp->walk([&](Operation *op, mlir::WalkStage stage) {
    // Before visiting any of the regions of the operation, we simply check if
    // we should record this operation's ID (i.e. if it has operands).
    if (stage.isBeforeAllRegions()) {
      if (op->getNumOperands())
        operationIDs.insert({op, operationID++});
      return;
    }

    // After the walk has finished, sort the uses of all values defined within
    // this operation.
    if (stage.isAfterAllRegions()) {
      for (Region &region : op->getRegions()) {
        for (Block &block : region) {
          for (BlockArgument &arg : block.getArguments())
            sortValueUses(arg, operationIDs);
          for (Operation &op : block)
            for (Value result : op.getResults())
              sortValueUses(result, operationIDs);
        }
      }
    }
  });
}

/// Erase all declarations unreachable from the main module. This is primarily
/// useful when there are imported modules that were not lazily loaded from the
/// cache. This function should run after textual modules are saved to the
/// cache, reducing the amount of IR reaching the compiler. In addition, it
/// provides the compiler a canonical form of IR coming out of the parser. This,
/// for instance, ensures the cache key computed on parser output does not
/// depend on whether the parser has cache hits for lazy loading.
static void eraseUnreachableDecls(Operation *declOp, ModuleOp module) {
  CompilerTimeTraceScope traceScope("eraseUnreachableDecls");

  // Start by erasing unresolved imports. This puts the module in a
  // canonical form.
  module.walk<mlir::WalkOrder::PreOrder>([&](Operation *op) {
    if (op == declOp) {
      // Don't purge anything from the main package if we are parsing one.
      if (isa<PackageOp>(op))
        return WalkResult::skip();
      op->walk<mlir::WalkOrder::PreOrder>([](Operation *op) {
        if (isa<UnresolvedImportOp, UnresolvedWildcardImportOp>(op)) {
          op->erase();
          return WalkResult::skip();
        }
        if (isa<StructDeclOp, LIT::FuncOp, LIT::TraitDeclOp>(op))
          return WalkResult::skip();
        return WalkResult::advance();
      });
      return WalkResult::skip();
    }

    // Remove all alias decls outside functions and the main decl.
    if (isa<UnresolvedImportOp, UnresolvedWildcardImportOp, AliasDeclOp>(op)) {
      op->erase();
      return WalkResult::skip();
    }
    // Functions have nothing to check inside them.
    if (isa<LIT::FuncOp>(op))
      return WalkResult::skip();
    return WalkResult::advance();
  });

  // The remaining skippable decls are all symbol operations. Run symbol DCE
  // rooted at the main module.
  mlir::SymbolTableCollection symtab;
  DenseSet<Operation *> liveSymbols;
  std::vector<Operation *> worklist;
  declOp->walk([&](Operation *op) {
    if (isa<mlir::SymbolOpInterface>(op)) {
      liveSymbols.insert(op);
      worklist.push_back(op);
    }
  });

  // This walker will mark all referenced symbols as live.
  mlir::AttrTypeWalker refCollector;
  auto markLive = [&](Operation *op) {
    if (liveSymbols.insert(op).second)
      worklist.push_back(op);
  };
  refCollector.addWalk([&](SymbolRefAttr ref) {
    // Mark all referenced symbols as live. Invalid symbol references will get
    // caught by the verifier.
    SmallVector<Operation *, 4> symbols;
    if (failed(symtab.lookupSymbolIn(module, ref, symbols)))
      return;
    for (Operation *symbol : symbols)
      markLive(symbol);
  });

  // Propagate liveness.
  while (!worklist.empty()) {
    Operation *cur = worklist.back();
    worklist.pop_back();
    // Collect symbol references between this symbol table and any child symbol
    // tables. Nested `lit.func` operations are trickier, however.
    cur->walk<mlir::WalkOrder::PreOrder>([&](Operation *op) {
      if (op != cur) {
        // Mark nested functions as live, which also recurses on them.
        if (auto func = dyn_cast<LIT::FuncOp>(op);
            func && func.getParamDeclAttr())
          markLive(func);
        if (op->hasTrait<OpTrait::SymbolTable>())
          return WalkResult::skip();
      }
      refCollector.walk(op->getAttrDictionary());
      for (Region &region : op->getRegions()) {
        for (Block &block : region)
          for (Type type : block.getArgumentTypes())
            refCollector.walk(type);
      }
      for (Type type : op->getResultTypes())
        refCollector.walk(type);
      return WalkResult::advance();
    });
  }

  // Walk post-order to erase dead symbols.
  module.walk<mlir::WalkOrder::PreOrder>([&](Operation *op) -> WalkResult {
    // Don't purge anything from the main package if we are parsing one.
    if (op == declOp && isa<PackageOp>(declOp))
      return WalkResult::skip();

    // Don't erase custom op implementations. The operation has a symbol for
    // fast access that is not referenced in the IR.
    if (isa<KGEN::CustomOpImplsOp>(op))
      return WalkResult::advance();

    if (isa<mlir::SymbolOpInterface, LIT::FuncOp>(op) &&
        !liveSymbols.contains(op)) {
      op->erase();
      return WalkResult::skip();
    }

    // We never need to erase anything inside functions.
    if (isa<LIT::FuncOp>(op))
      return WalkResult::skip();

    return WalkResult::advance();
  });
}

/// Parse a mojo module or package into the specified MLIR context. Returns the
/// resultant IR, and the decl for the module or package. This abstracts away
/// the shared setup between module and package parsing.
static std::tuple<OwningOpRef<mlir::ModuleOp>, ASTDecl *>
importMojoImpl(AsyncRT::Runtime &runtime, StringRef moduleIdentifier,
               SourceMgr &sourceMgr, SharedState &sharedState,
               mlir::TimingScope &ts,
               SmallVectorImpl<std::string> *includedFiles,
               function_ref<ASTDecl &(ModuleOp)> buildDeclFn) {
  MLIRContext *context = sharedState.getContext();
  auto fileLoc =
      FileLineColLoc::get(context, moduleIdentifier, /*line=*/1, /*column=*/1);
  llvm::StringMap<Telemetry::MetricAttributeValue> attrs = {
      {"filename", fileLoc.getFilename().str()}};
  [[maybe_unused]] auto timeScope =
      runtime.context->get<M::Telemetry::TelemetryContext>()
          ->createUInt64Timer<std::chrono::milliseconds>(
              "mojo.parser.compile.time", M::Telemetry::Level::L2, attrs);

  // This is the result module we are parsing into.
  mlir::OwningOpRef<ModuleOp> module(ModuleOp::create(fileLoc));

  // Build the decl for the main module.
  ASTDecl &moduleDecl = buildDeclFn(*module);

  // Resolve everything within the main input module.
  sharedState.declResolver->resolveAllReferencedFrom(moduleDecl);

  // Finalize the imported bytecode now that we've resolved everything. This
  // will drop bytecode operations that never got referenced.
  if (failed(sharedState.finalizeImportedBytecodeModules()))
    return {nullptr, nullptr};

  // Add in the `custom` op implementations in the IR.
  sharedState.finalizeCustomOpImplementations(*module);

  // We fail either if we have a non-recoverable parse error, or if we emitted
  // an error and then recovered.  In either case, the IR will not be valid and
  // the caller should not verify it.
  if (sharedState.diags.isErrorEmitted())
    return {nullptr, nullptr};

#ifndef MODULAR_PRODUCTION
  // Make sure the parse module has no other structural problems detected by
  // the verifier.
  {
    auto verificationTimer = ts.nest("Verify module");
    if (failed(mlir::verify(*module)))
      return {};
  }
#endif // MODULAR_PRODUCTION

  eraseUnreachableDecls(moduleDecl.getIfOperation(), *module);
  sortValueUses(*module);

  // Set the included files if requested.
  if (includedFiles)
    llvm::append_range(*includedFiles, sharedState.getIncludedFiles());
  return {std::move(module), &moduleDecl};
}

/// Parse the specified Mojo file into the specified MLIR context. Returns the
/// resultant IR, and the decl for the module represented by the input file.
static std::tuple<OwningOpRef<mlir::ModuleOp>, ASTDecl *>
importMojoFileImpl(AsyncRT::Runtime &runtime, SourceMgr &sourceMgr,
                   SharedState &sharedState, mlir::TimingScope &ts,
                   SmallVectorImpl<std::string> *includedFiles = nullptr) {
  auto sourceBuf = sourceMgr.getMemoryBuffer(sourceMgr.getMainFileID());
  StringRef bufName = sourceBuf->getBufferIdentifier();
  DebugInfo::DIBuilder::ScopeGuard fileGuard;

  return importMojoImpl(
      runtime, bufName, sourceMgr, sharedState, ts, includedFiles,
      [&](ModuleOp module) -> ASTDecl & {
        Lexer lexer(sharedState.diags, sourceBuf);
        auto startSMLoc = lexer.getToken().getLoc();

        // Create the top-level outer decl, which will contain all things we
        // parse.
        ASTDecl &topLevelDecl = sharedState.declResolver->addDecl(
            module, startSMLoc, StringAttr(), /*parentDecl=*/nullptr,
            lexer.getCursor(), LexerCursor::getEOF(sourceBuf), -1);
        sharedState.initialize(topLevelDecl);

        // If we are emitting debug info, create a file entry for this file.
        if (sharedState.diBuilder)
          fileGuard = sharedState.diBuilder->pushFile(bufName, "/");

        // Grab a module name for the current input, choosing a dummy name if we
        // don't have one that's valid.
        std::string moduleName =
            std::filesystem::path(bufName.str()).stem().string();
        if (moduleName.empty())
          moduleName = "<input>";

        // Build the input module.
        return sharedState.createModule(moduleName, sourceBuf,
                                        cast<FileLineColLoc>(module->getLoc()));
      });
}

std::pair<OwningOpRef<ModuleOp>, PackageOp>
LIT::importMojoPackage(AsyncRT::Runtime &runtime, StringRef path,
                       StringRef packageName, llvm::SourceMgr &sourceMgr,
                       ParserConfig &config, mlir::TimingScope &ts,
                       SmallVectorImpl<std::string> *includedFiles) {
  // Emit an error if the path doesn't actually correspond with a package.
  if (!Filesystem::isMojoSourcePackagePath(path.str())) {
    sourceMgr.PrintMessage({}, llvm::SourceMgr::DK_Error,
                           "provided path '" + path +
                               "' does not correspond to a package");
    return {};
  }
  SharedState sharedState(sourceMgr, config);
  DebugInfo::DIBuilder::ScopeGuard fileGuard;

  auto [module, packageDecl] = importMojoImpl(
      runtime, path, sourceMgr, sharedState, ts, includedFiles,
      [&](ModuleOp module) -> ASTDecl & {
        // Create the top-level outer decl, which will contain all things we
        // parse.
        ASTDecl &topLevelDecl = sharedState.declResolver->addDecl(
            module, SMLoc(), StringAttr(), /*parentDecl=*/nullptr,
            LexerCursor(), LexerCursor(), /*indentation=*/-1);
        sharedState.initialize(topLevelDecl);

        if (sharedState.diBuilder)
          fileGuard = sharedState.diBuilder->pushFile(path, "/");

        // Build the package.
        return sharedState.createPackage(path, packageName);
      });
  if (!module)
    return {};
  return {std::move(module), cast<PackageOp>(*packageDecl)};
}

/// Load a stripped binary package at the given path, only pulling in the top
/// level package operation. Returns the dependencies of the package, and its
/// post parse module.
static std::pair<LinkDependencyArrayAttr, DenseResourceElementsAttr>
loadStrippedBinaryPackage(AsyncRT::Runtime &runtime,
                          const std::shared_ptr<llvm::SourceMgr> &sourceMgr,
                          MLIRContext *ctx, StringRef path) {
  llvm::ErrorOr<std::unique_ptr<llvm::MemoryBuffer>> packageBuffer =
      llvm::MemoryBuffer::getFile(path);
  if (!packageBuffer)
    return {nullptr, nullptr};
  unsigned bufferId =
      sourceMgr->AddNewSourceBuffer(std::move(*packageBuffer), SMLoc());
  const llvm::MemoryBuffer *memoryBuf = sourceMgr->getMemoryBuffer(bufferId);

  // Parse just the top-level binary package operation and extract out the post
  // parse module.
  mlir::ParserConfig config(ctx, /*verifyAfterParse=*/false);
  mlir::BytecodeReader bytecodeReader(memoryBuf->getMemBufferRef(), config,
                                      /*lazyLoad=*/true, sourceMgr);
  auto finalizeReader = [&] {
    return bytecodeReader.finalize([](Operation *) { return false; });
  };
  mlir::Block block;
  if (failed(bytecodeReader.readTopLevel(&block))) {
    (void)finalizeReader();
    return {nullptr, nullptr};
  }
  LIT::PackageOp packageOp = cast<LIT::PackageOp>(&block.front());
  DenseResourceElementsAttr postParseModuleAttr =
      packageOp.getPostParseModuleAttr();
  LinkDependencyArrayAttr deps = packageOp.getDependenciesAttr();
  if (failed(finalizeReader()))
    return {nullptr, nullptr};
  return {deps, postParseModuleAttr};
}

OwningOpRef<ModuleOp> LIT::importStandaloneMojoBinaryPackage(
    AsyncRT::Runtime &runtime,
    const std::shared_ptr<llvm::SourceMgr> &sourceMgr, MLIRContext *ctx,
    StringRef path) {
  // Emit an error if the path doesn't actually correspond with a package.
  if (!Filesystem::isMojoBinaryPackagePath(path.str())) {
    sourceMgr->PrintMessage(
        {}, llvm::SourceMgr::DK_Error,
        "provided path '" + path +
            "' does not correspond to a binary Mojo package");
    return {};
  }

  auto emitPackageLoadFailure = [&](const Twine &msg = {}) {
    sourceMgr->PrintMessage(
        {}, llvm::SourceMgr::DK_Error,
        "unable to load package '" + path + "'" +
            (!msg.isTriviallyEmpty() ? (": " + msg.str()) : ""));
    return OwningOpRef<ModuleOp>();
  };

  // Read in the post parser module from the package.
  auto [deps, postParseModuleAttr] =
      loadStrippedBinaryPackage(runtime, sourceMgr, ctx, path);
  if (!postParseModuleAttr)
    return emitPackageLoadFailure();
  OwningOpRef<ModuleOp> packageModule =
      readOpFromBytecodeFile<ModuleOp>(postParseModuleAttr);
  if (!packageModule)
    return emitPackageLoadFailure();

  // The post parser module of a package is not self-contained, it references
  // other packages but those packages don't have their own post-parser content
  // available. To resolve this, pull in the dependencies so that we can attach
  // the necessary metadata to our module.
  if (!deps)
    return packageModule;
  KGEN::CompilationOptions options;
  ParserConfig config(ctx, options);
  SharedState sharedState(*sourceMgr, config);
  SymbolTable symbolTable(packageModule.get());
  for (FlatSymbolRefAttr dep : deps) {
    std::optional<std::string> depPath =
        sharedState.resolveModulePath(dep.getValue(), SMLoc());
    if (!depPath || !Filesystem::isMojoBinaryPackagePath(*depPath))
      return emitPackageLoadFailure("unable to locate module '" +
                                    dep.getValue() + "'");

    auto [_, postParseModuleAttr] =
        loadStrippedBinaryPackage(runtime, sourceMgr, ctx, *depPath);
    if (!postParseModuleAttr)
      return emitPackageLoadFailure("unable to load dependency module '" +
                                    dep.getValue() + "'");

    // Update the symbol table with the dependency.
    PackageOp mainDepPackage = symbolTable.lookup<PackageOp>(dep.getValue());
    mainDepPackage.setPostParseModuleAttr(postParseModuleAttr);
  }

  return packageModule;
}

OwningOpRef<mlir::ModuleOp>
LIT::importMojoFile(AsyncRT::Runtime &runtime, llvm::SourceMgr &sourceMgr,
                    ParserConfig &config, mlir::TimingScope &ts,
                    SmallVectorImpl<std::string> *includedFiles) {
  SharedState sharedState(sourceMgr, config);
  auto [module, topLevelDecl] =
      importMojoFileImpl(runtime, sourceMgr, sharedState, ts, includedFiles);
  return std::move(module);
}

OwningOpRef<ModuleOp> LIT::cloneDeclModuleForCompilation(ASTDecl &decl) {
  IRMapping mapping;
  return cloneDeclModuleForCompilation(decl, mapping);
}
OwningOpRef<ModuleOp> LIT::cloneDeclModuleForCompilation(ASTDecl &decl,
                                                         IRMapping &mapping) {
  Operation *declOp = decl.getIfOperation();
  assert(declOp && "expected decl to be an operation");

  // Clone the module containing the decl.
  ModuleOp declModule = declOp->getParentOfType<ModuleOp>();
  OwningOpRef<ModuleOp> newModule = cast<ModuleOp>(declModule->clone(mapping));
  Operation *newDeclOp = mapping.lookup(declOp);

  // Perform the necessary post-parse transformations to prepare the module for
  // compilation.
  eraseUnreachableDecls(newDeclOp, *newModule);
  sortValueUses(*newModule);
  return newModule;
}

//===----------------------------------------------------------------------===//
// ParserListener
//===----------------------------------------------------------------------===//

bool ParserListener::isInterestedInLoc(SMLoc parserLoc) { return true; }
void ParserListener::onAliasDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onArgumentDecl(ASTDecl *decl, StringRef argName,
                                    SMLoc identifierLoc) {}
void ParserListener::onFunctionDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onImport(SMLoc importLoc) {}
void ParserListener::onImport(ResolveInputDeclFn getPackageDecl,
                              SMLoc importLoc) {}
void ParserListener::onMemberLookup(ResolveInputDeclFn getDeclFn, SMLoc loc,
                                    bool searchParentScopes) {}
void ParserListener::onModuleImport(ASTDecl *decl, StringRef spelling,
                                    SMLoc importLoc) {}
void ParserListener::onModuleDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onParameterDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onStructDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onStructFieldDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onTraitDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onVariableDecl(ASTDecl *decl, SMLoc identifierLoc) {}
void ParserListener::onRef(ArrayRef<ASTDecl *> decls, StringRef spelling,
                           llvm::SMRange range) {}
void ParserListener::onCall(ArrayRef<ASTDecl *> decls, llvm::SMLoc rparenLoc,
                            const OperandContainer &operands) {}
void ParserListener::onParameterBinding(ArrayRef<ASTDecl *> decls,
                                        llvm::SMLoc rsquareLoc,
                                        ArrayRef<ExprNode *> parameters) {}
