//===- HLKGENOps.cpp ------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file implements the HLKGEN dialect operations.
//
//===----------------------------------------------------------------------===//

#include "KGEN/HLKGENDialect/HLKGENOps.h"
#include "KGEN/KGENDialect/KGENOps.h"
#include "KGEN/KGENDialect/KGENParameters.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/FunctionImplementation.h"

using namespace M;
using namespace KGEN;

//===----------------------------------------------------------------------===//
// HLGeneratorOp
//===----------------------------------------------------------------------===//

std::pair<ArrayRef<ParamDeclAttr>, ArrayRef<ParamDeclAttr>>
HLGeneratorOp::getParameterInfo() {
  return getDeclParameterInfo(getOperation());
}

ReturnOp HLGeneratorOp::getReturnOp() {
  return cast<ReturnOp>(getBodyBlock()->getTerminator());
}

/// Parses a HLKGEN Generator.
ParseResult HLGeneratorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseGeneratorOrKernel(parser, result,
                                GeneratorOrKernelKind::hlgenerator);
}

// Print the HLGeneratorOp using the shared printing logic.
void HLGeneratorOp::print(OpAsmPrinter &p) { printGeneratorOrKernel(p, *this); }

LogicalResult HLGeneratorOp::verifyRegions() {
  if (failed(getReturnOp().checkArgumentTypes(getResultParamDecls(),
                                              getResultTypes())))
    return failure();

  // See if the parameter definitions and uses within the generator are
  // structured correctly.
  return ParameterDeclsAndUses::calculate(*this);
}

LogicalResult
HLGeneratorOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
  // If the generator is implementing a generator interface, check that they
  // line up correctly.
  FlatSymbolRefAttr interfaceSym = getImplementsAttr();
  if (!interfaceSym)
    return success();

  // Check that the callee attribute was specified.
  GeneratorInterfaceOp interface = dyn_cast_or_null<GeneratorInterfaceOp>(
      symbolTable.lookupNearestSymbolFrom(*this, interfaceSym));
  if (!interface)
    return emitError() << "'" << interfaceSym.getValue()
                       << "' does not reference a generator interface";

  // Verify that the signature of this generator matches the signature of the
  // interface.
  return verifyDeclMatchesInterface("generator", *this, "interface", interface);
}

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "KGEN/HLKGENDialect/HLKGEN.cpp.inc"
