//===- HLKGENOps.cpp ------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file implements the HLKGEN dialect operations.
//
//===----------------------------------------------------------------------===//

#include "KGEN/HLKGENDialect/HLKGENOps.h"
#include "KGEN/KGENDialect/KGENOps.h"
#include "KGEN/KGENDialect/KGENParameters.h"
#include "KGEN/KGENDialect/KGENUtils.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/FunctionImplementation.h"

using namespace M;
using namespace KGEN;

//===----------------------------------------------------------------------===//
// HLGeneratorOp
//===----------------------------------------------------------------------===//

ReturnOp HLGeneratorOp::getReturnOp() {
  return cast<ReturnOp>(getBodyBlock()->getTerminator());
}

/// Parses a HLKGEN Generator.
ParseResult HLGeneratorOp::parse(OpAsmParser &parser, OperationState &result) {
  return parseGeneratorOrFunc(parser, result, GeneratorOrFuncKind::hlgenerator);
}

// Print the HLGeneratorOp using the shared printing logic.
void HLGeneratorOp::print(OpAsmPrinter &p) { printGeneratorOrFunc(p, *this); }

LogicalResult
HLGeneratorOp::verifySymbolUses(SymbolTableCollection &symbolTable) {
  // Check result types match the ReturnOp.
  if (failed(getReturnOp().checkArgumentTypes(getResultParamTypes(),
                                              getResultTypes())) ||
      // See if the parameter definitions and uses within the generator are
      // structured correctly.
      failed(ParameterDeclsAndUses::calculateAndVerify(*this, symbolTable)))
    return failure();

  // If the generator is implementing a generator interface, check that they
  // line up correctly.
  FlatSymbolRefAttr interfaceSym = getImplementsAttr();
  if (!interfaceSym)
    return success();

  // Check that the callee attribute was specified.
  GeneratorInterfaceOp interface = dyn_cast_or_null<GeneratorInterfaceOp>(
      symbolTable.lookupNearestSymbolFrom(*this, interfaceSym));
  if (!interface)
    return emitError() << "'" << interfaceSym.getValue()
                       << "' does not reference a generator interface";

  // Result parameters need to match, but input parameters may be inferred.
  if (getResultParamTypesAttr() != interface.getResultParamTypesAttr())
    return emitError() << "hlkgen.generator result parameter types must match "
                          "interface types";

  return success();
}

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "KGEN/HLKGENDialect/HLKGEN.cpp.inc"
