//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include "KGEN/EmitFuncHeader.h"
#include "KGEN/LowerToObject.h"
#include "Support/FileSystemExtras.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/ToolOutputFile.h"

using namespace M;
using namespace KGEN;

static ErrorOr<std::string>
generateHeaderContent(SymbolTable &symtab, const ExportMap &exportedSymbols,
                      ObjectCompiler &compiler, StringRef filename) {
  std::filesystem::path filePath(filename.str());

  llvm::StringLiteral headerFmtStart = R"literal(//===-{0}-===//
//
// This file is Modular Inc proprietary.
//
//==={0}===//
// THIS FILE IS AUTOGENERATED BY `kgen`, DO NOT EDIT!
//==={0}===//

#ifndef {1}
#define {1}

#ifdef __cplusplus
extern "C" {{
#endif

#if defined(_WIN64) || defined(_WIN32)
#include <BaseTsd.h>
using ssize_t = SSIZE_T;
#else // defined(_WIN64) || defined(_WIN32)
#include <sys/types.h>
#endif // defined(_WIN64) || defined(_WIN32)

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

)literal";

  llvm::StringLiteral headerFmtEnd = R"literal(
#ifdef __cplusplus
} // extern "C"
#endif

#endif // {0}
)literal";

  std::string header;
  llvm::raw_string_ostream headerOs(header);

  std::string headerGuard =
      "__KGEN_" + StringRef(filePath.stem().string()).upper() + "_H";
  headerOs << llvm::formatv(headerFmtStart.data(),
                            llvm::fmt_repeat('-', 80 - 2 * strlen("//===")),
                            headerGuard);

  // Emit the function decls into the header.
  if (failed(compiler.produceFunctionDecls(symtab, exportedSymbols, headerOs)))
    return Error("failed to produce function decls");

  headerOs << llvm::formatv(headerFmtEnd.data(), headerGuard);

  return header;
}

/// This allows us to emit a header file for the given func so that we can
/// `#include` it and get nice autocompletion/etc. in users' IDEs.
LogicalResult M::KGEN::emitHeader(SymbolTable &symtab,
                                  const ExportMap &exportedSymbols,
                                  ObjectCompiler &compiler,
                                  StringRef filename) {
  ErrorOr<std::string> header =
      generateHeaderContent(symtab, exportedSymbols, compiler, filename);
  if (failed(header))
    return mlir::failure();

  if (filename == "-") {
    llvm::outs() << *header;
    llvm::outs().flush();
    return mlir::success();
  }

  std::filesystem::path filePath(filename.str());

  // Safely process creating the header, taking into account that we may have
  // different processes trying to produce this header in parallel.
  if (auto err =
          writeFileUnderLock(filePath, [&](raw_ostream &os) { os << *header; });
      err.isError())
    return mlir::emitError(symtab.getOp()->getLoc(), err.getError());

  return mlir::success();
}
