load("//utils/bazel/build/rules:lit.bzl", "lit_tests")

lit_tests(
    name = "mojo-lsp-server",
    srcs = glob(
        ["**/*.test"],
        exclude = [
            "definition.test",  # TODO: Debug and enable
        ],
    ),
    mojo_deps = [
        "//Kernels/mojo/stdlib",
    ],
    tools = [
        "//KGEN/tools/mojo-lsp-server",
    ],
)
