load("//bazel:api.bzl", "lit_tests")

package(default_visibility = ["//visibility:private"])

lit_tests(
    name = "mojo-lsp-server-misc",
    srcs = glob(
        [
            "**/*.test",
            "**/*.mojo",
        ],
        exclude = ["parse-stdlib/**"],
    ),
    mojo_deps = [
        "@mojo//:std",
    ],
    tools = [
        "//KGEN/tools/mojo-lsp-server",
        "//KGEN/tools/mojo-lsp-simple-client",
    ],
)

# Umbrella target: bt //KGEN/test/mojo-lsp-server runs everything.
test_suite(
    name = "mojo-lsp-server",
    tests = [
        ":mojo-lsp-server-misc",
        "//KGEN/test/mojo-lsp-server/parse-stdlib:mojo-lsp-server-parse-stdlib",
    ],
)
