load("//bazel:api.bzl", "modular_cc_library")
load("//Config:version.bzl", "status_template")

modular_cc_library(
    name = "Config",
    srcs = glob(["lib/**/*.cpp"]) + [
        ":GeneratedVersion",
    ],
    hdrs = glob(["include/**/*.h"]),
    copts = ["-I$(GENDIR)/Config"],
    defines = [
        # FIXME(amscanne): These are non-hermetic. These will automatically
        # propagate to all dependent targets and be defined universally.
        "MODULAR_ASYNCRT_MAX_PROFILING_LEVEL=00000",
        "MODULAR_KERNELS_BUILD_TYPE=\\\"unknown\\\"",
    ],
    visibility = ["//visibility:public"],
)

status_template(
    name = "GeneratedVersion",
    # Note that this still incldues the include/ prefix, which will be stripped
    # above. This can only be used via a dependency on the Config library.
    src = "include/GeneratedVersion.h.tmpl",
    out = "GeneratedVersion.h",
)
