load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "mojo-test-executor",
    srcs = ["main.cpp"],
    deps = [
        "//KGEN:ExecutionEngine",
        "//KGEN:LITDialect",
        "//KGEN:MojoJupyter",
        "//KGEN:MojoLLDB",
        "//KGEN:MojoTesting",
        "//KGEN:ObjectCompiler",
        "//KGEN:liblldb.wrapper",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "//Support:Init",
    ],
)
