//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include <string>

#include "Support/Entitlements/EntitlementToken.h"
#include "llvm/ADT/StringRef.h"
#include "gtest/gtest.h"

using namespace M;

TEST(TestEntitlementToken, emptyString) {
  auto tokenOr = M::unpackToken("");
  EXPECT_TRUE(tokenOr.isError());
}

TEST(TestEntitlementToken, unpack) {
  // DO NOT MODIFY!
  // Throwaway private key in the format used by Phoenix
  std::string keyPEM =
      "-----BEGIN PRIVATE KEY-----\n"
      "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgHdXthFGhYOsIpnkN\n"
      "2y2mxibPXI7pk3SOVlQ2pj/Z6N+hRANCAAR0d7BZfDg//ZdR32gqx03MdupWh0as\n"
      "jZtKnB54Q4JWCY8+Iyd9C38js09XYUCeyv6toXT+ssxk3qzeqXwkdKgA\n"
      "-----END PRIVATE KEY-----\n";
  // Cert in theformat generated by phoenix
  std::string certPEM =
      "-----BEGIN CERTIFICATE-----\n"
      "MIIB7TCCAZOgAwIBAgICB+MwCgYIKoZIzj0EAwIwTjEQMA4GA1UEChMHRm9vQ29y\n"
      "cDEUMBIGA1UECxMLYWR2ZXJ0aXNpbmcxJDAiBgNVBAMMG21zdF9hc2RmYXNkZmFz\n"
      "ZGZhc2RmYXNkZmFkZjAeFw0yNDAzMjcxODUwMjNaFw0zNDAzMjcxODUwMjNaME4x\n"
      "EDAOBgNVBAoTB0Zvb0NvcnAxFDASBgNVBAsTC2FkdmVydGlzaW5nMSQwIgYDVQQD\n"
      "DBttc3RfYXNkZmFzZGZhc2RmYXNkZmFzZGZhZGYwWTATBgcqhkjOPQIBBggqhkjO\n"
      "PQMBBwNCAAR0d7BZfDg//ZdR32gqx03MdupWh0asjZtKnB54Q4JWCY8+Iyd9C38j\n"
      "s09XYUCeyv6toXT+ssxk3qzeqXwkdKgAo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYD\n"
      "VR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wHQYD\n"
      "VR0OBBYEFL/ZgGeSGyiSHXKNdhMRpQGDo27xMAoGCCqGSM49BAMCA0gAMEUCIB9a\n"
      "wo0Y5K+g8f1+yc6piCXbT8FPpTrqijhYZAvhuOkeAiEAtl270EtRQS6vH07A4dEN\n"
      "X7ls0zArX7obxme3NVQRVuI=\n"
      "-----END CERTIFICATE-----\n";
  // Token generated from phoenix using the above key & cert.
  // DO NOT MODIFY.
  // This is needed to ensure backwrds compat with Phoenix.
  std::string phoenixToken =
      "eJyEk1GP4jYUhf/Kilda4QnMACv14dpxHA/"
      "rgEOAJE1VQcI4JODAwOAkVf97NaBuR9tW4yf7WLr3Hp3v/tFJt6+X39N8vdOdr792fn4/"
      "mDLufSHUD7jDCQT0piZacI6HASEQTxUYjkFxgrvCEBXxSRXztkAUDDdBQaWAAYOHBSW5cP3D"
      "+CqtcZPo1KYLgfn9pxbfopVvxeEzWofecXNI62cbdlh5SwxCMOuhzZxxnlr+"
      "IQq9Mj44baJjFn9UyriArWNQ49nQiiKtp/"
      "bCiMJbOwa1P2qCDupEUxum9x5VgFF83SDvmmqoHRvmd/"
      "0cEMsps8Oyydi+Xa8etZhLw1VkL6W0E23jyyXt+y9/T/"
      "XDTLd3zCKzCiDAKj3lZTGdSY6xUrd7omdSYGw8AuCjbIjjF1v1enHm9y11qlFfZG/"
      "HVY7W5yK+TDR+HMjB84pEoy5vsjHpj4pEn9E4jBZk21yfLlUYdM/"
      "nuuyf2u0pNGU2UVBZ1ITt3akrRxheRhSDIFBJ48rITvTSR3uMI+"
      "NAxCcmwlguXDCcEXJmIBcONgILGL1nlVFDcc9IR4B4r/"
      "RPhSnGEXW+"
      "9WLFtnPW7OZuOPGyXPhHyezKGtYCKkbIic3FYHzrjxQIuiAcj9eJNhWKHiddNXp56Dbp03FH"
      "wk0wcmbH4PW0K/Iohmv+Ni23sKNw2VtDRC++nD9dXTSEQUa9RIfD/"
      "Rm18BoOq0192Pa9pfSXb/"
      "yXRN+gpZ79HyB3fvupU26bztePvM98voSAfpnQ6DvvzAVFQWDBcHP3AIp+"
      "9wOGupghs37fBSmVm4WX3GF5ND3zoy69RFuNdah3m1nIh8eyP58u99I6Fr34yevmPnyef6L/"
      "j4DP8v/g/9/GOn/+FQAA//8D5kQD";

  auto tokenOr = M::unpackToken(phoenixToken);
  if (tokenOr.isError()) {
    EXPECT_EQ("", tokenOr.getError());
  }
  EXPECT_FALSE(tokenOr.isError());

  auto token = tokenOr.takeValue();
  EXPECT_EQ(keyPEM, token->key);
  EXPECT_EQ(certPEM, token->certChain.at(0));

  size_t numCerts = 1;
  EXPECT_EQ(numCerts, token->certChain.size());
  EXPECT_EQ(certPEM, token->certChain.at(0));
}

TEST(TestEntitlementToken, roundTrip) {
  //  auto tokenOr = M::unpackToken(llvm::StringRef(token));
  EntitlementToken t1;
  t1.key = "1234";
  t1.certChain.emplace_back("asdf");

  std::string s = M::packToken(t1);
  // base64(zip(json))
  EXPECT_EQ("eJyrVkpOLSqJT85IzMxTsopWSixOSVOK1VHKTq1UslIyNDI2UaoFAODZCyI=", s);

  auto tokenOr = M::unpackToken(s);
  EXPECT_FALSE(tokenOr.isError());
  auto t2 = std::move(tokenOr.get());
  EXPECT_EQ(t2->key, t1.key);

  size_t numCerts = 1;
  EXPECT_EQ(numCerts, t2->certChain.size());
  EXPECT_EQ("asdf", t2->certChain.at(0));

  std::string s2 = M::packToken(*t2);
  EXPECT_EQ(s, s2);
}
