//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include <string>

#include "Support/Entitlements/EntitlementToken.h"
#include "llvm/ADT/StringRef.h"
#include "gtest/gtest.h"

using namespace M;

TEST(TestEntitlementToken, emptyString) {
  auto tokenOr = M::unpackToken("");
  EXPECT_TRUE(tokenOr.isError());
}

TEST(TestEntitlementToken, unpack) {
  // DO NOT MODIFY!
  // Throwaway private key in the format used by Phoenix
  std::string keyPEM =
      "-----BEGIN EC PRIVATE KEY-----\n"
      "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgcNwmHjIxTuUxx6sH\n"
      "k/WJhlvOGN3mo1CSPAa5DEY0jVyhRANCAAT9jDV3tDw1m457oTTI3tWIncwxTC6G\n"
      "bZ8+hYAVyvCVNK/o3XZqvWgODztCVW2O+zJP9kVhgGx0P793QA3JBU+M\n"
      "-----END EC PRIVATE KEY-----\n";
  // Cert in theformat generated by phoenix
  std::string certPEM =
      "-----BEGIN CERTIFICATE-----\n"
      "MIIB7jCCAZOgAwIBAgICB+MwCgYIKoZIzj0EAwIwTjEQMA4GA1UEChMHRm9vQ29y\n"
      "cDEUMBIGA1UECxMLYWR2ZXJ0aXNpbmcxJDAiBgNVBAMMG21zdF9hc2RmYXNkZmFz\n"
      "ZGZhc2RmYXNkZmFkZjAeFw0yNDAzMjUyMDA1NTRaFw0zNDAzMjUyMDA1NTRaME4x\n"
      "EDAOBgNVBAoTB0Zvb0NvcnAxFDASBgNVBAsTC2FkdmVydGlzaW5nMSQwIgYDVQQD\n"
      "DBttc3RfYXNkZmFzZGZhc2RmYXNkZmFzZGZhZGYwWTATBgcqhkjOPQIBBggqhkjO\n"
      "PQMBBwNCAAT9jDV3tDw1m457oTTI3tWIncwxTC6GbZ8+hYAVyvCVNK/o3XZqvWgO\n"
      "DztCVW2O+zJP9kVhgGx0P793QA3JBU+Mo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYD\n"
      "VR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wHQYD\n"
      "VR0OBBYEFPCKfqUM0zcou1dnqxI9mAGQMKU6MAoGCCqGSM49BAMCA0kAMEYCIQDz\n"
      "GIW+B6g/z3Sn/tqXTSercH+3HO2nViOYCor2Dgdz3QIhAJtKAhURSKkEg7b/dMIf\n"
      "e1zc2are+hAbkVimlJgbaM3Z\n"
      "-----END CERTIFICATE-----\n";
  // Token generated from phoenix using the above key & cert.
  // DO NOT MODIFY.
  // This is needed to ensure backwrds compat with Phoenix.
  std::string phoenixToken =
      ("eJyEk1+PozYUxb/KKK9pFQLzL/t2/"
       "QfjpIaYAAmUqkpIxgwMppnJxkDV715Nom5Hq12Nn+xj6d5z7N/9e1QcXk9/FuX2WY++/"
       "D769X0hyrh/"
       "g2kYcZdjiOhFzbXgHD1UGEMWKDAcgeIYjYXBKuWLNuNDZVEw3EQVlQJuGUxjikvhhc3sLO1"
       "Zn+uC0Fggfr3pxG/pOrSzzdzabvy/"
       "dk3RzQk8I+"
       "UnCIRg9nTYu7OysMMm3fh11rhDrjOWfVTqrIKDa6zeJzCIKu4FgakfhVvXWMP3mqC3Xa4pg"
       "eDao42QlZ13ln8uNHQugdVVf4uw7db7Jun37GXYru+0WEnDVUoSKUmuCTqdCid8+s/"
       "Vd54u54ylZh1BhFRxLOsqWEqOkFKXfa6XUiBkfAwQzSqSOCdips3t3UMbRdw5rbkuTBfhe7"
       "bLHsdlCkl/xom/"
       "mLTOJjue1yrINRlOOFnbwXiYL2d1UirWWcuHmSPBmaN4LFqbms1wTerJRwRPjxSBwNBK48m"
       "U5DoJrReEUuNCyhcmRUjGHhjOMH5jIGMXGYEEPL7/1Z4aiiZGugLEe6X/"
       "KwQIpdRd4sXTMRbWULRfp3t97PisASbFIr4X0DKMj2wlbmeX/"
       "lYNgqaYSzLkmvH1GN2ryeCs9OR03ESrw2vhjR0vsHXyHKS4fbWJ2g+"
       "O5CXMTwso43C1qKl62E32gj/l+jAdCnv7ehiXsKuT5+ZlrnZb4WS5vkBLffIDkEd//DKqD/"
       "3oy0feKb5ZhjyBiN4saPoNeeaBoiCQYKi/"
       "xgBFv0UCQz3ELLN9HwcpVeGbxqt4F32Nu+7+"
       "zct1PVnPy5dzwHynaad4tYTtHaGpVSV9GcLnCOT6ZxB8hsCHJ/hhttE//wYAAP//"
       "k7pCgg==");

  auto tokenOr = M::unpackToken(phoenixToken);
  if (tokenOr.isError()) {
    EXPECT_EQ("", tokenOr.getError());
  }
  EXPECT_FALSE(tokenOr.isError());

  auto token = tokenOr.takeValue();
  EXPECT_EQ(keyPEM, token->key);

  size_t numCerts = 1;
  EXPECT_EQ(numCerts, token->certChain.size());
  EXPECT_EQ(certPEM, token->certChain.at(0));
}

TEST(TestEntitlementToken, roundTrip) {
  //  auto tokenOr = M::unpackToken(llvm::StringRef(token));
  EntitlementToken t1;
  t1.key = "1234";
  t1.certChain.emplace_back("asdf");

  std::string s = M::packToken(t1);
  // base64(zip(json))
  EXPECT_EQ("eJyrVkpOLSqJT85IzMxTsopWSixOSVOK1VHKTq1UslIyNDI2UaoFAODZCyI=", s);

  auto tokenOr = M::unpackToken(s);
  EXPECT_FALSE(tokenOr.isError());
  auto t2 = std::move(tokenOr.get());
  EXPECT_EQ(t2->key, t1.key);

  size_t numCerts = 1;
  EXPECT_EQ(numCerts, t2->certChain.size());
  EXPECT_EQ("asdf", t2->certChain.at(0));

  std::string s2 = M::packToken(*t2);
  EXPECT_EQ(s, s2);
}
