load("//bazel:api.bzl", "modular_cc_binary", "run_tool")

modular_cc_binary(
    name = "kgen-translate",
    srcs = glob(["*.cpp"]),
    deps = [
        "//AsyncRT:Init",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//KGEN:Compiler",
        "//KGEN:CompilerRT",
        "//KGEN:ExecutionEngine",
        "//KGEN:KGENDialect",
        "//KGEN:MojoParser",
        "//KGEN:ObjectCompiler",
        "//KGEN:Pipeline",
        "//KGEN:Support",
        "//KGEN:ToolCommon",
        "//Support:Globals",
        "//Support:MDialect",
        "@llvm-project//mlir:TranslateLib",
    ],
)

run_tool(
    name = "kgen-translate-standalone",
    data = [
        "//open-source/mojo/stdlib/stdlib",
    ],
    tags = ["manual"],
    tool = ":kgen-translate",
    visibility = ["//visibility:private"],
)
