load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "kgen-opt",
    srcs = glob(["*.cpp"]),
    deps = [
        "//AsyncRT:Init",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//KGEN:Compiler",
        "//KGEN:CompilerRT",
        "//KGEN:ExecutionEngine",
        "//KGEN:KGENDialect",
        "//KGEN:LITDialect",
        "//KGEN:MOGGPreElab",
        "//KGEN:MojoParser",
        "//KGEN:ObjectCompiler",
        "//KGEN:Pipeline",
        "//KGEN:Support",
        "//KGEN:ToolCommon",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:Globals",
        "//Support:MDialect",
        "@llvm-project//mlir:MlirOptLib",
    ],
)
