load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@llvm-project//mlir:tblgen.bzl", "gentbl_cc_library", "td_library")
load("//utils/bazel/build/rules:cc_distributable_static_library.bzl", "cc_distributable_static_library")
load("//utils/bazel/build/rules:globals_library.bzl", "globals_library")
load("//utils/bazel/build/rules:kgen.bzl", "kgen_kernel")
load("//utils/bazel/build/rules:opt_wrapper.bzl", "opt_wrapper")
load("//utils/bazel/build/rules:tablegen.bzl", "driver_option_tablegen", "gentbl_mlir_dialect")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

td_library(
    name = "HLCFDialectTdFiles",
    srcs = glob(["include/KGEN/HLCFDialect/*.td"]),
    includes = ["include"],
    deps = [
        ":InterpreterTdFiles",
        "//Support:MTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "HLCFDialectIncGen",
    dialect = "hlcf",
    td_file = "include/KGEN/HLCFDialect/HLCF.td",
    deps = [
        ":HLCFDialectTdFiles",
        "@llvm-project//mlir:ControlFlowInterfacesTdFiles",
    ],
)

gentbl_cc_library(
    name = "HLCFAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attrdef-decls"],
            "include/KGEN/HLCFDialect/HLCFAttrs.h.inc",
        ),
        (
            ["-gen-attrdef-defs"],
            "include/KGEN/HLCFDialect/HLCFAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/HLCFDialect/HLCFAttrs.td",
    deps = [
        ":HLCFDialectIncGen",
        ":HLCFDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "HLCFEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/HLCFDialect/HLCFEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/HLCFDialect/HLCFEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/HLCFDialect/HLCFAttrs.td",
    deps = [
        ":HLCFDialectIncGen",
        ":HLCFDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "HLCFInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/HLCFDialect/HLCFInterfaces.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/HLCFDialect/HLCFInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/HLCFDialect/HLCFInterfaces.td",
    deps = [
        ":HLCFDialectIncGen",
        ":HLCFDialectTdFiles",
    ],
)

td_library(
    name = "KGENPassTdFile",
    srcs = ["include/KGEN/KGENPasses.td"],
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENPassesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-pass-decls"],
            "include/KGEN/KGENPasses.h.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENPasses.td",
    deps = [
        ":KGENPassTdFile",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

td_library(
    name = "KGENDialectTdFiles",
    srcs = glob(["include/KGEN/KGENDialect/*.td"]),
    includes = ["include"],
    deps = [
        ":InterpreterTdFiles",
        "//Support:DebugInfoTdFiles",
        "//Support:MTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "KGENDialectIncGen",
    dialect = "kgen",
    td_file = "include/KGEN/KGENDialect/KGEN.td",
    deps = [
        ":HLCFDialectTdFiles",
        ":InterpreterTdFiles",
        ":KGENDialectTdFiles",
        "@llvm-project//mlir:ControlFlowInterfacesTdFiles",
        "@llvm-project//mlir:FunctionInterfacesTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENAttrInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attr-interface-decls"],
            "include/KGEN/KGENDialect/KGENAttrInterfaces.h.inc",
        ),
        (
            ["-gen-attr-interface-defs"],
            "include/KGEN/KGENDialect/KGENAttrInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENAttrInterfaces.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attrdef-decls"],
            "include/KGEN/KGENDialect/KGENAttrs.h.inc",
        ),
        (
            ["-gen-attrdef-defs"],
            "include/KGEN/KGENDialect/KGENAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENAttrs.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=kgen",
            ],
            "include/KGEN/KGENDialect/KGENDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENDialectBytecode.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/KGENDialect/KGENEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/KGENDialect/KGENEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENAttrs.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/KGENDialect/KGENInterfaces.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/KGENDialect/KGENInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENInterfaces.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENTypeInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-type-interface-decls"],
            "include/KGEN/KGENDialect/KGENTypeInterfaces.h.inc",
        ),
        (
            ["-gen-type-interface-defs"],
            "include/KGEN/KGENDialect/KGENTypeInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENTypeInterfaces.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

td_library(
    name = "InterpreterTdFiles",
    srcs = glob(["include/KGEN/Interpreter/*.td"]),
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "InterpreterDialectIncGen",
    dialect = "interp",
    td_file = "include/KGEN/Interpreter/Interpreter.td",
    deps = [
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterInterfaceIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/Interpreter/InterpreterInterface.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/Interpreter/InterpreterInterface.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterInterface.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attrdef-decls"],
            "include/KGEN/Interpreter/InterpreterAttrs.h.inc",
        ),
        (
            ["-gen-attrdef-defs"],
            "include/KGEN/Interpreter/InterpreterAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterAttrs.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=interp",
            ],
            "include/KGEN/Interpreter/InterpreterDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterDialectBytecode.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
        "//Support:MTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterOpInterfaceIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/Interpreter/InterpreterOpInterface.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/Interpreter/InterpreterOpInterface.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterInterface.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "MemoryableTypeInterfaceIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-type-interface-decls"],
            "include/KGEN/Interpreter/MemoryableTypeInterface.h.inc",
        ),
        (
            ["-gen-type-interface-defs"],
            "include/KGEN/Interpreter/MemoryableTypeInterface.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterInterface.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

td_library(
    name = "MOGGreElabTdFile",
    srcs = ["include/KGEN/MOGGPreElab/MOGGPreElabPasses.td"],
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "MOGGreElabIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-pass-decls"],
            "include/KGEN/MOGGPreElab/MOGGPreElabPasses.h.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/MOGGPreElab/MOGGPreElabPasses.td",
    deps = [
        ":KGENPassTdFile",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

cc_library(
    name = "MOGGPreElab",
    srcs = glob([
        "lib/MOGGPreElab/*.cpp",
        "lib/MOGGPreElab/*.h",
    ]),
    hdrs = glob(["include/KGEN/MOGGPreElab/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":KGENDialect",
        ":MOGGreElabIncGen",
        ":POPAttrsIncGen",
        ":TransformUtils",
    ],
)

cc_library(
    name = "Interpreter",
    srcs = glob(["lib/Interpreter/*.cpp"]),
    hdrs = glob(["include/KGEN/Interpreter/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":InterpreterAttrsIncGen",
        ":InterpreterDialectBytecodeIncGen",
        ":InterpreterDialectIncGen",
        ":InterpreterOpInterfaceIncGen",
        ":MemoryableTypeInterfaceIncGen",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:MDialect",
        "//Support:Threading",
        "@llvm-project//mlir:IR",
    ],
)

cc_library(
    name = "HLCFDialect",
    srcs = glob(["lib/HLCFDialect/*.cpp"]),
    hdrs = glob([
        "include/KGEN/HLCFDialect/*.h",
        "include/KGEN/KGENDialect/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFAttrsIncGen",
        ":HLCFDialectIncGen",
        ":HLCFEnumsIncGen",
        ":HLCFInterfacesIncGen",
        ":Interpreter",
        ":KGENAttrInterfacesIncGen",
        ":KGENAttrsIncGen",
        ":KGENDialectIncGen",
        ":KGENEnumsIncGen",
        ":KGENInterfacesIncGen",
        ":KGENTypeInterfacesIncGen",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:IPRational",
        "@llvm-project//mlir:IR",
    ],
)

cc_library(
    name = "HLCFDialectAnalysis",
    srcs = glob(["lib/HLCFDialect/Analysis/*.cpp"]),
    hdrs = glob([
        "include/KGEN/HLCFDialect/Analysis/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFDialect",
        "@llvm-project//mlir:IR",
    ],
)

td_library(
    name = "LITDialectTdFiles",
    srcs = glob(["include/KGEN/LITDialect/*.td"]),
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "LITDialectIncGen",
    dialect = "lit",
    td_file = "include/KGEN/LITDialect/LIT.td",
    deps = [
        ":HLCFDialectTdFiles",
        ":InterpreterTdFiles",
        ":KGENDialectTdFiles",
        ":LITDialectTdFiles",
        ":POPDialectTdFiles",
        "@llvm-project//mlir:ControlFlowInterfacesTdFiles",
        "@llvm-project//mlir:FunctionInterfacesTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=lit",
            ],
            "include/KGEN/LITDialect/LITDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITDialectBytecode.td",
    deps = [
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
        "//Support:MTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attrdef-decls",
                "-attrdefs-dialect=lit",
            ],
            "include/KGEN/LITDialect/LITAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
                "-attrdefs-dialect=lit",
            ],
            "include/KGEN/LITDialect/LITAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITAttrs.td",
    deps = [
        ":KGENDialectTdFiles",
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
        "//Support:MTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/LITDialect/LITEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/LITDialect/LITEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITEnums.td",
    deps = [
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/LITDialect/LITInterfaces.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/LITDialect/LITInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITInterfaces.td",
    deps = [
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
    ],
)

cc_library(
    name = "LITDialect",
    srcs = glob(["lib/LITDialect/*.cpp"]),
    hdrs = glob([
        "include/KGEN/HLCFDialect/*.h",
        "include/KGEN/KGENDialect/*.h",
        "include/KGEN/LITDialect/*.h",
        "include/KGEN/LITDialect/*.def",
        "include/KGEN/POPDialect/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFAttrsIncGen",
        ":HLCFDialectIncGen",
        ":HLCFEnumsIncGen",
        ":HLCFInterfacesIncGen",
        ":Interpreter",
        ":KGENAttrInterfacesIncGen",
        ":KGENAttrsIncGen",
        ":KGENDialectIncGen",
        ":KGENEnumsIncGen",
        ":KGENInterfacesIncGen",
        ":KGENTypeInterfacesIncGen",
        ":LITAttrsIncGen",
        ":LITDialectBytecodeIncGen",
        ":LITDialectIncGen",
        ":LITEnumsIncGen",
        ":LITInterfacesIncGen",
        ":POPAttrsIncGen",
        ":POPDialectIncGen",
        ":POPEnumsIncGen",
        "//Support:Base",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:IPRational",
    ],
)

td_library(
    name = "POPDialectTdFiles",
    srcs = glob(["include/KGEN/POPDialect/*.td"]),
    includes = ["include"],
    deps = [
        ":InterpreterTdFiles",
        ":KGENDialectTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "POPDialectIncGen",
    dialect = "pop",
    td_file = "include/KGEN/POPDialect/POP.td",
    deps = [
        ":InterpreterTdFiles",
        ":POPDialectTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_cc_library(
    name = "POPAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attrdef-decls",
                "-attrdefs-dialect=pop",
            ],
            "include/KGEN/POPDialect/POPAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
                "-attrdefs-dialect=pop",
            ],
            "include/KGEN/POPDialect/POPAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/POPDialect/POP.td",
    deps = [
        ":POPDialectIncGen",
        ":POPDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "POPDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=pop",
            ],
            "include/KGEN/POPDialect/POPDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/POPDialect/POPDialectBytecode.td",
    deps = [
        ":POPDialectIncGen",
        ":POPDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "POPEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/POPDialect/POPEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/POPDialect/POPEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/POPDialect/POPAttrs.td",
    deps = [
        ":POPDialectIncGen",
        ":POPDialectTdFiles",
    ],
)

cc_library(
    name = "POPDialect",
    srcs = glob(["lib/POPDialect/*.cpp"]),
    hdrs = glob([
        "include/KGEN/HLCFDialect/*.h",
        "include/KGEN/Interpreter/*.h",
        "include/KGEN/KGENDialect/*.h",
        "include/KGEN/POPDialect/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFInterfacesIncGen",
        ":InterpreterAttrsIncGen",
        ":InterpreterDialectIncGen",
        ":InterpreterOpInterfaceIncGen",
        ":KGENAttrInterfacesIncGen",
        ":KGENAttrsIncGen",
        ":KGENDialectIncGen",
        ":KGENEnumsIncGen",
        ":KGENInterfacesIncGen",
        ":KGENTypeInterfacesIncGen",
        ":MemoryableTypeInterfaceIncGen",
        ":POPAttrsIncGen",
        ":POPDialectBytecodeIncGen",
        ":POPDialectIncGen",
        ":POPEnumsIncGen",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:IPRational",
        "//Support:MDialect",
        "//Support:Threading",
        "@llvm-project//mlir:IR",
    ],
)

cc_library(
    name = "KGENDialect",
    srcs = glob(["lib/KGENDialect/*.cpp"]),
    hdrs = glob([
        "include/KGEN/KGENDialect/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFDialect",
        ":Interpreter",
        ":KGENAttrInterfacesIncGen",
        ":KGENAttrsIncGen",
        ":KGENDialectBytecodeIncGen",
        ":KGENDialectIncGen",
        ":KGENEnumsIncGen",
        ":KGENInterfacesIncGen",
        ":KGENTypeInterfacesIncGen",
        ":Support",
        "//Support:ADT",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:MDialect",
    ],
)

# TODO: This should get replaced with something that actually generates the
# correct version number. (NOTE: It looks like clang, llvm, and lldb do this...)
# For now, just hard code some values.
genrule(
    name = "kgen_version_gen",
    outs = ["KGENVersion.h"],
    # TODO: Properly generate a version using shared variables. See Version.h.in
    #       for all the macro magic to generate versions.
    cmd = "echo '#define KGEN_VERSION_STRING \"1.0.0\"' >> $@\n",
)

cc_library(
    name = "VersionHeader",
    hdrs = [":kgen_version_gen"],
    include_prefix = "KGEN/KGENVersion",
)

_TOOL_COMMON_HEADERS = [
    "include/KGEN/ToolCommon/CLOptions.h",
    "include/KGEN/ToolCommon/CompilationOptions.h",
    "include/KGEN/ToolCommon/KGENPasses.h",
]

# NOTE: Broken out to break circular dependencies
cc_library(
    name = "ToolCommonHeaders",
    hdrs = _TOOL_COMMON_HEADERS,
    strip_include_prefix = "include",
    deps = [
        ":KGENPassesIncGen",
        "//Support:CommonCLOptions",
    ],
)

cc_library(
    name = "Compiler",
    srcs = glob(["lib/Compiler/*.cpp"]),
    hdrs = glob([
        "include/KGEN/Compiler/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":KGENDialect",
        ":KGENDialectIncGen",
        ":KGENInterfacesIncGen",
        ":Pipeline",
        ":ToolCommonHeaders",
        ":VersionHeader",
        "//LLCL:CompilerSupport",
        "//Support:DebugInfoTransforms",
        "//Support:Telemetry",
        "@llvm-project//llvm:OrcJIT",
    ],
)

cc_distributable_static_library(
    name = "CompilerRT.distributable",
    library_name = "libKGENCompilerRT-static.a",
    deps = [
        ":CompilerRT.static",
        "//ArraySupport",
        "//CUDASupport:Globals",
        "//Config",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals.static",
        "//LLCL:Support",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:Filesystem",
        "//Support:Globals.static",
        "//Support:ML",
        "//Support:Profiling",
        "//Support:Threading",
        "@llvm-project//llvm:Demangle",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:Support",
    ],
)

write_file(
    name = "gen_link_test",
    out = "LinkTest.cpp",
    content = ["""
#include "gtest/gtest.h"

extern "C" bool KGEN_CompilerRT_Initialize();

TEST(LinkTest, works) {
    EXPECT_TRUE(KGEN_CompilerRT_Initialize());
}
"""],
)

cc_test(
    name = "CompilerRTLinkTest",
    srcs = [
        "include/KGEN/CompilerRT/Registration.h",
        ":gen_link_test",
    ],
    copts = ["-Wno-global-constructors"],
    linkopts = ["-lz"],
    deps = [
        ":CompilerRT.distributable",
        "@com_github_google_googletest//:gtest_main",
    ],
)

globals_library(
    name = "CompilerRT",
    srcs = glob([
        "lib/CompilerRT/*.cpp",
        "lib/CompilerRT/*.h",
    ]),
    hdrs = glob([
        "include/KGEN/CompilerRT/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        "//ArraySupport",
        "//CUDASupport:CUDASupportHeaders",
        "//CUDASupport:Globals",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//LLCL:RuntimeHeaders",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:Globals",
        "//Support:Threading",
    ],
)

# TODO: Move to configure.bzl?
# Share this across variables:
# https://bazel.build/build/share-variables#sharing_variables_across_multiple_build_files
MOJO_CONFIG_COPTS = ["-DMOJO_CONFIG_SECTION=mojo"]

cc_library(
    name = "Support",
    srcs = glob(["lib/Support/*.cpp"]),
    hdrs = glob([
        "include/KGEN/Support/*.h",
        "include/KGEN/KGENDialect/*.h",
    ]),
    copts = MOJO_CONFIG_COPTS,
    strip_include_prefix = "include",
    deps = [
        "//LLCL:Support",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:ML",
        "//Support:Profiling",
    ],
)

cc_library(
    name = "LowerLIT",
    srcs = glob(["lib/LowerLIT/*.cpp"]),
    hdrs = glob(["include/KGEN/LowerLIT/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":KGENDialect",
        ":LITDialect",
        ":ToolCommonHeaders",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:IR",
    ],
)

cc_library(
    name = "KGENToLLVM",
    srcs = glob([
        "lib/KGENToLLVM/*.cpp",
        "lib/KGENToLLVM/*.h",
    ]),
    hdrs = glob(["include/KGEN/KGENToLLVM/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFDialectAnalysis",
        ":KGENDialect",
        ":ToolCommon",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:IR",
    ],
)

cc_library(
    name = "Transforms",
    srcs = glob(["lib/Transforms/*.cpp"]),
    hdrs = glob(["include/KGEN/Transforms/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFDialect",
        ":HLCFDialectAnalysis",
        ":ToolCommonHeaders",
        ":TransformUtils",
        "//LLCL:Runtime",
        "//Support:DebugInfoDialect",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:TransformUtils",
    ],
)

cc_library(
    name = "Elaborator",
    srcs = glob([
        "lib/Elaborator/*.cpp",
        "lib/Elaborator/*.h",
    ]),
    hdrs = glob(["include/KGEN/Elaborator/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":KGENDialect",
        ":LITDialect",
        ":ToolCommonHeaders",
        ":VersionHeader",
        "//Cache",
        "//LLCL:CompilerSupport",
    ],
)

cc_library(
    name = "Pipeline",
    srcs = glob(["lib/Pipeline/*.cpp"]),
    hdrs = glob(["include/KGEN/Pipeline/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Elaborator",
        ":KGENPassesIncGen",
        ":LowerLIT",
        ":MOGGPreElab",
        ":Transforms",
        "//Support:DebugInfoToLLVM",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:TransformUtils",
    ],
)

cc_library(
    name = "TransformUtils",
    srcs = glob(["lib/TransformUtils/*.cpp"]),
    hdrs = glob(["include/KGEN/TransformUtils/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":HLCFDialect",
        ":LITDialect",
        ":Support",
        "@llvm-project//llvm:OrcJIT",
        "@llvm-project//mlir:BuiltinToLLVMIRTranslation",
    ],
)

cc_library(
    name = "ObjectCompiler",
    srcs = glob([
        "lib/ObjectCompiler/*.cpp",
        "lib/ObjectCompiler/*.h",
    ]),
    hdrs = glob(["include/KGEN/ObjectCompiler/*.h"]),
    strip_include_prefix = "include",
    deps = [
        ":Compiler",
        ":KGENToLLVM",
        ":Pipeline",
        "//LLCL:CompilerSupport",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

cc_library(
    name = "MojoParser",
    srcs = glob([
        "lib/MojoParser/*.cpp",
        "lib/MojoParser/*.h",
    ]),
    hdrs = glob([
        "include/KGEN/MojoParser/*.h",
        "include/KGEN/MojoParser/*.def",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":Compiler",
        ":ToolCommon",
    ],
)

cc_library(
    name = "MojoTooling",
    srcs = glob([
        "lib/MojoTooling/*.cpp",
        "lib/MojoTooling/*.h",
    ]),
    hdrs = glob([
        "include/KGEN/MojoTooling/*.h",
        "include/KGEN/MojoTooling/*.def",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":MojoParser",
    ],
)

cc_library(
    name = "MojoTesting",
    srcs = glob([
        "lib/MojoTesting/*.cpp",
        "lib/MojoTesting/*.h",
    ]),
    hdrs = glob([
        "include/KGEN/MojoTesting/*.h",
        "include/KGEN/MojoTesting/*.def",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":MojoParser",
        ":MojoTooling",
        ":ToolCommon",
        "@llvm-project//mlir:MlirLspServerSupportLib",
    ],
)

genrule(
    name = "FakeCASIDHeadersGen",
    outs = [
        "COMPILERRTCASID.h",
        "ORCCASID.h",
    ],
    cmd = """
touch $(location :ORCCASID.h)
echo '

#ifndef BAZEL_CAS_SIDESTEP
#define BAZEL_CAS_SIDESTEP
#include "llvm/ADT/StringRef.h"

namespace M::CASID {

inline constexpr llvm::StringLiteral kCompilerRT = "bazel not support this yet";
inline constexpr llvm::StringLiteral kOrcRT = "bazel not support this yet";
}  // namespace M::CASID

#endif
' > $(location :COMPILERRTCASID.h)
""",
)

cc_library(
    name = "FakeCASIDHeaders",
    hdrs = [":FakeCASIDHeadersGen"],
    include_prefix = "KGEN/ExecutionEngine",
)

cc_library(
    name = "ExecutionEngine",
    srcs = glob([
        "lib/ExecutionEngine/*.cpp",
        "lib/ExecutionEngine/*.h",
    ]),
    hdrs = glob([
        "include/KGEN/ExecutionEngine/*.h",
        "include/KGEN/ExecutionEngine/*.def",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":FakeCASIDHeaders",
        ":MojoParser",
        ":MojoTooling",
        ":VersionHeader",
        "@llvm-project//llvm:OrcDebugging",
        "@llvm-project//mlir:MlirLspServerSupportLib",
    ],
)

cc_library(
    name = "Package",
    srcs = glob([
        "lib/Package/*.cpp",
    ]),
    hdrs = glob([
        "include/KGEN/Package/*.h",
    ]),
    strip_include_prefix = "include",
    deps = [
        ":Compiler",
        ":KGENDialect",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

cc_library(
    name = "ToolCommon",
    srcs = glob(["lib/ToolCommon/**/*.cpp"]),
    hdrs = glob(
        [
            "include/KGEN/ToolCommon/*.h",
            "include/KGEN/Compiler/*.h",
        ],
        exclude = _TOOL_COMMON_HEADERS,
    ),
    strip_include_prefix = "include",
    deps = [
        ":HLCFDialect",
        ":KGENPassesIncGen",
        ":LITDialect",
        ":MOGGPreElab",
        ":POPDialect",
        ":Package",
        "//Support:CommonCLOptions",
        "//Support:DebugInfoDialect",
        "//Support:DebugInfoToLLVM",
        "@llvm-project//llvm:OrcJIT",
        "@llvm-project//mlir:BuiltinToLLVMIRTranslation",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

cc_binary(
    name = "hash-mlir",
    srcs = glob(["tools/hash-mlir/*.cpp"]),
    deps = [
        ":ToolCommon",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

cc_binary(
    name = "kgen",
    srcs = glob(["tools/kgen/*.cpp"]),
    deps = [
        ":Compiler",
        ":CompilerRT",
        ":ExecutionEngine",
        ":KGENDialect",
        ":MojoParser",
        ":ObjectCompiler",
        ":Package",
        ":Pipeline",
        ":Support",
        ":ToolCommon",
        "//Config",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:Globals",
        "//Support:Init",
        "//Support:MArchTarget",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

cc_binary(
    name = "kgen-opt",
    srcs = glob(["tools/kgen-opt/*.cpp"]),
    deps = [
        ":Compiler",
        ":CompilerRT",
        ":ExecutionEngine",
        ":KGENDialect",
        ":LITDialect",
        ":MOGGPreElab",
        ":MojoParser",
        ":ObjectCompiler",
        ":Package",
        ":Pipeline",
        ":Support",
        ":ToolCommon",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:Globals",
        "//Support:Init",
        "//Support:MDialect",
        "@llvm-project//mlir:MlirOptLib",
    ],
)

cc_binary(
    name = "kgen-reduce",
    srcs = glob([
        "tools/kgen-reduce/*.cpp",
        "tools/kgen-reduce/*.h",
    ]),
    deps = [
        ":Compiler",
        ":CompilerRT",
        ":ExecutionEngine",
        ":HLCFDialect",
        ":KGENDialect",
        ":MojoParser",
        ":ObjectCompiler",
        ":Pipeline",
        ":ToolCommon",
        ":TransformUtils",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
        "//Support:Init",
        "@llvm-project//mlir:MlirOptLib",
    ],
)

cc_binary(
    name = "kgen-translate",
    srcs = glob([
        "tools/kgen-translate/*.cpp",
        "tools/kgen-translate/*.h",
    ]),
    deps = [
        ":Compiler",
        ":CompilerRT",
        ":ExecutionEngine",
        ":KGENDialect",
        ":MojoParser",
        ":ObjectCompiler",
        ":Pipeline",
        ":Support",
        ":ToolCommon",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "//Support:Init",
        "//Support:MDialect",
        "@llvm-project//mlir:MlirTranslateMain",
    ],
)

cc_binary(
    name = "llvm-module-split",
    srcs = glob([
        "tools/llvm-module-split/*.cpp",
    ]),
    deps = [
        ":Compiler",
        ":ObjectCompiler",
        ":ToolCommon",
        "//Config",
        "//LLCL:Runtime",
        "//Support:Base",
        "@llvm-project//llvm:Support",
    ],
)

cc_binary(
    name = "mojo-lsp-server",
    srcs = glob([
        "tools/mojo-lsp-server/*.cpp",
        "tools/mojo-lsp-server/*.h",
    ]),
    deps = [
        ":LITDialect",
        ":MojoParser",
        ":MojoTooling",
        ":ObjectCompiler",
        ":Pipeline",
        ":Support",
        ":ToolCommon",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
        "//Support:Init",
        "//Support:Telemetry",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:MlirLspServerLib",
    ],
)

cc_binary(
    name = "mojo-repl-entry-point",
    srcs = glob([
        "tools/mojo-repl-entry-point/*.cpp",
        "tools/mojo-repl-entry-point/*.h",
    ]),
    # We need to prevent inline function expansion to guarentee our entry
    # point function is correctly invoked.
    copts = [
        "-O0",
        "-g0",
    ],
    deps = [
        ":CompilerRT.static",
        ":MojoParser",
        ":MojoTooling",
        ":ObjectCompiler",
        ":Pipeline",
        ":ToolCommon",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
        "//Support:Init",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:MlirLspServerLib",
    ],
)

cc_library(
    name = "MojoToolsCommon",
    srcs = glob([
        "tools/common/*.cpp",
    ]),
    hdrs = glob([
        "tools/common/*.h",
    ]),
    strip_include_prefix = "tools/common",
    deps = [
        "//Support:Driver",
        "//Support:Telemetry",
    ],
)

cc_binary(
    name = "mojo-prime-package-cache",
    srcs = glob([
        "tools/mojo-prime-package-cache/*.cpp",
        "tools/mojo-prime-package-cache/*.h",
    ]),
    deps = [
        ":CompilerRT",
        ":ExecutionEngine",
        ":KGENDialect",
        ":LITDialect",
        ":MojoParser",
        ":MojoTooling",
        ":MojoToolsCommon",
        ":ObjectCompiler",
        ":Package",
        ":Pipeline",
        ":ToolCommon",
        "//Config",
        "//LLCL:CompilerSupport",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:Driver",
        "//Support:Globals",
        "//Support:Init",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:MlirLspServerLib",
    ],
)

expand_template(
    name = "MojoDebugHeaderGen",
    out = "MojoDebug.h",
    substitutions = select({
        "@platforms//os:macos": {
            "@CMAKE_SHARED_LIBRARY_PREFIX@": "lib",
            "@CMAKE_SHARED_LIBRARY_SUFFIX@": ".dylib",
        },
        "@platforms//os:linux": {
            "@CMAKE_SHARED_LIBRARY_PREFIX@": "lib",
            "@CMAKE_SHARED_LIBRARY_SUFFIX@": ".so",
        },
    }),
    template = "tools/mojo/Debug/MojoDebug.h.in",
)

cc_library(
    name = "MojoDebugHeader",
    hdrs = [":MojoDebugHeaderGen"],
    include_prefix = "Debug",
)

cc_binary(
    name = "mojo",
    srcs = glob([
        "tools/mojo/**/*.h",
        "tools/mojo/**/*.cpp",
    ]),
    includes = ["tools/mojo"],
    local_defines = ["MODULAR_MOJO_BUILD_SERVER_PREVIEW"],
    deps = [
        ":Build.inc_files",
        ":BuildProject.inc_files",
        ":Compiler",
        ":CompilerRT",
        ":Debug.inc_files",
        ":Demangle.inc_files",
        ":Doc.inc_files",
        ":ExecutionEngine",
        ":Format.inc_files",
        ":Index.inc_files",
        ":KGENDialect",
        ":LITDialect",
        ":MojoBuild",
        ":MojoDebugHeader",
        ":MojoParser",
        ":MojoTesting",
        ":MojoTooling",
        ":MojoToolsCommon",
        ":ObjectCompiler",
        ":POPDialect",
        ":Package",
        ":Package.inc_files",
        ":REPL.inc_files",
        ":Run.inc_files",
        ":Support",
        ":Test.inc_files",
        ":ToolCommon",
        "//Config",
        "//LLCL:Runtime",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:CrashReporting",
        "//Support:Driver",
        "//Support:Filesystem",
        "//Support:Globals",
        "//Support:Init",
        "//Support:MArchTarget",
        "//Support:MDialect",
        "//Support:Telemetry",
    ],
)

opt_wrapper(
    name = "mojo.opt",
    dep = ":mojo",
)

[
    driver_option_tablegen(
        name = command,
        srcs = glob(["tools/mojo/{}/*.td".format(command)]),
        includes = ["tools/mojo"],
        manual_name = "mojo-{}".format(command.lower()),
        markdown_name = command.lower(),
        td_file = "tools/mojo/{command}/{command}Options.td".format(command = command),
        deps = [
            ":MojoDescriptionTdFiles",
        ],
    )
    for command in [
        "Build",
        "BuildProject",
        "Debug",
        "Demangle",
        "Doc",
        "Format",
        "Package",
        "REPL",
        "Run",
        "Test",
    ]
]

driver_option_tablegen(
    name = "Index",
    srcs = ["tools/mojo/DriverOptions.td"],
    manual_name = "mojo",
    markdown_name = "index",
    opts = ["-DMODULAR_MOJO_BUILD_SERVER_PREVIEW"],
    td_file = "tools/mojo/DriverOptions.td",
    deps = [
        ":Build.td_library",
        ":BuildProject.td_library",
        ":Debug.td_library",
        ":Demangle.td_library",
        ":Doc.td_library",
        ":Format.td_library",
        ":MojoDescriptionTdFiles",
        ":Package.td_library",
        ":REPL.td_library",
        ":Run.td_library",
        ":Test.td_library",
    ],
)

td_library(
    name = "MojoDescriptionTdFiles",
    srcs = glob([
        "tools/mojo/*.td",
        "tools/mojo/BuildProject/*.td",
        "tools/mojo/Common/*.td",
    ]),
    includes = ["tools/mojo"],
    deps = [
        "//Support:DriverCommandTdFiles",
        "//Support:OptTableTdFiles",
    ],
)

cc_library(
    name = "MojoBuild",
    srcs = glob([
        "lib/MojoBuild/*.cpp",
        "lib/MojoBuild/*.h",
    ]),
    hdrs = glob(["include/KGEN/MojoBuild/*.h"]),
    strip_include_prefix = "include",
    deps = [
        "//Support:Base",
        "//Support:Filesystem",
        "@llvm-project//mlir:MlirLspServerSupportLib",
    ],
)

kgen_kernel(
    name = "mojo_build_server",
    src = "tools/mojo-build-server/mojo_build_server.mojo",
)

cc_binary(
    name = "mojo-build-server",
    deps = [
        ":CompilerRT",
        ":MojoBuild",
        ":mojo_build_server",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
    ],
)

genrule(
    name = "gen_exports_file_linux",
    srcs = ["@llvm-project//lldb:source/API/liblldb-private.exports"],
    outs = ["exports_linux.txt"],
    cmd = """
cat > $(OUTS) <<EOF
{
  global:
    $$(sed 's/$$/;/g' $(SRCS))
};
EOF
""",
)

genrule(
    name = "gen_exports_file_macos",
    srcs = ["@llvm-project//lldb:source/API/liblldb-private.exports"],
    outs = ["exports_macos.txt"],
    cmd = "sed 's/^/_/g' $(SRCS) > $(OUTS)",
)

globals_library(
    name = "LLDB",
    srcs = [],
    additional_linker_inputs = [
        "@llvm-project//lldb:source/API/liblldb-private.exports",
        ":gen_exports_file_linux",
        ":gen_exports_file_macos",
    ],
    linkopts = ["-ledit"] + select({
        "@platforms//os:linux": [
            "-Wl,--export-dynamic-symbol-list=$(location :gen_exports_file_linux)",
        ],
        "@platforms//os:macos": [
            "-Wl,-exported_symbols_list-=$(location :gen_exports_file_macos)",
        ],
    }),
    deps = ["@llvm-project//lldb:liblldb.static"],
)

globals_library(
    name = "MojoLLDB",
    srcs = glob(["lib/MojoLLDB/**/*.cpp"]),
    hdrs = glob(["lib/MojoLLDB/**/*.h"]),
    copts = [
        "-fvisibility=default",
        "-iquoteexternal/",
    ],
    local_defines = [
        "MODULAR_BUILDING_LIBRARY",
    ],
    deps = [
        ":ExecutionEngine",
        ":KGENDialect",
        ":LLDB",
        ":LLDB.headers",
        ":MojoTooling",
        ":ObjectCompiler",
        "//Support:Base",
        "//Support:CrashReporting",
        "//Support:Init",
        "@llvm-project//lldb/source/Plugins:PluginSymbolFileDWARFHeaders",
    ],
)

genrule(
    name = "gen_maptlotlib_initialization_script",
    outs = ["gen_maptlotlib_initialization_tool.py"],
    cmd = """
cat > $(OUTS) <<EOF
import sys

print(
    open(sys.argv[1]).read()
    .replace("@ENABLE_MATPLOTLIB_STR@", open(sys.argv[2]).read())
    .replace("@MATPLOTLIB_BACKEND_STR@", open(sys.argv[3]).read())
)
EOF
""",
)

py_binary(
    name = "gen_maptlotlib_initialization_tool",
    srcs = [":gen_maptlotlib_initialization_script"],
)

genrule(
    name = "gen_maptlotlib_initialization",
    srcs = [
        "lib/MojoJupyter/MatplotlibInitialization.h.in",
        "lib/MojoJupyter/matplotlib_backend.py",
        "lib/MojoJupyter/enable_matplotlib.py",
    ],
    outs = ["MojoJupyter/MatplotlibInitialization.h"],
    cmd = """
$(location :gen_maptlotlib_initialization_tool) \
    $(location :lib/MojoJupyter/MatplotlibInitialization.h.in) \
    $(location :lib/MojoJupyter/enable_matplotlib.py) \
    $(location :lib/MojoJupyter/matplotlib_backend.py) > $(OUTS)
""",
    tools = [":gen_maptlotlib_initialization_tool"],
)

cc_library(
    name = "MojoJupyter",
    srcs = glob(["lib/MojoJupyter/*.cpp"]) + [":gen_maptlotlib_initialization"],
    hdrs = glob([
        "include/KGEN/MojoJupyter/*.h",
    ]),
    copts = [
        "-fvisibility=default",
        "-iquoteexternal/",
    ],
    local_defines = [
        "MODULAR_BUILDING_JUPYTER_LIBRARY",
    ],
    strip_include_prefix = "include",
    deps = [
        ":KGENDialect",
        ":MojoLLDB",
        ":MojoTooling",
        "@llvm-project//lldb/source/Plugins:PluginSymbolFileDWARFHeaders",
    ],
)
