load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@build_bazel_apple_support//rules:apple_genrule.bzl", "apple_genrule")
load("@rules_pkg//pkg:mappings.bzl", "pkg_filegroup", "pkg_files")
load(
    "//bazel:api.bzl",
    "gentbl_cc_library",
    "gentbl_mlir_dialect",
    "gentbl_modular_passes",
    "modular_cc_binary",
    "modular_cc_library",
    "modular_cc_test",
    "modular_shared_library",
    "modular_versioned_expand_template",
    "td_library",
)
load("//bazel:config.bzl", "ASYNCRT_PROFILING_LOCAL_DEFINES", "CONFIG_SECTION_LOCAL_DEFINES", "KERNELS_BUILD_TYPE_LOCAL_DEFINES")
load("//utils/bazel/build/rules:cc_distributable_static_library.bzl", "cc_distributable_static_library")

td_library(
    name = "CustomDialectTdFiles",
    srcs = glob(["include/KGEN/CustomDialect/*.td"]),
    includes = ["include"],
    deps = [
        "//Support:MTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "CustomDialectIncGen",
    dialect = "custom",
    td_file = "include/KGEN/CustomDialect/Custom.td",
    deps = [
        ":CustomDialectTdFiles",
    ],
)

modular_cc_library(
    name = "CustomDialect",
    srcs = glob(["lib/CustomDialect/**/*.cpp"]),
    hdrs = glob(["include/KGEN/CustomDialect/**/*.h"]),
    deps = [
        ":CustomDialectIncGen",
        "//Support:Base",
        "@llvm-project//mlir:IR",
    ],
)

td_library(
    name = "CODialectTdFiles",
    srcs = glob(["include/KGEN/CODialect/*.td"]),
    includes = ["include"],
    deps = [
        ":KGENDialectTdFiles",
        "//Support:MTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "CODialectIncGen",
    dialect = "co",
    td_file = "include/KGEN/CODialect/CO.td",
    deps = [
        ":CODialectTdFiles",
        "@llvm-project//mlir:ControlFlowInterfacesTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_cc_library(
    name = "CODialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=co",
            ],
            "include/KGEN/CODialect/CODialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/CODialect/CODialectBytecode.td",
    deps = [
        ":CODialectIncGen",
        ":CODialectTdFiles",
        ":KGENDialectIncGen",
    ],
)

modular_cc_library(
    name = "CODialect",
    srcs = glob(["lib/CODialect/*.cpp"]),
    hdrs = glob(["include/KGEN/CODialect/*.h"]),
    deps = [
        ":CODialectBytecodeIncGen",
        ":CODialectIncGen",
        ":KGENDialect",
        ":TransformUtils",
        "//Support:Base",
        "//Support:Compiler",
        "@llvm-project//mlir:IR",
    ],
)

td_library(
    name = "HLCFDialectTdFiles",
    srcs = glob(["include/KGEN/HLCFDialect/*.td"]),
    includes = ["include"],
    deps = [
        ":InterpreterTdFiles",
        "//Support:MTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "HLCFDialectIncGen",
    dialect = "hlcf",
    td_file = "include/KGEN/HLCFDialect/HLCF.td",
    deps = [
        ":HLCFDialectTdFiles",
        "@llvm-project//mlir:ControlFlowInterfacesTdFiles",
    ],
)

gentbl_cc_library(
    name = "HLCFAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attrdef-decls"],
            "include/KGEN/HLCFDialect/HLCFAttrs.h.inc",
        ),
        (
            ["-gen-attrdef-defs"],
            "include/KGEN/HLCFDialect/HLCFAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/HLCFDialect/HLCFAttrs.td",
    deps = [
        ":HLCFDialectIncGen",
        ":HLCFDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "HLCFEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/HLCFDialect/HLCFEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/HLCFDialect/HLCFEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/HLCFDialect/HLCFAttrs.td",
    deps = [
        ":HLCFDialectIncGen",
        ":HLCFDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "HLCFInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/HLCFDialect/HLCFInterfaces.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/HLCFDialect/HLCFInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/HLCFDialect/HLCFInterfaces.td",
    deps = [
        ":HLCFDialectIncGen",
        ":HLCFDialectTdFiles",
    ],
)

td_library(
    name = "KGENPassTdFile",
    srcs = ["include/KGEN/KGENPasses.td"],
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_modular_passes(
    name = "KGENPassesIncGen",
    td_file = "include/KGEN/KGENPasses.td",
    deps = [
        ":KGENPassTdFile",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

td_library(
    name = "KGENDialectTdFiles",
    srcs = glob(["include/KGEN/KGENDialect/*.td"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        ":InterpreterTdFiles",
        "//Support:DebugInfoTdFiles",
        "//Support:MTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "KGENDialectIncGen",
    dialect = "kgen",
    td_file = "include/KGEN/KGENDialect/KGEN.td",
    deps = [
        ":HLCFDialectTdFiles",
        ":InterpreterTdFiles",
        ":KGENDialectTdFiles",
        ":KGENEnumsIncGen",
        "@llvm-project//mlir:ControlFlowInterfacesTdFiles",
        "@llvm-project//mlir:FunctionInterfacesTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENAttrInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attr-interface-decls"],
            "include/KGEN/KGENDialect/KGENAttrInterfaces.h.inc",
        ),
        (
            ["-gen-attr-interface-defs"],
            "include/KGEN/KGENDialect/KGENAttrInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENAttrInterfaces.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attrdef-decls"],
            "include/KGEN/KGENDialect/KGENAttrs.h.inc",
        ),
        (
            ["-gen-attrdef-defs"],
            "include/KGEN/KGENDialect/KGENAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENAttrs.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=kgen",
            ],
            "include/KGEN/KGENDialect/KGENDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENDialectBytecode.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/KGENDialect/KGENEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/KGENDialect/KGENEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENAttrs.td",
    deps = [
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/KGENDialect/KGENInterfaces.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/KGENDialect/KGENInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENInterfaces.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "KGENTypeInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-type-interface-decls"],
            "include/KGEN/KGENDialect/KGENTypeInterfaces.h.inc",
        ),
        (
            ["-gen-type-interface-defs"],
            "include/KGEN/KGENDialect/KGENTypeInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/KGENDialect/KGENTypeInterfaces.td",
    deps = [
        ":KGENDialectIncGen",
        ":KGENDialectTdFiles",
    ],
)

td_library(
    name = "InterpreterTdFiles",
    srcs = glob(["include/KGEN/Interpreter/*.td"]),
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "InterpreterDialectIncGen",
    dialect = "interp",
    td_file = "include/KGEN/Interpreter/Interpreter.td",
    deps = [
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterInterfaceIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/Interpreter/InterpreterInterface.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/Interpreter/InterpreterInterface.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterInterface.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-attrdef-decls"],
            "include/KGEN/Interpreter/InterpreterAttrs.h.inc",
        ),
        (
            ["-gen-attrdef-defs"],
            "include/KGEN/Interpreter/InterpreterAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterAttrs.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=interp",
            ],
            "include/KGEN/Interpreter/InterpreterDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterDialectBytecode.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
        "//Support:MTdFiles",
    ],
)

gentbl_cc_library(
    name = "InterpreterOpInterfaceIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/Interpreter/InterpreterOpInterface.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/Interpreter/InterpreterOpInterface.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterInterface.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

gentbl_cc_library(
    name = "MemoryableTypeInterfaceIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-type-interface-decls"],
            "include/KGEN/Interpreter/MemoryableTypeInterface.h.inc",
        ),
        (
            ["-gen-type-interface-defs"],
            "include/KGEN/Interpreter/MemoryableTypeInterface.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/Interpreter/InterpreterInterface.td",
    deps = [
        ":InterpreterDialectIncGen",
        ":InterpreterTdFiles",
    ],
)

td_library(
    name = "MOGGreElabTdFile",
    srcs = ["include/KGEN/MOGGPreElab/MOGGPreElabPasses.td"],
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_modular_passes(
    name = "MOGGreElabIncGen",
    td_file = "include/KGEN/MOGGPreElab/MOGGPreElabPasses.td",
    deps = [
        ":KGENPassTdFile",
        "@llvm-project//mlir:PassBaseTdFiles",
    ],
)

modular_cc_library(
    name = "MOGGPreElab",
    srcs = glob([
        "lib/MOGGPreElab/*.cpp",
        "lib/MOGGPreElab/*.h",
    ]),
    hdrs = glob(["include/KGEN/MOGGPreElab/*.h"]),
    deps = [
        ":KGENDialect",
        ":LITDialect",
        ":MOGGreElabIncGen",
        ":POPAttrsIncGen",
        ":TransformUtils",
    ],
)

modular_cc_library(
    name = "Interpreter",
    srcs = glob(["lib/Interpreter/*.cpp"]),
    hdrs = glob(["include/KGEN/Interpreter/*.h"]),
    deps = [
        ":InterpreterAttrsIncGen",
        ":InterpreterDialectBytecodeIncGen",
        ":InterpreterDialectIncGen",
        ":InterpreterOpInterfaceIncGen",
        ":MemoryableTypeInterfaceIncGen",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:MDialect",
        "//Support:Threading",
        "@llvm-project//mlir:ControlFlowInterfaces",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "HLCFDialect",
    srcs = glob(["lib/HLCFDialect/*.cpp"]),
    hdrs = glob(["include/KGEN/HLCFDialect/*.h"]),
    deps = [
        ":HLCFAttrsIncGen",
        ":HLCFDialectIncGen",
        ":HLCFEnumsIncGen",
        ":HLCFInterfacesIncGen",
        ":Interpreter",
        ":KGENDialect.headers",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:IPRational",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:InferTypeOpInterface",
    ],
)

modular_cc_library(
    name = "HLCFDialectAnalysis",
    srcs = glob(["lib/HLCFDialect/Analysis/*.cpp"]),
    hdrs = glob([
        "include/KGEN/HLCFDialect/Analysis/*.h",
    ]),
    deps = [
        ":HLCFDialect",
        "@llvm-project//mlir:IR",
    ],
)

td_library(
    name = "LITDialectTdFiles",
    srcs = glob(["include/KGEN/LITDialect/*.td"]),
    includes = ["include"],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "LITDialectIncGen",
    dialect = "lit",
    td_file = "include/KGEN/LITDialect/LIT.td",
    deps = [
        ":HLCFDialectTdFiles",
        ":InterpreterTdFiles",
        ":KGENDialectTdFiles",
        ":LITDialectTdFiles",
        ":POPDialectTdFiles",
        "@llvm-project//mlir:ControlFlowInterfacesTdFiles",
        "@llvm-project//mlir:FunctionInterfacesTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=lit",
            ],
            "include/KGEN/LITDialect/LITDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITDialectBytecode.td",
    deps = [
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
        "//Support:MTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attrdef-decls",
                "-attrdefs-dialect=lit",
            ],
            "include/KGEN/LITDialect/LITAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
                "-attrdefs-dialect=lit",
            ],
            "include/KGEN/LITDialect/LITAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITAttrs.td",
    deps = [
        ":KGENDialectTdFiles",
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
        "//Support:MTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/LITDialect/LITEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/LITDialect/LITEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITEnums.td",
    deps = [
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "LITInterfacesIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-op-interface-decls"],
            "include/KGEN/LITDialect/LITInterfaces.h.inc",
        ),
        (
            ["-gen-op-interface-defs"],
            "include/KGEN/LITDialect/LITInterfaces.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/LITDialect/LITInterfaces.td",
    deps = [
        ":LITDialectIncGen",
        ":LITDialectTdFiles",
    ],
)

modular_cc_library(
    name = "LITDialect",
    srcs = glob(["lib/LITDialect/*.cpp"]),
    hdrs = glob([
        "include/KGEN/LITDialect/*.h",
        "include/KGEN/LITDialect/*.def",
    ]),
    deps = [
        ":CODialect",
        ":CODialectIncGen",
        ":Interpreter",
        ":KGENDialect",
        ":LITAttrsIncGen",
        ":LITDialectBytecodeIncGen",
        ":LITDialectIncGen",
        ":LITEnumsIncGen",
        ":LITInterfacesIncGen",
        ":POPDialect",
        "//Support:Base",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:IPRational",
        "//Support:MDialect",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
    ],
)

td_library(
    name = "POPDialectTdFiles",
    srcs = glob(["include/KGEN/POPDialect/*.td"]),
    includes = ["include"],
    deps = [
        ":CODialectTdFiles",
        ":InterpreterTdFiles",
        ":KGENDialectTdFiles",
        "@llvm-project//mlir:BuiltinDialectTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_mlir_dialect(
    name = "POPDialectIncGen",
    dialect = "pop",
    td_file = "include/KGEN/POPDialect/POP.td",
    deps = [
        ":InterpreterTdFiles",
        ":POPDialectTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
    ],
)

gentbl_cc_library(
    name = "POPAttrsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-attrdef-decls",
                "-attrdefs-dialect=pop",
            ],
            "include/KGEN/POPDialect/POPAttrs.h.inc",
        ),
        (
            [
                "-gen-attrdef-defs",
                "-attrdefs-dialect=pop",
            ],
            "include/KGEN/POPDialect/POPAttrs.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/POPDialect/POP.td",
    deps = [
        ":POPDialectIncGen",
        ":POPDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "POPDialectBytecodeIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            [
                "-gen-bytecode",
                "-bytecode-dialect=pop",
            ],
            "include/KGEN/POPDialect/POPDialectBytecode.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/POPDialect/POPDialectBytecode.td",
    deps = [
        ":POPDialectIncGen",
        ":POPDialectTdFiles",
    ],
)

gentbl_cc_library(
    name = "POPEnumsIncGen",
    includes = ["include"],
    strip_include_prefix = "include",
    tbl_outs = [
        (
            ["-gen-enum-decls"],
            "include/KGEN/POPDialect/POPEnums.h.inc",
        ),
        (
            ["-gen-enum-defs"],
            "include/KGEN/POPDialect/POPEnums.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/KGEN/POPDialect/POPAttrs.td",
    deps = [
        ":POPDialectIncGen",
        ":POPDialectTdFiles",
    ],
)

modular_cc_library(
    name = "POPDialect",
    srcs = glob(["lib/POPDialect/*.cpp"]),
    hdrs = glob(["include/KGEN/POPDialect/*.h"]),
    deps = [
        ":CODialect",
        ":CODialectIncGen",
        ":Interpreter",
        ":KGENDialect",
        ":MemoryableTypeInterfaceIncGen",
        ":POPAttrsIncGen",
        ":POPDialectBytecodeIncGen",
        ":POPDialectIncGen",
        ":POPEnumsIncGen",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:IPRational",
        "//Support:MDialect",
        "//Support:Threading",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "KGENDialect.headers",
    hdrs = glob(["include/KGEN/KGENDialect/*.h"]),
    visibility = ["//visibility:private"],
    deps = [
        ":KGENAttrInterfacesIncGen",
        ":KGENAttrsIncGen",
        ":KGENDialectIncGen",
        ":KGENEnumsIncGen",
        ":KGENInterfacesIncGen",
        ":KGENTypeInterfacesIncGen",
    ],
)

modular_cc_library(
    name = "KGENDialect",
    srcs = glob(["lib/KGENDialect/*.cpp"]),
    hdrs = glob(["include/KGEN/KGENDialect/*.h"]),
    local_defines = KERNELS_BUILD_TYPE_LOCAL_DEFINES + ASYNCRT_PROFILING_LOCAL_DEFINES + select({
        "//:dbg_build": ["BUILD_TYPE=debug"],
        "//:fastbuild_build": ["BUILD_TYPE=relwithdebinfo"],
        "//:opt_build": ["BUILD_TYPE=release"],
    }),
    deps = [
        ":HLCFDialect",
        ":Interpreter",
        ":KGENAttrInterfacesIncGen",
        ":KGENAttrsIncGen",
        ":KGENDialectBytecodeIncGen",
        ":KGENDialectIncGen",
        ":KGENEnumsIncGen",
        ":KGENInterfacesIncGen",
        ":KGENTypeInterfacesIncGen",
        ":Support",
        "//Support:ADT",
        "//Support:DebugInfoDialect",
        "//Support:IPInt",
        "//Support:MDialect",
        "@llvm-project//mlir:Transforms",
    ],
)

modular_versioned_expand_template(
    name = "kgen_version_gen",
    out = "KGENVersion.h",
    substitutions = {},
    template = "include/KGEN/KGENVersion/KGENVersion.h.tmpl",
)

modular_cc_library(
    name = "VersionHeader",
    hdrs = [":kgen_version_gen"],
    include_prefix = "KGEN/KGENVersion",
)

modular_cc_library(
    name = "ToolCommon.headers",
    hdrs = glob(["include/KGEN/ToolCommon/*.h"]),
    visibility = ["//visibility:private"],
    deps = [
        ":KGENPassesIncGen",
        "//Support:CommonCLOptions",
    ],
)

modular_cc_library(
    name = "Compiler.headers",
    hdrs = glob(["include/KGEN/Compiler/*.h"]),
    deps = [
        ":ExecutionEngine.headers",
    ],
)

modular_cc_library(
    name = "Compiler",
    srcs = glob(["lib/Compiler/*.cpp"]),
    hdrs = glob(["include/KGEN/Compiler/*.h"]),
    deps = [
        ":ExecutionEngine.headers",
        ":JIT",
        ":KGENDialect",
        ":KGENDialectIncGen",
        ":KGENInterfacesIncGen",
        ":ObjectCompiler.headers",
        ":Pipeline",
        ":ToolCommon.headers",
        ":TransformUtils",
        ":VersionHeader",
        "//AsyncRT:CompilerSupport",
        "//Support:DebugInfoTransforms",
        "//Support:Telemetry",
        "@llvm-project//llvm:OrcJIT",
    ],
)

cc_distributable_static_library(
    name = "CompilerRT.distributable",
    library_name = "libKGENCompilerRT-static.a",
    visibility = ["//visibility:public"],
    deps = [
        ":CompilerRT.static",
        "//ArraySupport",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals.static",
        "//AsyncRT:Support",
        "//CUDASupport",
        "//CUDASupport:Globals.static",
        "//Config",
        "//Runtime",
        "//Support:ADT",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:Filesystem",
        "//Support:Globals.static",
        "//Support:ML",
        "//Support:Profiling",
        "//Support:Threading",
        "@llvm-project//llvm:Demangle",
        "@llvm-project//llvm:Support",
        "@llvm-project//llvm:TargetParser",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:Support",
    ] + select({
        "@platforms//os:linux": ["@gperftools//:tcmalloc_objects"],
        "//conditions:default": [],
    }) + select({
        "//bazel/internal:profiling_off": [],
        "//conditions:default": [
            "//Support:CPUCache",
            "//Support:DeviceSpecs",
            "//Support:MArchTargetMinimal",
            "@llvm-project//clang:ast",
            "@llvm-project//clang:basic",
            "@llvm-project//clang:lex",
            "@llvm-project//llvm:Analysis",
            "@llvm-project//llvm:AsmParser",
            "@llvm-project//llvm:BinaryFormat",
            "@llvm-project//llvm:BitReader",
            "@llvm-project//llvm:BitstreamReader",
            "@llvm-project//llvm:Core",
            "@llvm-project//llvm:DebugInfoBTF",
            "@llvm-project//llvm:DebugInfoCodeView",
            "@llvm-project//llvm:DebugInfoDWARF",
            "@llvm-project//llvm:DebugInfoMSF",
            "@llvm-project//llvm:DebugInfoPDB",
            "@llvm-project//llvm:FrontendOffloading",
            "@llvm-project//llvm:FrontendOpenMP",
            "@llvm-project//llvm:IRReader",
            "@llvm-project//llvm:MC",
            "@llvm-project//llvm:MCParser",
            "@llvm-project//llvm:Object",
            "@llvm-project//llvm:ProfileData",
            "@llvm-project//llvm:Remarks",
            "@llvm-project//llvm:Scalar",
            "@llvm-project//llvm:Symbolize",
            "@llvm-project//llvm:TextAPI",
            "@llvm-project//llvm:TransformUtils",
        ],
    }),
)

write_file(
    name = "gen_link_test",
    out = "LinkTest.cpp",
    content = ["""
#include "gtest/gtest.h"

extern "C" bool KGEN_CompilerRT_Initialize();

TEST(LinkTest, works) {
    EXPECT_TRUE(KGEN_CompilerRT_Initialize());
}
"""],
)

modular_cc_test(
    name = "CompilerRTLinkTest",
    srcs = [
        "include/KGEN/CompilerRT/Registration.h",
        ":gen_link_test",
    ],
    linkopts = ["-lz"],
    deps = [":CompilerRT.distributable"],
)

modular_shared_library(
    name = "CompilerRT",
    srcs = glob([
        "lib/CompilerRT/*.cpp",
        "lib/CompilerRT/*.h",
    ]),
    hdrs = glob([
        "include/KGEN/CompilerRT/*.h",
    ]),
    local_defines = [
        "MODULAR_BUILDING_COMPILERRT",
    ] + CONFIG_SECTION_LOCAL_DEFINES,
    output_name = "KGENCompilerRTShared",
    deps = [
        "//ArraySupport",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//AsyncRT:Support",
        "//CUDASupport",
        "//CUDASupport:Globals",
        "//Runtime",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:Filesystem",
        "//Support:Globals",
        "//Support:ML",
        "//Support:Profiling",
        "//Support:Threading",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_library(
    name = "Support",
    srcs = glob(["lib/Support/*.cpp"]),
    hdrs = glob(["include/KGEN/KGENDialect/*.h"]) + [
        "include/KGEN/Support/CompilerProfiling.h",
        "include/KGEN/Support/Configuration.h",
        "include/KGEN/Support/DebugInfoEncoding.h",
        "include/KGEN/Support/Debugging.h",
        "include/KGEN/Support/NameMangling.h",
    ],
    local_defines = CONFIG_SECTION_LOCAL_DEFINES,
    deps = [
        "//AsyncRT:Support",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:ML",
        "//Support:Profiling",
        "//Support:Settings",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "SupportForceLinkMLIRC",
    srcs = glob([
        "lib/Support/ForceLinkMLIRC/*.cpp",
        "lib/Support/ForceLinkMLIRC/*.cpp.inc",
    ]),
    hdrs = [
        "include/KGEN/Support/ForceLinkMLIRC.h",
    ],
    deps = [
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:CAPIIR",
        "@llvm-project//mlir:CAPITransforms",
    ],
)

modular_cc_library(
    name = "LowerLIT",
    srcs = glob(["lib/LowerLIT/*.cpp"]),
    deps = [
        ":KGENDialect",
        ":LITDialect",
        ":ToolCommon.headers",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_library(
    name = "KGENToLLVM",
    srcs = glob([
        "lib/KGENToLLVM/*.cpp",
        "lib/KGENToLLVM/*.h",
    ]),
    deps = [
        ":HLCFDialectAnalysis",
        ":KGENDialect",
        ":ToolCommon",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:IndexDialect",
    ],
)

modular_cc_library(
    name = "Transforms",
    srcs = glob(["lib/Transforms/*.cpp"]),
    deps = [
        ":CODialect",
        ":CustomDialect",
        ":HLCFDialect",
        ":HLCFDialectAnalysis",
        ":LITDialect",
        ":POPDialect",
        ":ToolCommon.headers",
        ":TransformUtils",
        "//AsyncRT:Runtime",
        "//Support:DebugInfoDialect",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:CAPIIR",
        "@llvm-project//mlir:CAPITransforms",
        "@llvm-project//mlir:IndexDialect",
        "@llvm-project//mlir:TransformUtils",
    ],
)

modular_cc_library(
    name = "Elaborator",
    srcs = glob([
        "lib/Elaborator/*.cpp",
        "lib/Elaborator/*.h",
    ]),
    deps = [
        ":CustomDialect",
        ":KGENDialect",
        ":LITDialect",
        ":ToolCommon.headers",
        ":VersionHeader",
        "//AsyncRT:CompilerSupport",
        "//Cache",
        "@llvm-project//mlir:IndexDialect",
    ],
)

modular_cc_library(
    name = "Pipeline",
    srcs = glob(["lib/Compiler/Pipeline/*.cpp"]),
    hdrs = glob(["lib/Compiler/Pipeline/*.h"]),
    deps = [
        ":Compiler.headers",
        ":Elaborator",
        ":KGENPassesIncGen",
        ":LowerLIT",
        ":MOGGPreElab",
        ":Transforms",
        "//Support:DebugInfoToLLVM",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:TransformUtils",
    ],
)

modular_cc_library(
    name = "TransformUtils",
    srcs = glob(["lib/TransformUtils/*.cpp"]),
    hdrs = glob(["include/KGEN/TransformUtils/*.h"]),
    deps = [
        ":HLCFDialect",
        ":Support",
        "@llvm-project//llvm:OrcJIT",
        "@llvm-project//mlir:BuiltinToLLVMIRTranslation",
    ],
)

modular_cc_library(
    name = "ObjectCompiler.headers",
    srcs = glob(["lib/Compiler/ObjectCompiler/*.h"]),
    visibility = ["//visibility:private"],
)

modular_cc_library(
    name = "ObjectCompiler",
    srcs = glob([
        "lib/Compiler/ObjectCompiler/*.cpp",
        "lib/Compiler/ObjectCompiler/*.h",
    ]),
    deps = [
        ":Compiler",
        ":KGENToLLVM",
        ":Pipeline",
        "//AsyncRT:CompilerSupport",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)

modular_cc_library(
    name = "MojoParser",
    srcs = glob([
        "lib/MojoParser/*.cpp",
        "lib/MojoParser/*.h",
    ]),
    hdrs = glob([
        "include/KGEN/MojoParser/*.h",
        "include/KGEN/MojoParser/*.def",
    ]),
    deps = [
        ":Compiler",
        ":ToolCommon",
    ],
)

modular_cc_library(
    name = "MojoTooling",
    srcs = glob([
        "lib/MojoTooling/*.cpp",
        "lib/MojoTooling/*.h",
    ]),
    hdrs = glob(["include/KGEN/MojoTooling/*.h"]),
    deps = [
        ":MojoParser",
    ],
)

modular_cc_library(
    name = "MojoTesting",
    srcs = glob(["lib/MojoTesting/*.cpp"]),
    hdrs = glob(["include/KGEN/MojoTesting/*.h"]),
    deps = [
        ":MojoParser",
        ":MojoTooling",
        ":ToolCommon",
        "@llvm-project//mlir:MlirLspServerSupportLib",
    ],
)

modular_cc_library(
    name = "ExecutionEngine.headers",
    hdrs = glob(["include/KGEN/ExecutionEngine/*.h"]),
)

modular_cc_library(
    name = "ExecutionEngine",
    srcs = glob(["lib/ExecutionEngine/*.cpp"]),
    hdrs = glob(["include/KGEN/ExecutionEngine/*.h"]),
    deps = [
        ":JIT",
        ":VersionHeader",
        "//Cache",
        "//Support:Buffer",
        "//Support:Compiler",
        "@llvm-project//llvm:OrcDebugging",
        "@llvm-project//mlir:MlirLspServerSupportLib",
    ],
)

modular_cc_library(
    name = "JIT",
    srcs = glob([
        "lib/ExecutionEngine/JIT/*.cpp",
        "lib/ExecutionEngine/JIT/*.h",
    ]),
    hdrs = glob(["include/KGEN/ExecutionEngine/JIT/*.h"]),
    deps = [
        ":Compiler.headers",
        ":ExecutionEngine.headers",
        ":KGENDialect",
        ":ToolCommon.headers",
        ":VersionHeader",
        "//Cache",
        "//Support:Buffer",
        "@llvm-project//llvm:OrcDebugging",
        "@llvm-project//llvm:OrcJIT",
    ],
)

modular_cc_library(
    name = "ToolCommon",
    srcs = glob(["lib/ToolCommon/**/*.cpp"]),
    hdrs = glob(["include/KGEN/ToolCommon/*.h"]),
    deps = [
        ":CODialect",
        ":CustomDialect",
        ":ExecutionEngine",
        ":HLCFDialect",
        ":KGENPassesIncGen",
        ":LITDialect",
        ":MOGGPreElab",
        ":POPDialect",
        ":ToolCommon.headers",
        "//Cache",
        "//Support:CommonCLOptions",
        "//Support:DebugInfoDialect",
        "//Support:DebugInfoToLLVM",
        "@llvm-project//llvm:OrcJIT",
        "@llvm-project//mlir:BuiltinToLLVMIRTranslation",
        "@llvm-project//mlir:BytecodeWriter",
        "@llvm-project//mlir:ConversionPasses",
        "@llvm-project//mlir:IndexDialect",
        "@llvm-project//mlir:LLVMToLLVMIRTranslation",
        "@llvm-project//mlir:NVVMToLLVMIRTranslation",
    ],
)

genrule(
    name = "gen_exports_file_linux",
    srcs = ["@llvm-project//lldb:source/API/liblldb-private.exports"],
    outs = ["exports_linux.txt"],
    cmd = """
cat > $(OUTS) <<EOF
{
  global:
    $$(sed 's/$$/;/g' $(SRCS))
};
EOF
""",
)

genrule(
    name = "gen_exports_file_macos",
    srcs = ["@llvm-project//lldb:source/API/liblldb-private.exports"],
    outs = ["exports_macos.txt"],
    cmd = "sed 's/^/_/g' $(SRCS) > $(OUTS)",
)

# TODO: Delete once https://github.com/llvm/llvm-project/pull/91549 is in
modular_cc_binary(
    name = "lldb19.0.0git",
    additional_linker_inputs = select({
        "@platforms//os:linux": [
            ":gen_exports_file_linux",
        ],
        "@platforms//os:macos": [
            ":gen_exports_file_macos",
        ],
        "//conditions:default": [],
    }),
    linkopts = select({
        "@platforms//os:linux": [
            "-Wl,--export-dynamic-symbol-list=$(location :gen_exports_file_linux)",
        ],
        "@platforms//os:macos": [
            "-Wl,-exported_symbols_list,$(location :gen_exports_file_macos)",
        ],
        "//conditions:default": [],
    }),
    linkshared = True,
    deps = [
        "@llvm-project//lldb:API",
        "@llvm-project//lldb:Interpreter",
    ],
)

cc_import(
    name = "liblldb.wrapper",
    shared_library = "lldb19.0.0git",
    visibility = [":__subpackages__"],
)

# TODO: Remove once https://github.com/llvm/llvm-project/pull/91789 is in
apple_genrule(
    name = "debugserver_signed",
    srcs = ["@llvm-project//lldb:debugserver"],
    outs = ["debugserver"],
    cmd = "cp $(SRCS) $(OUTS) && xcrun codesign -f -s - --entitlements $(location //:third-party/llvm-project/lldb/tools/debugserver/resources/debugserver-macosx-entitlements.plist) $(OUTS)",
    target_compatible_with = select({
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    tools = [
        "//:third-party/llvm-project/lldb/tools/debugserver/resources/debugserver-macosx-entitlements.plist",
    ],
)

# TODO: Remove once https://github.com/llvm/llvm-project/pull/91789 is in
alias(
    name = "gdb-server",
    actual = select({
        "@platforms//os:macos": ":debugserver",
        "//conditions:default": "@llvm-project//lldb:lldb-server",
    }),
    visibility = ["//visibility:public"],
)

# TODO: Replace with copy_file when https://github.com/llvm/llvm-project/pull/91549 is in
modular_cc_binary(
    name = "mojo-lldb",
    srcs = [
        "//:third-party/llvm-project/lldb/tools/driver/Driver.cpp",
        "//:third-party/llvm-project/lldb/tools/driver/Driver.h",
        "//:third-party/llvm-project/lldb/tools/driver/Platform.cpp",
        "//:third-party/llvm-project/lldb/tools/driver/Platform.h",
    ],
    deps = [
        ":liblldb.wrapper",
        ":lldb19.0.0git",
        "@llvm-project//lldb:lldb_options_inc_gen",
        "@llvm-project//llvm:Option",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_library(
    name = "MojoLLDBPublicHeaders",
    hdrs = glob(["include/KGEN/MojoLLDB/*.h"]),
)

modular_shared_library(
    name = "MojoLLDB",
    srcs = glob(["lib/MojoLLDB/**/*.cpp"]),
    hdrs = glob(["lib/MojoLLDB/**/*.h"]),
    copts = [
        "-fvisibility=default",
        "-iquoteexternal/",
    ],
    local_defines = [
        "MODULAR_BUILDING_LIBRARY",
    ],
    strip_include_prefix = None,
    deps = [
        ":ExecutionEngine",
        ":KGENDialect",
        ":MojoLLDBPublicHeaders",
        ":MojoTooling",
        ":ObjectCompiler",
        ":TransformUtils",
        ":liblldb.wrapper",
        ":lldb19.0.0git",
        "//AsyncRT:Init",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Base",
        "//Support:CrashReporting",
        "//Support:Globals",
        "@llvm-project//llvm:ExecutionEngine",
        "@llvm-project//llvm:MCJIT",
    ],
)

genrule(
    name = "gen_maptlotlib_initialization_script",
    outs = ["gen_maptlotlib_initialization_tool.py"],
    cmd = """
cat > $(OUTS) <<EOF
import sys

print(
    open(sys.argv[1]).read()
    .replace("@ENABLE_MATPLOTLIB_STR@", open(sys.argv[2]).read())
    .replace("@MATPLOTLIB_BACKEND_STR@", open(sys.argv[3]).read())
)
EOF
""",
)

py_binary(
    name = "gen_maptlotlib_initialization_tool",
    srcs = [":gen_maptlotlib_initialization_script"],
)

genrule(
    name = "gen_maptlotlib_initialization",
    srcs = [
        "lib/MojoJupyter/MatplotlibInitialization.h.in",
        "lib/MojoJupyter/matplotlib_backend.py",
        "lib/MojoJupyter/enable_matplotlib.py",
    ],
    outs = ["MojoJupyter/MatplotlibInitialization.h"],
    cmd = """
$(location :gen_maptlotlib_initialization_tool) \
    $(location :lib/MojoJupyter/MatplotlibInitialization.h.in) \
    $(location :lib/MojoJupyter/enable_matplotlib.py) \
    $(location :lib/MojoJupyter/matplotlib_backend.py) > $(OUTS)
""",
    tools = [":gen_maptlotlib_initialization_tool"],
)

modular_shared_library(
    name = "MojoJupyter",
    srcs = glob(["lib/MojoJupyter/*.cpp"]) + [":gen_maptlotlib_initialization"],
    hdrs = glob([
        "include/KGEN/MojoJupyter/*.h",
    ]),
    copts = [
        "-fvisibility=default",
        "-iquoteexternal/",
    ],
    local_defines = [
        "MODULAR_BUILDING_JUPYTER_LIBRARY",
    ],
    deps = [
        ":KGENDialect",
        ":MojoLLDB",
        ":MojoLLDBPublicHeaders",
        ":MojoTooling",
        ":liblldb.wrapper",
        ":lldb19.0.0git",
    ],
)

pkg_filegroup(
    name = "jupyter-mojo",
    srcs = [
        ":jupyter-manage-kernel",
        ":jupyter-mojo-kernel",
    ],
    visibility = ["//visibility:public"],
)

pkg_files(
    name = "jupyter-manage-kernel",
    srcs = [
        ":utils/jupyter-mojo/manage_kernel.py",
    ],
)

pkg_files(
    name = "jupyter-mojo-kernel",
    srcs = glob([
        "utils/jupyter-mojo/kernel/*",
    ]),
    prefix = "kernel",
)
