# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #

import argparse
import os
import re
import sys


def token_hash(file: str, line: int, token: str):
    # FNV-1a hash function for 64-bit hash computation
    hash_value = 0xCBF29CE484222325

    def hash(value) -> None:  # noqa: ANN001
        nonlocal hash_value
        hash_value ^= value
        hash_value *= 0x100000001B3
        hash_value &= 0xFFFFFFFFFFFFFFFF

    hash(line)
    for char in file:
        hash(ord(char))
    for char in token:
        hash(ord(char))

    return hash_value


token_hash_pattern = r"(?P<token_hash>MOTR_TOKEN_HASH)(?P<not_open_paren>[^\(]*)(?P<open_paren>\(?)(?P<not_quote>[^\"]*)(?P<quote>\")?(?P<string>[^\"\n]*)?(?P<close_quote>\")?(?P<not_close_paren>[^\)]*)(?P<close_paren>\))?"


def find_token_hashes(line: str, path: str, line_number: int):
    matches = re.finditer(token_hash_pattern, line)
    results = []

    def error(msg, g) -> None:  # noqa: ANN001
        token = g["token_hash"]
        fullmatch = g["fullmatch"]
        sys.stderr.write(f"\n{path}:{line_number}\n")
        sys.stderr.write(f" > ERROR: Found {token} {msg}\n")
        sys.stderr.write(f" > {fullmatch}\n")

    for m in matches:
        # Check for the presence of required groups
        # sys.stderr.write(f"match: {m}\n")
        g = m.groupdict()
        fullmatch = m.group(0)
        g["fullmatch"] = fullmatch
        # sys.stderr.write(f"{g=}\n")
        if g["not_open_paren"]:
            error(
                "without open parenthesis immediately after MOTR_TOKEN_HASH", g
            )
        elif g["not_quote"]:
            error("without quote immediately after MOTR_TOKEN_HASH(", g)
        elif g["not_close_paren"]:
            error(
                'without close parenthesis immediately after MOTR_TOKEN_HASH("...',
                g,
            )
        elif (
            g["open_paren"]
            and g["close_paren"]
            and g["quote"]
            and g["close_quote"]
        ):
            results.append(g["string"])
        else:
            error("without proper formatting", g)

    return results


# Function to extract MOTR_TOKEN_HASH calls from a file
def extract_token_hashes(full_file_path, repo_root):  # noqa: ANN001
    hashes = {}

    assert full_file_path.startswith(repo_root), (
        f"{full_file_path} does not start with {repo_root}"
    )
    file = full_file_path[len(repo_root) :]

    with open(full_file_path) as open_file:
        for line_number, line in enumerate(open_file, start=1):
            matches = find_token_hashes(line, file, line_number)
            for str in matches:
                hash_value = token_hash(file, line_number, str)
                hashes[hash_value] = (str, file, line_number)

    return hashes


# Function to generate the reverse mapping .cpp file
def generate_reverse_mapping_text(hashes, repo_root):  # noqa: ANN001
    text = ""
    newline = "\n"
    i = 0

    def emit(new_text="") -> None:  # noqa: ANN001
        nonlocal text
        nonlocal i
        indent = "  " * i
        text += f"{indent}{new_text}{newline}"

    emit("//")
    emit("// This file is generated by motr_gen_hash_to_token_map.py")
    emit(
        "// It is used to map a hash value to a token string and file:line location."
    )
    emit("// The hash value is computed using the FNV-1a hash function.")
    emit("//")
    emit("#include <cstdint>")
    emit("#include <unordered_map>")
    emit("#include <string>")
    emit("")
    emit("namespace M::motr {")
    emit("")
    emit("struct TokenInfo {")
    i = 1
    emit("uint64_t hash;")
    emit("std::string file;")
    emit("int line;")
    emit("std::string token;")
    i = 0
    emit("};")
    emit()
    emit("using TokenHashTable = std::unordered_map<uint64_t, TokenInfo>;")
    emit()
    emit("struct TokenHashes {")
    i = 1
    emit("std::string repo_root;")
    emit("TokenHashTable table;")
    i = 0
    emit("};")
    emit()

    emit("TokenHashTable genTokenHashTable() {")
    i = 1
    emit("return {")
    newline = ""
    for hash_value, (token_string, file_path, line_number) in hashes.items():
        hash_str = f"0x{hash_value:016x}"
        i = 2
        emit(f"{{ {hash_str}, {{ {hash_str}, ")
        i = 0
        emit(f'"{file_path}", ')
        emit(f"{line_number:5d}, ")
        emit(f'"{token_string}"')
        emit("}},")
        emit("\n")
    newline = "\n"
    i = 1
    emit("};")
    i = 0
    emit("}")
    emit()
    emit("TokenHashes genTokenHashes() {")
    i = 1
    emit("return {")
    i = 2
    emit(f'"{repo_root}",')
    emit("genTokenHashTable()")
    i = 1
    emit("};")
    i = 0
    emit("}")
    emit()

    emit("} // namespace M::motr::detail")

    emit()
    emit("#ifdef MOTR_ENABLE_TEST")
    emit("#include <cstdio>")
    emit("int main() {")
    emit("    const auto& hashes = M::motr::genTokenHashes();")
    emit("    for(auto [_, info] : hashes.table) {")
    emit(
        '        printf("[%016llX] \\"%s\\": %s%s:%d\\n", (unsigned long long)info.hash, info.token.c_str(), hashes.repo_root.c_str(), info.file.c_str(), info.line);'
    )
    emit("    }")
    emit("    return 0;")
    emit("}")
    emit("#endif // MOTR_ENABLE_TEST")

    return text


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compute MOTR_TOKEN_HASH values and generate reverse mapping."
    )
    parser.add_argument(
        "--repo-root", required=True, help="The repository root string."
    )
    parser.add_argument("files", nargs="+", help="List of files to process.")
    args = parser.parse_args()

    all_hashes = {}

    for file_path in args.files:
        if os.path.isfile(file_path):
            hashes = extract_token_hashes(file_path, args.repo_root)
            all_hashes.update(hashes)
        else:
            print(f"File not found: {file_path}")

    text = generate_reverse_mapping_text(all_hashes, args.repo_root)
    print(text)

    # with open(output_file, 'w') as file:
    #     file.write(text)


if __name__ == "__main__":
    main()
