load("//bazel:api.bzl", "modular_cc_binary")

package(
    default_visibility = ["//MLRT:__subpackages__"],
    features = [
        "layering_check",
        "parse_headers",
    ],
)

modular_cc_binary(
    name = "crash-report-path-info",
    srcs = glob(["*.cpp"]),
    deps = [
        "//Init",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//Support:Base",
        "//Support:Configuration",
        "//Support:CrashReporting",
        "//Support:Globals",
        "@llvm-project//llvm:Support",
    ],
)
