[project]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Add a short description here"
name = "max-graph-api"
platforms = ["osx-arm64", "linux-64"]
version = "0.0.0"

[tasks]
mnist = "python mnist.py"
test = { depends-on = ["mnist"] }

[dependencies]
max = "*"
pytorch = ">=2.5.0,<=2.7.0"
torchvision = ">=0.19.0,<0.22"
numpy = "*"
