//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file defines options for the `greeter-cli bye` subcommand.
// `bye` only takes common options such as `--help`, so this file is mostly
// empty.
//
//===----------------------------------------------------------------------===//

include "Bye/ByeDescription.td"
include "Support/Driver/CommonOptions.td"
