//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This is the top level file for the POP dialect.
//
//===----------------------------------------------------------------------===//

#ifndef KGEN_POPDIALECT_POP_TD
#define KGEN_POPDIALECT_POP_TD

include "KGEN/POPDialect/POPAttrs.td"
include "KGEN/POPDialect/POPOps.td"
include "KGEN/POPDialect/POPTypes.td"

#endif // KGEN_POPDIALECT_POP_TD
