//===- POP.td -------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This is the top level file for the POP dialect.
//
//===----------------------------------------------------------------------===//

#ifndef POP_TD
#define POP_TD

include "KGEN/POPDialect/POPAttrs.td"
include "KGEN/POPDialect/POPOps.td"
include "KGEN/POPDialect/POPTypes.td"

#endif // POP_TD
