load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "mojo-test-executor",
    srcs = glob(
        ["**/*.mojo"],
    ),
    mojo_deps = [
        "//open-source/max/mojo/stdlib/stdlib",
    ],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/mojo",
        "//KGEN/tools/mojo-test-executor",
    ],
)
