load("//utils/bazel/build/rules:lit.bzl", "lit_tests")

lit_tests(
    name = "mojo-test-executor",
    srcs = glob(
        ["**/*.mojo"],
    ),
    data = [
        "//KGEN:MojoLLDB",
        "//KGEN:gdb-server",
        "//KGEN/tools/mojo-repl-entry-point",
    ],
    env = {
        "LLDB_DEBUGSERVER_PATH": "$(location //KGEN:gdb-server)",
        "MODULAR_CRASH_REPORTING_ENABLED": "false",
        "MODULAR_MOJO_LLDB_PLUGIN_PATH": "$(location //KGEN:MojoLLDB)",
        "MODULAR_MOJO_REPL_ENTRY_POINT": "$(location //KGEN/tools/mojo-repl-entry-point)",
    },
    mojo_deps = [
        "//open-source/mojo/stdlib/stdlib:stdlib",
    ],
    tools = [
        "//KGEN/tools/mojo-test-executor",
    ],
)
