//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#ifndef DEBUGINFO_TD
#define DEBUGINFO_TD

include "Support/DebugInfoDialect/IR/DebugInfoAttrs.td"
include "Support/DebugInfoDialect/IR/DebugInfoEnums.td"
include "Support/DebugInfoDialect/IR/DebugInfoExprAttrs.td"
include "Support/DebugInfoDialect/IR/DebugInfoOps.td"
include "Support/DebugInfoDialect/IR/DebugInfoTypes.td"

#endif // DEBUGINFO_TD
