load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "mojo-jupyter-executor",
    srcs = ["main.cpp"],
    deps = [
        "//AsyncRT:Init",
        "//AsyncRT:RuntimeGlobals",
        "//KGEN:ExecutionEngine",
        "//KGEN:MojoJupyter",
        "//KGEN:MojoLLDB",
        "//KGEN:MojoLLDBPublicHeaders",
        "//KGEN:liblldb.wrapper",
        "//Support:Globals",
    ],
)
