load("//bazel:api.bzl", "modular_cc_binary", "modular_cc_test")

modular_cc_test(
    name = "QueueBenchmark",
    srcs = ["QueueBenchmark.cpp"],
    deps = [
        "//AsyncRT:Support",
        "@google_benchmark//:benchmark_main",
    ],
)

modular_cc_binary(
    name = "bench_gpu_kernel_enqueue_cuda",
    srcs = [
        "bench_gpu_kernel_enqueue_cuda.cpp",
        "cuda_common.h",
    ],
    target_compatible_with = ["//:nvidia_gpu"],
    deps = [
        "//Support:MicroBenchmark",
    ],
)
