//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
// This file is autogenerated, DO NOT EDIT
//===----------------------------------------------------------------------===//

#ifndef SUPPORT_PLATFORMLIBNAMES_H
#define SUPPORT_PLATFORMLIBNAMES_H

#include "llvm/Support/ErrorHandling.h"
#include <string>

namespace M {
struct PlatformLibrary {

  static std::string getSharedLibraryName(llvm::StringRef name);

  static std::string getStaticLibraryName(llvm::StringRef name);
};
} // namespace M

#endif // SUPPORT_PLATFORMLIBNAMES_H
