load("//bazel:api.bzl", "modular_cc_test")

# gazelle:default_visibility //visibility:private

package(
    default_visibility = ["//visibility:private"],
    features = [
        "layering_check",
        "parse_headers",
    ],
)

modular_cc_test(
    name = "ADTTest",
    srcs = glob(["ADT/*.cpp"]),
    deps = [
        "//Support:ADT",
        "//Support:Base",
        "//Support:Globals",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_test(
    name = "BaseTest",
    srcs = [
        "AlignedAllocTest.cpp",
        "AssertStreamTest.cpp",
        "ErrorOrTest.cpp",
        "ErrorTest.cpp",
        "FunctionExtrasTest.cpp",
        "MathExtras.cpp",
        "ProcessTest.cpp",
        "RandomTest.cpp",
        "StringExtrasTest.cpp",
        "ThreadingTest.cpp",
    ],
    deps = [
        "//Support:Base",
        "//Support:Buffer",
        "//Support:Threading",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "LogTest",
    srcs = [
        "Log/LogTest.cpp",
    ],
    deps = [
        "//Support:Log",
        "@llvm-project//llvm:Support",
    ],
)

# Separate test because of global log file state
modular_cc_test(
    name = "LogConfigFileTest",
    srcs = [
        "Log/LogConfigFileTest.cpp",
    ],
    deps = [
        "//Support:Configuration",
        "//Support:Log",
        "@llvm-project//llvm:Support",
    ],
)

# Separate test because of global log file state
modular_cc_test(
    name = "LogJSONOutputTest",
    srcs = [
        "Log/LogJSONOutputTest.cpp",
    ],
    env = {
        "MODULAR_LOG_JSON": "true",
        "MODULAR_LOG_LEVEL": "DEBUG",
    },
    deps = [
        "//Support:Configuration",
        "//Support:Log",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "HashUtilsTest",
    srcs = ["HashUtilsTest.cpp"],
    deps = [
        "//Support:HashUtils",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_test(
    name = "IPIntTest",
    srcs = ["IPIntTest.cpp"],
    deps = [
        "//Support:IPInt",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "IPRationalTest",
    srcs = ["IPRationalTest.cpp"],
    deps = ["//Support:IPRational"],
)

modular_cc_test(
    name = "BufferTest",
    srcs = ["BufferTest.cpp"],
    deps = [
        "//Support:Buffer",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:Support",
    ],
)

modular_cc_test(
    name = "Base64Test",
    srcs = ["Base64Test.cpp"],
    deps = [
        "//Support:Base64",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "CompilerTest",
    srcs = glob(["Compiler/*.cpp"]),
    deps = [
        "//Support:Compiler",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_test(
    name = "ConfigurationTest",
    srcs = ["ConfigurationTest.cpp"],
    deps = [
        "//Support:Configuration",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "ContextTest",
    srcs = ["ContextTest.cpp"],
    deps = [
        "//Support:Context",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "DebugInfoDialectTest",
    srcs = glob(["DebugInfoDialect/*.cpp"]),
    deps = [
        "//Support:Base",
        "//Support:DebugInfoDialect",
        "//Support:DebugInfoToLLVM",
        "//Support:DebugInfoTransforms",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:Parser",
    ],
)

modular_cc_test(
    name = "DeviceSpecsTest",
    srcs = ["DeviceSpecsTest.cpp"],
    deps = ["//Support:DeviceSpecs"],
)

modular_cc_test(
    name = "MicroBenchmarkTest",
    srcs = ["MicroBenchmarkTest.cpp"],
    deps = [
        "//Support:MicroBenchmark",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "FilesystemTest",
    srcs = ["FileSystemExtrasTest.cpp"],
    deps = [
        "//Support:Base",
        "//Support:Buffer",
        "//Support:Filesystem",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "URITest",
    srcs = ["URITest.cpp"],
    deps = ["//Support:URI"],
)

modular_cc_test(
    name = "MLTest",
    srcs = [
        "DTypeTest.cpp",
        "TensorShapeTest.cpp",
        "TensorSpecTest.cpp",
    ],
    deps = [
        "//Support:Base",
        "//Support:ML",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
    ],
)

modular_cc_test(
    name = "HostTest",
    srcs = ["HostTest.cpp"],
    deps = [
        "//Support:MArchTarget",
        "//Support:MArchTargetMinimal",
        "//Support:Threading",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "ProfilingTest",
    srcs = ["TimeProfilerTest.cpp"],
    deps = [
        "//Support:Globals",
        "//Support:Profiling",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "MArchTargetTest",
    srcs = glob(["MArchTarget/*.cpp"]),
    deps = [
        "//Support:Base",
        "//Support:Globals",
        "//Support:MArchTarget",
        "//Support:MDialect",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "TelemetryTest",
    srcs = ["TelemetryTest.cpp"],
    env = {"MODULAR_TELEMETRY_ENABLED": "true"},
    deps = [
        "//Support:Base",
        "//Support:Configuration",
        "//Support:Filesystem",
        "//Support:Telemetry",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "FillTest",
    srcs = ["ML/FillTest.cpp"],
    deps = [
        "//Support:ML",
        "@llvm-project//llvm:Support",
    ],
)

modular_cc_test(
    name = "PermutationTest",
    srcs = ["ML/Permutation.cpp"],
    deps = ["//Support:ML"],
)

modular_cc_test(
    name = "DiagnosticsTests",
    srcs = glob(["Diagnostics/*.cpp"]),
    deps = ["//Support:Diagnostics"],
)
