load("//bazel:api.bzl", "modular_cc_test")

modular_cc_test(
    name = "ASN1Test",
    srcs = ["ASN1Test.cpp"],
    deps = ["//Support:ASN1"],
)

modular_cc_test(
    name = "ADTTest",
    srcs = glob(["ADT/*.cpp"]),
    deps = [
        "//Support:ADT",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "BaseTest",
    srcs = [
        "AlignedAllocTest.cpp",
        "AssertStreamTest.cpp",
        "BufferTest.cpp",
        "ErrorOrTest.cpp",
        "ErrorTest.cpp",
        "FunctionExtrasTest.cpp",
        "MathExtras.cpp",
        "RandomTest.cpp",
        "VersionTest.cpp",
    ],
    deps = [
        "//Support:Base",
        "//Support:Buffer",
    ],
)

modular_cc_test(
    name = "IPIntTest",
    srcs = ["IPIntTest.cpp"],
    deps = ["//Support:IPInt"],
)

modular_cc_test(
    name = "IPRationalTest",
    srcs = ["IPRationalTest.cpp"],
    deps = ["//Support:IPRational"],
)

modular_cc_test(
    name = "BufferTest",
    srcs = ["BufferTest.cpp"],
    deps = ["//Support:Buffer"],
)

modular_cc_test(
    name = "Base64Test",
    srcs = ["Base64Test.cpp"],
    deps = ["//Support:Base64"],
)

modular_cc_test(
    name = "CompilerTest",
    srcs = glob(["Compiler/*.cpp"]),
    deps = [
        "//LLCL:CompilerSupport",
        "//Support:Compiler",
    ],
)

modular_cc_test(
    name = "ConfigurationTest",
    srcs = ["ConfigurationTest.cpp"],
    deps = ["//Support:Configuration"],
)

modular_cc_test(
    name = "ContextTest",
    srcs = ["ContextTest.cpp"],
    deps = [
        "//Support:ADT",
        "//Support:Base",
        "//Support:Globals",
    ],
)

modular_cc_test(
    name = "CryptographyTest",
    srcs = glob(["Cryptography/*.cpp"]),
    deps = ["//Support:Cryptography"],
)

modular_cc_test(
    name = "DebugInfoDialectTest",
    srcs = glob(["DebugInfoDialect/*.cpp"]),
    deps = [
        "//LLCL:CompilerSupport",
        "//Support:DebugInfoDialect",
        "//Support:DebugInfoToLLVM",
        "//Support:DebugInfoTransforms",
    ],
)

modular_cc_test(
    name = "DeviceSpecsTest",
    srcs = ["DeviceSpecsTest.cpp"],
    deps = ["//Support:DeviceSpecs"],
)

modular_cc_test(
    name = "EntitlementsTest",
    srcs = ["//Support:CertificatesHeader"] + glob(["Entitlements/*.cpp"]),
    copts = ["-I$(GENDIR)/Support"],
    deps = ["//Support:Entitlements"],
)

modular_cc_test(
    name = "HMACTest",
    srcs = ["HMACTest.cpp"],
    deps = ["//Support:HMAC"],
)

modular_cc_test(
    name = "MicroBenchmarkTest",
    srcs = ["MicroBenchmarkTest.cpp"],
    deps = ["//Support:MicroBenchmark"],
)

modular_cc_test(
    name = "FilesystemTest",
    srcs = ["FileSystemExtrasTest.cpp"],
    deps = [
        "//Support:Buffer",
        "//Support:Filesystem",
    ],
)

modular_cc_test(
    name = "URITest",
    srcs = ["URITest.cpp"],
    deps = ["//Support:URI"],
)

modular_cc_test(
    name = "JSONTest",
    srcs = ["JSONTest.cpp"],
    deps = ["//Support:JSON"],
)

modular_cc_test(
    name = "HTTPTest",
    srcs = glob(["HTTP/*.cpp"]),
    deps = ["//Support:HTTP"],
)

modular_cc_test(
    name = "MLTest",
    srcs = [
        "BCastTest.cpp",
        "DTypeTest.cpp",
        "TensorShapeTest.cpp",
        "TensorSpecTest.cpp",
    ],
    deps = ["//Support:ML"],
)

modular_cc_test(
    name = "HostTest",
    srcs = ["HostTest.cpp"],
    deps = [
        "//LLCL:CompilerSupport",
        "//Support:MArchTarget",
        "//Support:Threading",
    ],
)

modular_cc_test(
    name = "ProfilingTest",
    srcs = ["TimeProfilerTest.cpp"],
    deps = [
        "//Support:Globals",
        "//Support:Profiling",
    ],
)

modular_cc_test(
    name = "MArchTargetTest",
    srcs = glob(["MArchTarget/*.cpp"]),
    deps = [
        "//LLCL:CompilerSupport",
        "//LLCL:RuntimeGlobals",
        "//Support:Globals",
        "//Support:MArchTarget",
    ],
)

modular_cc_test(
    name = "TelemetryTest",
    srcs = ["TelemetryTest.cpp"],
    deps = ["//Support:Telemetry"],
)

modular_cc_test(
    name = "FillTest",
    srcs = ["ML/FillTest.cpp"],
    deps = ["//Support:ML"],
)

modular_cc_test(
    name = "PermutationTest",
    srcs = ["ML/Permutation.cpp"],
    deps = ["//Support:ML"],
)

modular_cc_test(
    name = "MeteringTests",
    srcs = glob(["Metering/*.cpp"]),
    deps = ["//Support:Metering"],
)
