load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "llvm-module-split",
    srcs = glob(["*.cpp"]),
    deps = [
        "//Config",
        "//KGEN:Compiler",
        "//KGEN:ObjectCompiler",
        "//KGEN:ToolCommon",
        "//LLCL:Runtime",
        "//Support:Base",
        "@llvm-project//llvm:Support",
    ],
)
