load("//utils/bazel/build/rules:lit.bzl", "lit_tests")

lit_tests(
    name = "test",
    size = "large",
    srcs = glob([
        "*.lldb",
        "*.mojo",
    ]),
    custom_substitutions = {
        # Mirrored from lit.cfg.py to avoid searching $PATH for 'mojo'
        "%debug": "$(rlocationpath //KGEN/tools/mojo) debug -Xlldb -x -Xlldb --source-quietly -Xlldb -S -Xlldb ../../../utils/lit-lldb-init.in",
    },
    data = glob(["Inputs/*.mojo"]) + [
        "//KGEN:CompilerRT",
        "//KGEN:CompilerRT.distributable",
        "//KGEN:MojoLLDB",
        "//KGEN:gdb-server",
        "//KGEN:mojo-lldb",
        "//utils:lit-lldb-init.in",
        "@llvm-project//compiler-rt:orc_rt",
        "@llvm-project//lldb:lldb-argdumper",
    ],
    env = {
        "LLDB_DEBUGSERVER_PATH": "$(location //KGEN:gdb-server)",
        "LLDB_ARGDUMPER_PATH": "$(location @llvm-project//lldb:lldb-argdumper)",
        "MODULAR_MOJO_COMPILERRT_PATH": "$(location //KGEN:CompilerRT)",
        "MODULAR_MOJO_COMPILERRT_STATIC_PATH": "$(location //KGEN:CompilerRT.distributable)",
        "MODULAR_MOJO_DRIVER_PATH": "$(location //KGEN/tools/mojo)",
        "MODULAR_MOJO_LLDB_PATH": "$(location //KGEN:mojo-lldb)",
        "MODULAR_MOJO_LLDB_PLUGIN_PATH": "$(location //KGEN:MojoLLDB)",
        "MODULAR_MOJO_ORCRT_PATH": "$(location @llvm-project//compiler-rt:orc_rt)",
    },
    exec_properties = {
        "test.EstimatedComputeUnits": "10",
    },
    mojo_deps = [
        "//open-source/mojo/stdlib/stdlib:stdlib",
    ],
    target_compatible_with = select({
        "//:asan": ["@platforms//:incompatible"],  # __jit_debug_descriptor exists in liblldb and libMojoLLDB
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/mojo",
    ],
)
