load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "kgen",
    srcs = glob(["**/*.mlir"]),
    data = [
        "//KGEN:CompilerRT",
        "@llvm-project//compiler-rt:orc_rt",
    ],
    env = {
        "MODULAR_MOJO_ORCRT_PATH": "$(location @llvm-project//compiler-rt:orc_rt)",
        "MODULAR_MOJO_COMPILERRT_PATH": "$(location //KGEN:CompilerRT)",
    },
    tools = [
        "//KGEN/tools/hash-mlir",
        "//KGEN/tools/kgen",
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/kgen-translate",
        "//KGEN/tools/llvm-module-split",
        "@llvm-project//llvm:llvm-objdump",
    ],
)
