// RUN: kgen-opt %s -allow-unregistered-dialect -outline-closures | kgen-opt -allow-unregistered-dialect | FileCheck %s

// COM: This shouldn't change at all, save for whatever canonicalizations happen at parse time.
// CHECK-LABEL: @call_region<fn: <index -> index>() -> index -> E>() -> index
kgen.generator @call_region<fn: <index -> index>() ->index -> E>() -> index {
  // CHECK-NEXT: kgen.param.declare BoundFn: <[] -> index>() -> index = <bind_signature(:<index -> index>() -> index fn, 2)>
  kgen.param.declare BoundFn: <[] -> index>() -> index = <bind_signature(:<index -> index>() -> index fn, 2)>
  // CHECK-NEXT: %0 = kgen.call_param[<[] -> index>() -> index: BoundFn]<() -> Result>()
  %0 = kgen.call_param[<[] -> index>() -> index: BoundFn]<() -> Result>()
  // CHECK-NEXT: kgen.param.result_bind<Result>
  kgen.param.result_bind<Result>
  // CHECK-NEXT: kgen.return %0 : index
  kgen.return %0 : index
}

// COM: This is the region hoisted out into a generator.
// COM: This is the wrapper that loads values from the global variable.
// CHECK-LABEL: kgen.generator @raiseClosure_Fn<Jefffffffffff, C, A, B -> E>() capturing -> index
// CHECK-NEXT:   [[PTR:%[0-9]+]] = pop.compiler.global_load "raiseClosure_context_var_0" : !pop.struct<index, scalar<index>>
// CHECK-NEXT:   [[ARG0:%[0-9]+]] = pop.struct.extract [[PTR]][0] : !pop.struct<index, scalar<index>>
// CHECK-NEXT:   [[ARG1:%[0-9]+]] = pop.struct.extract [[PTR]][1] : !pop.struct<index, scalar<index>>
// CHECK-NEXT:   [[CST:%.*]] = kgen.param.constant = <add(mul(B, Jefffffffffff, -1), mul(A, Jefffffffffff), mul(C, Jefffffffffff))>
// CHECK-NEXT:   [[CASTCST:%[0-9]+]] = pop.cast_from_builtin [[CST]] : index to !pop.scalar<index>
// CHECK-NEXT:   [[CASTARG:%[0-9]+]] = pop.cast_from_builtin [[ARG0]] : index to !pop.scalar<index>
// CHECK-NEXT:   [[ADD:%[0-9]+]] = pop.add [[CASTCST]], [[CASTARG]] : !pop.scalar<index>
// CHECK-NEXT:   [[RES:%[0-9]+]] = pop.add [[ADD]], [[ARG1]] : !pop.scalar<index>
// CHECK-NEXT:   [[RESULT:%[0-9]+]] = pop.cast_to_builtin [[RES]] : !pop.scalar<index> to index
// CHECK-NEXT:   kgen.param.result_bind<add(mul(A, -1), C)>
// CHECK-NEXT:   kgen.return [[RESULT]]

// CHECK-LABEL: kgen.generator @raiseClosure
kgen.generator @raiseClosure<Jefffffffffff -> index>(%arg0: !pop.scalar<index>) -> (index, index) {
  %cst = index.constant 0
  kgen.param.declare C = <15>
  kgen.param.declare.region Fn = <A, B -> E>() capturing -> index {
    %0 = kgen.param.constant = <mul(add(sub(A, B), C), Jefffffffffff)>
    %1 = pop.cast_from_builtin %0 : index to !pop.scalar<index>
    %2 = pop.cast_from_builtin %cst : index to !pop.scalar<index>
    %3 = pop.add %1, %2 : !pop.scalar<index>
    %4 = pop.add %3, %arg0 : !pop.scalar<index>
    %5 = pop.cast_to_builtin %4 : !pop.scalar<index> to index
    kgen.param.result_bind<sub(C, A)>
    kgen.return %5 : index
  }
  // CHECK: [[STRUCT:%[0-9]+]] = pop.struct.create(%idx0, %arg0) : !pop.struct<index, scalar<index>>
  // CHECK-NEXT: pop.compiler.global_store "raiseClosure_context_var_0", [[STRUCT]] : !pop.struct<index, scalar<index>>
  // CHECK: kgen.param.declare Fn: <index, index -> index>() capturing -> index = <@raiseClosure_Fn<Jefffffffffff, C, #kgen.unbound, #kgen.unbound>>
  // CHECK: kgen.param.declare BoundFn: <index -> index>() capturing -> index = <bind_signature(:<index, index -> index>() capturing -> index Fn, #kgen.unbound, 1)>
  kgen.param.declare BoundFn: <index -> index>() capturing -> index = <bind_signature(:<index, index -> index>() capturing -> index Fn, #kgen.unbound, 1)>
  // CHECK: kgen.call @call_region<:<index -> index>() -> index BoundFn -> Result>() : () -> index
  %0 = kgen.call @call_region<:<index -> index>() ->index BoundFn -> Result>() : () -> index
  %1 = kgen.param.constant = <Result>
  // CHECK: kgen.param.result_bind<Result>
  kgen.param.result_bind<Result>
  kgen.return %0, %1 : index, index
}

// CHECK-LABEL: kgen.generator @raise2Closures_Empty()
// CHECK-NEXT:    kgen.return

// CHECK-LABEL: kgen.generator @raise2Closures_Fn<C, A -> E>() capturing -> index
// CHECK-NEXT:    %[[PTR:.*]] = pop.compiler.global_load "raise2Closures_context_var_1" : !pop.struct<index>
// CHECK-NEXT:    %[[ARG0:.*]] = pop.struct.extract %[[PTR]][0] :
// CHECK-NEXT:    %[[V0:.*]] = kgen.param.constant = <add(A, C)>
// CHECK-NEXT:    %[[V1:.*]] = pop.cast_from_builtin %[[V0]] : index to !pop.scalar<index>
// CHECK-NEXT:    %[[V2:.*]] = pop.cast_from_builtin %[[ARG0]] : index to !pop.scalar<index>
// CHECK-NEXT:    %[[V3:.*]] = pop.add %[[V1]], %[[V2]] : !pop.scalar<index>
// CHECK-NEXT:    %[[V4:.*]] = pop.cast_to_builtin %[[V3]] : !pop.scalar<index> to index
// CHECK-NEXT:    kgen.param.result_bind<add(mul(A, -1), C)>
// CHECK-NEXT:    kgen.return %[[V4]] : index


// CHECK-LABEL: kgen.generator @raise2Closures
kgen.generator @raise2Closures() {
  %cst = index.constant 0
  // CHECK: index.constant 0
  // CHECK-NEXT: [[STRUCT2:%[0-9]+]] = pop.struct.create(%idx0) : !pop.struct<index>
  // CHECK-NEXT: pop.compiler.global_store "raise2Closures_context_var_1", [[STRUCT2]] : !pop.struct<index>
  kgen.param.declare C = <15>

  // CHECK: kgen.param.declare Empty: () -> () = <@raise2Closures_Empty>
  kgen.param.declare.region Empty = () -> () {
    kgen.return
  }

  // CHECK-NEXT: kgen.param.declare Fn: <index -> index>() capturing -> index = <@raise2Closures_Fn<C, #kgen.unbound>>
  kgen.param.declare.region Fn = <A -> E>() capturing -> index {
    %0 = kgen.param.constant = <add(A, C)>
    %1 = pop.cast_from_builtin %0 : index to !pop.scalar<index>
    %2 = pop.cast_from_builtin %cst : index to !pop.scalar<index>
    %3 = pop.add %1, %2 : !pop.scalar<index>
    %5 = pop.cast_to_builtin %3 : !pop.scalar<index> to index
    kgen.param.result_bind<sub(C, A)>
    kgen.return %5 : index
  }

  // CHECK: kgen.call @call_region<:<index -> index>() -> index Fn -> Result>() : ()  -> index
  %0 = kgen.call @call_region<:<index -> index>() ->index Fn -> Result>() : () -> index
  %1 = kgen.param.constant = <Result>
  // CHECK: kgen.return
  kgen.return
}

// CHECK-LABEL: kgen.generator @parametrizedClosure_Fn<T: type>() capturing -> !kgen.paramref<T>
// CHECK-NEXT:    %0 = pop.compiler.global_load "parametrizedClosure_context_var_2" : !pop.struct<T>
// CHECK-NEXT:    %1 = pop.struct.extract %0[0] : !pop.struct<T>
// CHECK-NEXT:    kgen.return %1 : !kgen.paramref<T>

// CHECK-LABEL: kgen.generator @parametrizedClosure<T: type>(%arg0: !kgen.paramref<T>) -> !kgen.paramref<T>
// CHECK-NEXT:    %0 = pop.struct.create(%arg0) : !pop.struct<T>
// CHECK-NEXT:    pop.compiler.global_store "parametrizedClosure_context_var_2", %0 : !pop.struct<T>
// CHECK-NEXT:    kgen.param.declare Fn: <>() capturing -> !kgen.paramref<T> = <@parametrizedClosure_Fn<:type T>>
// CHECK-NEXT:    %1 = kgen.call_param[() -> !kgen.paramref<T>: Fn]()
// CHECK-NEXT:    kgen.return %1 : !kgen.paramref<T>

// CHECK-LABEL: kgen.generator @raiseParamClosure() -> f32
// CHECK-NEXT:    %simd = kgen.param.constant: scalar<f32> = <"0">
// CHECK-NEXT:    %0 = pop.cast_to_builtin %simd : !pop.scalar<f32> to f32
// CHECK-NEXT:    %1 = kgen.call @parametrizedClosure<:type f32>(%0) : (f32) -> f32
// CHECK-NEXT:    kgen.return %1 : f32


kgen.generator @parametrizedClosure<T: type>(%arg0: !kgen.paramref<T>) -> !kgen.paramref<T> {
  kgen.param.declare.region Fn = <>() capturing -> !kgen.paramref<T> {
    kgen.return %arg0 : !kgen.paramref<T>
  }
  %1 = kgen.call_param[<>() -> !kgen.paramref<T>: Fn]()
  kgen.return %1 : !kgen.paramref<T>
}

kgen.generator @raiseParamClosure() -> f32 {
  %0 = kgen.param.constant : !pop.scalar<f32> = <<"0.000000e+00">>
  %1 = pop.cast_to_builtin %0 : !pop.scalar<f32> to f32
  %2 = kgen.call @parametrizedClosure<:type f32>(%1) : (f32) -> (f32)
  kgen.return %2 : f32
}

// CHECK-LABEL: @useAfterDef
kgen.generator @useAfterDef() -> index {
  %cst = index.constant 0
  // CHECK: index.constant 0
  // CHECK-NEXT: [[STRUCT2:%[0-9]+]] = pop.struct.create(%idx0) : !pop.struct<index>
  // CHECK-NEXT: pop.compiler.global_store "useAfterDef_context_var_3", [[STRUCT2]] : !pop.struct<index>
  kgen.param.declare C = <15>

  // CHECK: kgen.call @call_region<:<index -> index>() -> index Fn -> Result>() : () -> index
  %call = kgen.call @call_region<:<index -> index>() ->index Fn -> Result>() : () -> index
  // CHECK-NEXT: kgen.param.constant
  %constant = kgen.param.constant = <Result>

  // CHECK-NEXT: kgen.param.declare Fn: <index -> index>() capturing -> index = <@useAfterDef_Fn<C, #kgen.unbound>>
  kgen.param.declare.region Fn = <A -> E>() capturing -> index {
    %0 = kgen.param.constant = <add(A, C)>
    %1 = pop.cast_from_builtin %0 : index to !pop.scalar<index>
    %2 = pop.cast_from_builtin %cst : index to !pop.scalar<index>
    %3 = pop.add %1, %2 : !pop.scalar<index>
    %5 = pop.cast_to_builtin %3 : !pop.scalar<index> to index
    kgen.param.result_bind<sub(C, A)>
    kgen.return %5 : index
  }

  // CHECK: kgen.return
  kgen.return %call : index
}

// CHECK-LABEL: @nested
kgen.generator @nested(%pred: i1) -> index {
  kgen.param.declare C = <15>

  // CHECK: hlcf.if
  %if = hlcf.if %pred -> index {
    %cst = index.constant 0
    // CHECK-NEXT: index.constant 0
    // CHECK-NEXT: [[STRUCT2:%[0-9]+]] = pop.struct.create(%idx0) : !pop.struct<index>
    // CHECK-NEXT: pop.compiler.global_store "nested_context_var_4", [[STRUCT2]] : !pop.struct<index>

    // CHECK-NEXT: kgen.call @call_region<:<index -> index>() -> index Fn -> Result>() : () -> index
    %call = kgen.call @call_region<:<index -> index>() ->index Fn -> Result>() : () -> index

    // CHECK-NEXT: kgen.param.declare
    kgen.param.declare.region Fn = <A -> E>() capturing -> index {
      %0 = kgen.param.constant = <add(A, C)>
      %1 = pop.cast_from_builtin %0 : index to !pop.scalar<index>
      %2 = pop.cast_from_builtin %cst : index to !pop.scalar<index>
      %3 = pop.add %1, %2 : !pop.scalar<index>
      %5 = pop.cast_to_builtin %3 : !pop.scalar<index> to index
      kgen.param.result_bind<sub(C, A)>
      kgen.return %5 : index
    }
    hlcf.yield %call : index
  } else {
    %cst = index.constant 0
    hlcf.yield %cst : index
  }

  %1 = kgen.param.constant = <Result>

  // CHECK: kgen.param.declare Empty: () -> () = <@nested_Empty>
  kgen.param.declare.region Empty = () -> () {
    kgen.return
  }

  // CHECK: kgen.return
  kgen.return %if : index
}

// CHECK-LABEL: @nested2
kgen.generator @nested2() -> index {
  %cst = index.constant 0
  // CHECK: index.constant
  kgen.param.declare C = <15>

  // CHECK: hlcf.loop
  %res = hlcf.loop (%input = %cst: index) -> index {
    // CHECK-NEXT: [[STRUCT2:%[0-9]+]] = pop.struct.create(%arg0, %idx0) : !pop.struct<index, index>
    // CHECK-NEXT: pop.compiler.global_store "nested2_context_var_5", [[STRUCT2]] : !pop.struct<index, index>
    // CHECK-NEXT: kgen.param.declare
    kgen.param.declare.region Fn = <A -> E>() capturing -> index {
      %1 = pop.cast_from_builtin %input : index to !pop.scalar<index>
      %2 = pop.cast_from_builtin %cst : index to !pop.scalar<index>
      %3 = pop.add %1, %2 : !pop.scalar<index>
      %5 = pop.cast_to_builtin %3 : !pop.scalar<index> to index
      kgen.param.result_bind<sub(C, A)>
      kgen.return %5 : index
    }
    // CHECK-NEXT: kgen.call @call_region<:<index -> index>() -> index Fn -> Result>() : () -> index
    %call = kgen.call @call_region<:<index -> index>() -> index Fn -> Result>() : () -> index
    hlcf.break %call : index
  }

  // CHECK: kgen.return
  kgen.return %res : index
}

// CHECK-LABEL: kgen.generator @capture_crosses_parameter_domain
kgen.generator @capture_crosses_parameter_domain<T: type>(%arg0: !kgen.paramref<T>) {
  // CHECK: declare Fn: <index, type>
  kgen.param.declare.region Fn = <A, T: type>() capturing -> !kgen.paramref<T> {
    kgen.return %arg0: !kgen.paramref<T>
  }
  kgen.return
}

// COM: We have to parametrize the wrapper on captured SSA values as well, check that this actually happens.
// CHECK-LABEL: @parametrizedSSACapture_fn<T: type>
kgen.generator @parametrizedSSACapture<T: type>(%arg0 : !kgen.paramref<T>) -> index {
  %0 = kgen.call_param[<>() -> index: fn]()
  // CHECK: kgen.param.declare fn: <>() capturing -> index = <@parametrizedSSACapture_fn<:type T>>
  kgen.param.declare.region fn = () capturing -> index {
    "op.use"(%arg0) : (!kgen.paramref<T>) -> ()
    %1 = kgen.param.constant = <0>
    kgen.return %1 : index
  }
  kgen.return %0 : index
}

// COM: We should not try and capture input parameters.
// CHECK-LABEL: @dontBindInputParameters_fn<T: type, I>
kgen.generator @dontBindInputParameters<T: type, I>(%arg0 : !kgen.paramref<T>) -> index {
  %0 = kgen.call_param[<>() -> index: bind_signature(:<index>() -> index fn, I)]()
  // CHECK: kgen.param.declare fn: <index>() capturing -> index = <@dontBindInputParameters_fn<:type T, #kgen.unbound>>
  kgen.param.declare.region fn = <I>() capturing -> index {
    %1 = kgen.param.constant = <I>
    "use.op"(%arg0) : (!kgen.paramref<T>) -> ()
    kgen.return %1 : index
  }
  kgen.return %0 : index
}

// CHECK-LABEL: kgen.generator @innermostCapturesThroughMid_Bot<A>
// CHECK-LABEL: kgen.generator @innermostCapturesThroughMid_Mid<A>
// CHECK-LABEL: kgen.generator @innermostCapturesThroughMid<A>
// CHECK-NEXT: @innermostCapturesThroughMid_Mid<A>

kgen.generator @innermostCapturesThroughMid<A>() {
  kgen.param.declare.region Mid = () {
    kgen.param.declare.region Bot = () {
      kgen.param.constant = <A>
      kgen.return
    }
    kgen.return
  }
  kgen.return
}

// CHECK-LABEL: kgen.generator @paramCaptureNestedInParamRefType_Fn<N, Vs: array<N, i32>>
// CHECK: constant: array<N, i32> = <Vs>
// CHECK: declare Fn: () -> () = <@paramCaptureNestedInParamRefType_Fn<N, :array<N, i32> Vs>>

kgen.generator @paramCaptureNestedInParamRefType<N, Vs: array<N, i32>>() {
  kgen.param.declare.region Fn = () {
    kgen.param.constant: array<N, i32> = <Vs>
    kgen.return
  }
  kgen.return
}

// CHECK-LABEL: @left_to_right_dependency_CaptureThemAll
// CHECK-SAME: <A, F: type, G: type, H: type, I: type, J: type,
// CHECK-SAME:  L: array<A, struct<F, G, H, I, J>>, B: type,
// CHECK-SAME:  E: array<A, array<A, array<A, B>>>,
// CHECK-SAME:  D: array<A, array<A, B>>, C: array<A, B>
kgen.generator @left_to_right_dependency<
    A, B: type, C: array<A, B>, D: array<A, array<A, B>>,
    E: array<A, array<A, array<A, B>>>,
    F: type, G: type, H: type, I: type, J: type,
    K: struct<F, G, H, I, J>, L: array<A, struct<F, G, H, I, J>>>() {
  kgen.param.declare.region CaptureThemAll = () {
    "use"() {
      a = #kgen.param.decl.ref<"L"> : !pop.array<A, struct<F, G, H, I, J>>,
      b = #kgen.param.decl.ref<"E"> : !pop.array<A, array<A, array<A, B>>>,
      c = #kgen.param.decl.ref<"D"> : !pop.array<A, array<A, B>>,
      d = #kgen.param.decl.ref<"C"> : !pop.array<A, B>
    } : () -> ()
    kgen.return
  }
  kgen.return
}

// CHECK-LABEL: kgen.generator @dependent_outline<a>
kgen.generator @dependent_outline<a>() {
  // CHECK-NEXT: kgen.param.declare fn: <type>(!pop.array<a, *(0,0)>) -> () =
  // CHECK-SAME: <@dependent_outline_fn<a, :type #kgen.unbound>>
  kgen.param.declare.region fn = <b: type>(%arg0: !pop.array<a, b>) {
    kgen.return
  }
  kgen.return
}
