load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "kgen",
    srcs = glob(["*.cpp"]),
    data = [
        "//KGEN:CompilerRT",
        "//KGEN:CompilerRT.distributable",
        "@llvm-project//compiler-rt:orc_rt",
    ],
    deps = [
        "//AsyncRT:Init",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Config",
        "//KGEN:Compiler",
        "//KGEN:ExecutionEngine",
        "//KGEN:KGENDialect",
        "//KGEN:MojoParser",
        "//KGEN:ObjectCompiler",
        "//KGEN:Pipeline",
        "//KGEN:Support",
        "//KGEN:ToolCommon",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:Globals",
        "//Support:MArchTarget",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)
