//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include "EmitFuncHeader.h"
#include "KGEN/LowerToObject.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/ToolOutputFile.h"

using namespace M;
using namespace KGEN;

/// This allows us to emit a header file for the given func so that we can
/// `#include` it and get nice autocompletion/etc. in users' IDEs.
LogicalResult M::KGEN::emitHeader(ObjectCompiler &compiler,
                                  StringRef filename) {
  std::string err;
  auto outFile = mlir::openOutputFile(filename, &err);
  if (!outFile)
    return mlir::emitError(compiler.getModule()->getLoc(), err);

  std::filesystem::path filenameOnly(filename.str());
  filenameOnly = filenameOnly.stem();

  llvm::StringLiteral headerFmtStart = R"literal(//===-{0}-===//
//
// This file is Modular Inc proprietary.
//
//==={1}===//
// THIS FILE IS AUTOGENERATED BY `kgen`, DO NOT EDIT!
//==={1}===//

#ifndef {2}
#define {2}

#ifdef __cplusplus
extern "C" {{
#endif

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

)literal";

  llvm::StringLiteral headerFmtEnd = R"literal(
#ifdef __cplusplus
} // extern "C"
#endif

#endif // {0}
)literal";

  std::string headerGuard =
      "__KGEN_" + StringRef(filenameOnly.string()).upper() + "_H";
  outFile->os() << llvm::formatv(
      headerFmtStart.data(),
      llvm::fmt_align(" " + filename + " ", llvm::AlignStyle::Left,
                      80 - 2 * strlen("//===-"), '-'),
      llvm::fmt_repeat('-', 80 - 2 * strlen("//===")), headerGuard);

  // Emit the function decls into the header.
  if (failed(compiler.produceFunctionDecls(outFile->os())))
    return failure();

  outFile->os() << llvm::formatv(headerFmtEnd.data(), headerGuard);

  outFile->keep();

  return mlir::success();
}
