//===- EmitKernelHeader.cpp -----------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include "EmitKernelHeader.h"
#include "KGEN/MetaDialect/MetaTypes.h"
#include "Support/ML/DType.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/ToolOutputFile.h"

using namespace M;
using namespace KGEN;

namespace {
/// This provides a method by which we can emit a kernel's signature to an
/// llvm::formatv stream.
struct FormatKernel : public llvm::FormatAdapter<KernelOp> {
  FormatKernel(KernelOp func)
      : llvm::FormatAdapter<KernelOp>(std::forward<KernelOp &&>(func)) {}

  void format(llvm::raw_ostream &os, StringRef style) override {
    auto printDTypeAsC = [&](DType dt) {
      if (dt.isFloat()) {
        switch (dt.getValue()) {
        case DType::f32:
          os << "float";
          return;
        case DType::f64:
          os << "double";
          return;
        }
        llvm_unreachable("TODO: unhandled float type");
      }
      if (dt.isInt())
        os << (dt.isUInt() ? "u" : "") << "int" << dt.getWidthInBits() << "_t";
    };

    // Helper to print a function as a C type.
    std::function<void(Type)> printTypeAsC = [&](Type t) {
      if (auto simd = t.dyn_cast<SIMDType>()) {
        printDTypeAsC(simd.resolveDType());
        // Get the vector size in bytes to be used by the vector_size attribute.
        // The `__attribute__ ((vector_size(N)))` must be specified in bytes.
        auto vectorSizeInBytes =
            simd.resolveDType().getSizeInBytes(*simd.resolveSize());
        // Fixed vector types are easy and we add the simd attributes.
        // TODO: This will only work on GNU and CLANG compilers.
        os << " __attribute__ ((vector_size(" << vectorSizeInBytes << ")))";
        return;
      }
      if (auto ptr = t.dyn_cast<PointerType>()) {
        if (auto dtype = ptr.resolveDType(); dtype.isValid())
          printDTypeAsC(dtype);
        else
          os << "void";
        os << " *";
        return;
      }
      if (auto buffer = t.dyn_cast<BufferType>()) {
        if (!buffer.getSize())
          os << "intptr_t, ";
        if (auto dtype = buffer.resolveDType(); dtype.isValid()) {
          printDTypeAsC(dtype);
          os << " *";
        } else {
          os << "void *, int8_t";
        }
        return;
      }

      assert((t.isIndex() || llvm::isPowerOf2_64(t.getIntOrFloatBitWidth())) &&
             "bitwidth must be a power of 2");

      // Elementary type, just print it.
      if (t.isa<IntegerType>())
        os << "int" << t.getIntOrFloatBitWidth() << "_t";
      else if (t.isa<IndexType>())
        os << "intptr_t";
      else if (t.isF16())
        llvm::report_fatal_error("no support for fp16 yet");
      else if (t.isF32())
        os << "float";
      else if (t.isF64())
        os << "double";
      else
        llvm::report_fatal_error("unknown type");
    };

    // Now print the function declaration.
    os << "extern ";
    if (Item.getNumResults())
      printTypeAsC(Item.getResultTypes().front());
    else
      os << "void";
    os << " " << Item.getName() << "(";
    llvm::interleaveComma(Item.getFunctionType().getInputs(), os, printTypeAsC);
    os << ");";
  }
};
} // namespace

/// This allows us to emit a header file for the given kernel so that we can
/// `#include` it and get nice autocompletion/etc. in users' IDEs.
LogicalResult M::KGEN::emitHeaderForKernel(KernelOp kernel,
                                           StringRef filename) {
  std::string err;
  auto outFile = mlir::openOutputFile(filename, &err);
  if (!outFile)
    return mlir::emitError(kernel.getLoc(), err);

  llvm::StringLiteral fmtStr = R"literal(//===-{0}-===//
//
// This file is Modular Inc proprietary.
//
//==={1}===//
// THIS FILE IS AUTOGENERATED BY `kgen`, DO NOT EDIT!
//==={1}===//

#ifndef {2}
#define {2}

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stddef.h>

{3}

#ifdef __cplusplus
} // extern "C"
#endif

#endif // {2}
)literal";

  outFile->os() << llvm::formatv(
      fmtStr.data(),
      llvm::fmt_align(" " + kernel.getName() + ".h ", llvm::AlignStyle::Left,
                      80 - 2 * strlen("//===-"), '-'),
      llvm::fmt_repeat('-', 80 - 2 * strlen("//===")),
      "__KGEN_" + kernel.getName().upper() + "_H", FormatKernel(kernel));

  outFile->keep();

  return mlir::success();
}
