//===- EmitFuncHeader.cpp -------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//

#include "EmitFuncHeader.h"
#include "KGEN/POPDialect/POPTypes.h"
#include "KGEN/ZAPDialect/ZAPTypes.h"
#include "Support/ML/DType.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/ToolOutputFile.h"

using namespace M;
using namespace KGEN;

/// Emit the C signature of a KGEN func.
static LogicalResult emitSignature(raw_ostream &os, FuncOp func) {
  auto printDTypeAsC = [&](DType dt) -> LogicalResult {
    if (dt.isFloat()) {
      switch (dt.getValue()) {
      case DType::f32:
        os << "float";
        return success();
      case DType::f64:
        os << "double";
        return success();
      }
      return func.emitError("unhandled floating point dtype: ")
             << dt.getAsString();
    }
    if (dt.isInt())
      os << (dt.isUInt() ? "u" : "") << "int" << dt.getWidthInBits() << "_t";
    return success();
  };

  // Helper to print a function as a C type.
  std::function<LogicalResult(Type)> printTypeAsC =
      [&](Type t) -> LogicalResult {
    if (auto scalar = t.dyn_cast<POP::ScalarType>())
      return printDTypeAsC(*scalar.getResolvedDType());

    if (auto simd = t.dyn_cast<POP::SIMDType>()) {
      // Since the vector_size attribute only works on GNU and CLANG compilers,
      // we pass in an array.
      if (failed(printDTypeAsC(*simd.getResolvedDType())))
        return failure();
      os << "[" << simd.getResolvedSize() << "]";
      return success();
    }

    if (auto ptr = t.dyn_cast<POP::PointerType>()) {
      if (Type type = ptr.getResolvedElementType()) {
        if (failed(printTypeAsC(type)))
          return failure();
      } else {
        os << "void";
      }
      os << " *";
      return success();
    }

    if (auto array = t.dyn_cast<POP::ArrayType>()) {
      if (failed(printTypeAsC(array.getResolvedElementType())))
        return failure();
      os << "[" << *array.getResolvedSize() << "]";
      return success();
    }

    // FIXME: This pass should run pre-elaboration, but we have no way for user
    // defined typed to specify the functions in OpaqueObjectInterface.
    if (auto buffer = t.dyn_cast<ZAP::BufferType>()) {
      os << "intptr_t, void *, int8_t";
      return success();
    }

    if (auto structType = t.dyn_cast<POP::StructType>()) {
      SmallVector<Type> elementTypes;
      elementTypes.reserve(structType.getElementTypes().size());
      if (failed(structType.resolveElementTypes(elementTypes)))
        return failure();
      for (auto &elTy : llvm::enumerate(elementTypes)) {
        if (elTy.index() != 0)
          os << ", ";
        if (failed(printTypeAsC(elTy.value())))
          return failure();
      }
      return success();
    }

    if (t.isa<DTypeType>()) {
      os << "int8_t";
      return success();
    }

    if (!t.isa<IndexType, IntegerType, FloatType>())
      return func.emitError("unsupported argument type: ") << t;
    if (!t.isIndex() && !llvm::isPowerOf2_64(t.getIntOrFloatBitWidth()))
      return func.emitError("integer or float bitwidth must be a power of 2");

    // Elementary type, just print it.
    if (t.isa<IntegerType>())
      os << "int" << t.getIntOrFloatBitWidth() << "_t";
    else if (t.isa<IndexType>())
      os << "intptr_t";
    else if (t.isF16())
      llvm::report_fatal_error("no support for fp16 yet");
    else if (t.isF32())
      os << "float";
    else if (t.isF64())
      os << "double";
    else
      return func.emitError("unhandled float type: ") << t;
    return success();
  };

  // Now print the function declaration.
  os << "extern ";
  if (func.getNumResults() > 1)
    return func.emitError("functions with more than 1 result unsupported");
  if (func.getNumResults() == 0)
    os << "void";
  else if (failed(printTypeAsC(func.getResultTypes().front())))
    return failure();
  os << " " << func.getName() << "(";
  for (auto &it : llvm::enumerate(func.getFunctionType().getInputs())) {
    if (it.index() != 0)
      os << ", ";
    if (failed(printTypeAsC(it.value())))
      return failure();
  }
  os << ");";
  return success();
}

/// This allows us to emit a header file for the given func so that we can
/// `#include` it and get nice autocompletion/etc. in users' IDEs.
LogicalResult M::KGEN::emitHeaderForFunc(FuncOp func, StringRef filename) {
  std::string err;
  auto outFile = mlir::openOutputFile(filename, &err);
  if (!outFile)
    return mlir::emitError(func.getLoc(), err);

  llvm::StringLiteral headerFmtStart = R"literal(//===-{0}-===//
//
// This file is Modular Inc proprietary.
//
//==={1}===//
// THIS FILE IS AUTOGENERATED BY `kgen`, DO NOT EDIT!
//==={1}===//

#ifndef {2}
#define {2}

#ifdef __cplusplus
extern "C" {{
#endif

#include <stdint.h>
#include <stddef.h>

)literal";

  llvm::StringLiteral headerFmtEnd = R"literal(
#ifdef __cplusplus
} // extern "C"
#endif

#endif // {0}
)literal";

  std::string headerGuard = "__KGEN_" + func.getName().upper() + "_H";
  outFile->os() << llvm::formatv(
      headerFmtStart.data(),
      llvm::fmt_align(" " + func.getName() + ".h ", llvm::AlignStyle::Left,
                      80 - 2 * strlen("//===-"), '-'),
      llvm::fmt_repeat('-', 80 - 2 * strlen("//===")), headerGuard);
  if (failed(emitSignature(outFile->os(), func)))
    return mlir::emitError(func.getLoc(),
                           "during header emission for this function");
  outFile->os() << llvm::formatv(headerFmtEnd.data(), headerGuard);

  outFile->keep();

  return mlir::success();
}
