load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "support-dialect-opt",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//AsyncRT:CompilerSupport",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Support:Base",
        "//Support:DebugInfoToLLVM",
        "//Support:Globals",
        "//Support:MDialect",
        "@llvm-project//mlir:MlirOptLib",
    ],
)
