cc_binary(
    name = "support-dialect-opt",
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//LLCL:Runtime",
        "//LLCL:CompilerSupport",
        "//Support:Base",
        "//Support:DebugInfoToLLVM",
        "//Support:MDialect",
        "@llvm-project//mlir:MlirOptLib",
    ],
)
