[workspace]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Get started with GPU programming tutorial solution"
name = "gpu-intro"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
max = "*"

[tasks]
vector_addition = "mojo run vector_addition.mojo"
