//===- MetaOps.cpp --------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file implements the Meta dialect operations.
//
//===----------------------------------------------------------------------===//

#include "KGEN/MetaDialect/MetaOps.h"

#include "GenericML/Support/TensorEltType.h"
#include "KGEN/KGENDialect/KGENAttrs.h"
#include "KGEN/KGENDialect/KGENDialect.h"
#include "KGEN/KGENDialect/KGENTypes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/FunctionImplementation.h"

using namespace M;
using namespace KGEN;

//===----------------------------------------------------------------------===//
// MetaBufferSizeOp
//===----------------------------------------------------------------------===//

OpFoldResult MetaBufferSizeOp::fold(ArrayRef<Attribute> constants) {
  assert(constants.empty() && "meta.buffer.size has no operands");
  // A null size indicates ? size (unknown size). Since returning null
  // indicates that we don't fold anything, we don't need to check if
  // size is null.
  return getValue().getType().cast<BufferType>().getSize();
}

//===----------------------------------------------------------------------===//\
// MetaBufferDTypeOp
//===----------------------------------------------------------------------===//

OpFoldResult MetaBufferDTypeOp::fold(ArrayRef<Attribute> constants) {
  assert(constants.empty() && "meta.buffer.dtype has no operands");
  // A null dtype indicates ? dtype (unknown dtype). Since returning null
  // indicates that we don't fold anything, we don't need to check if
  // dtype is null.
  return getValue().getType().cast<BufferType>().getDtype();
}

//===----------------------------------------------------------------------===//
// MetaBufferCastOp
//===----------------------------------------------------------------------===//

/// Verifies that casting the input buffer to the result buffer is OK.
/// Allows casting to occur if
/// inpDtype == ? || resDtype == ? || inpDtype == resDtype
/// and
/// inpSize == ? || resSize == ? || inpSize == resSize
LogicalResult MetaBufferCastOp::verify() {
  BufferType inputBufTy = getBuffer().getType().cast<BufferType>();
  BufferType resultBufTy = getResult().getType().cast<BufferType>();

  Attribute inputDtype = inputBufTy.getDtype();
  Attribute resultDtype = resultBufTy.getDtype();

  if (inputDtype != resultDtype)
    if (inputDtype && resultDtype)
      // A null dtype indicates a buffer with unknown dtype.
      // TODO: Print the string version of the dtypes instead of a number.
      return emitOpError()
             << "expected the dtype of the input buffer (" << inputDtype
             << ") to the same as to the dtype you are casting to ("
             << resultDtype << "), or one of them to be unknown.";

  Attribute inputSize = inputBufTy.getSize();
  Attribute resultSize = resultBufTy.getSize();

  if (inputSize != resultSize)
    if (inputSize && resultSize)
      // A null size indicates a buffer with unknown size.
      return emitOpError()
             << "expected the size of the input buffer (" << inputSize
             << ") to be equal to the size you are casting it to ("
             << resultSize << "), or one of them to be unknown.";
  return success();
}

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "KGEN/MetaDialect/Meta.cpp.inc"
