//===- MetaOps.cpp --------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This file implements the Meta dialect operations.
//
//===----------------------------------------------------------------------===//

#include "KGEN/MetaDialect/MetaOps.h"

#include "KGEN/KGENDialect/KGENAttrs.h"
#include "KGEN/KGENDialect/KGENTypes.h"
#include "KGEN/KGENDialect/KGENUtils.h"
#include "Support/ML/DType.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/FunctionImplementation.h"

using namespace M;
using namespace KGEN;

//===----------------------------------------------------------------------===//
// Shared logic for MetaCastToBuiltinOp and MetaCastFromBuiltinOp
//===----------------------------------------------------------------------===//

static LogicalResult checkCastedTypes(Operation *op, Type metaTy,
                                      Type standardTy) {
  // Ignore types that are opaquely casted.
  if (metaTy.isa<PointerType>())
    return success();

  if (!metaTy.isa<ScalarType, SIMDType>())
    return op->emitOpError("expected a scalar or SIMD type");

  // Check the builtin types.
  auto emitError = [op](StringRef msg) {
    return op->emitOpError()
           << "does not support casting " << op->getOperand(0).getType()
           << " to " << op->getResult(0).getType() << ": " << msg;
  };
  return checkMetaCastedTypes(emitError, metaTy, standardTy);
}

//===----------------------------------------------------------------------===//
// MetaCastToBuiltinOp
//===----------------------------------------------------------------------===//

/// Verifies that casting the input scalar to the corresponding standard
/// type is valid.
LogicalResult MetaCastToBuiltinOp::verify() {
  return checkCastedTypes(*this, getOperand().getType(), getType());
}

/// Folds fixed_type -> !meta.type -> fixed_type (for A->B->A only)
OpFoldResult MetaCastToBuiltinOp::fold(ArrayRef<Attribute> operands) {
  if (auto fromFixedType =
          getOperand().getDefiningOp<MetaCastFromBuiltinOp>()) {
    // Note: The defining op will be a MetaCastFromBuiltinOp, since
    // we have two asymmetric cast ops.
    // Fold A->B->A
    if (fromFixedType.getOperand().getType() == getType())
      return fromFixedType.getOperand();
  }
  return {};
}

//===----------------------------------------------------------------------===//
// MetaCastFromBuiltinOp
//===----------------------------------------------------------------------===//

/// Verifies that casting the standard type to !meta type is valid.
LogicalResult MetaCastFromBuiltinOp::verify() {
  return checkCastedTypes(*this, getType(), getOperand().getType());
}

/// Folds !meta.type -> fixed_type -> !meta.type (for A->B->A only)
OpFoldResult MetaCastFromBuiltinOp::fold(ArrayRef<Attribute> operands) {
  if (auto toFixedType = getOperand().getDefiningOp<MetaCastToBuiltinOp>()) {
    // Note: The defining op will be a MetaCastToBuiltinOp, since
    // we have two asymmetric cast ops.
    // Fold A->B->A
    if (toFixedType.getOperand().getType() == getType())
      return toFixedType.getOperand();
  }
  return {};
}

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "KGEN/MetaDialect/Meta.cpp.inc"
