package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mojo-lsp-test-client",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//KGEN:Support",
        "//Support:Base",
        "//Support:Filesystem",
        "@llvm-project//mlir:MlirLspServerSupportLib",
    ],
)
