load("//bazel:api.bzl", "modular_cc_library")

modular_cc_library(
    name = "mojo-lsp-test-client",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//KGEN:Support",
        "//KGEN/tools/common/lsp-protocol",
        "//Support:Base",
        "//Support:Filesystem",
        "@llvm-project//mlir:MlirLspServerSupportLib",
    ],
)
