//===----------------------------------------------------------------------===//
//
// This file is Modular Inc proprietary.
//
//===----------------------------------------------------------------------===//
//
// This is the top level file for the LIT dialect.
//
//===----------------------------------------------------------------------===//

#ifndef LIT_TD
#define LIT_TD

include "KGEN/KGENDialect/KGENAttrs.td"
include "KGEN/LITDialect/LITAttrs.td"
include "KGEN/LITDialect/LITTypes.td"
include "KGEN/LITDialect/LITOps.td"

#endif // KGEN_TD
