load("@bazel_skylib//rules:expand_template.bzl", "expand_template")
load("@pip_deps//:requirements.bzl", "requirement")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files")
load(
    "//bazel:api.bzl",
    "driver_option_tablegen",
    "modular_cc_binary",
    "modular_cc_library",
    "rpath_shim",
    "run_tool",
    "td_library",
)

expand_template(
    name = "MojoDebugHeaderGen",
    out = "MojoDebug.h",
    substitutions = select({
        "@platforms//os:macos": {
            "@CMAKE_SHARED_LIBRARY_PREFIX@": "lib",
            "@CMAKE_SHARED_LIBRARY_SUFFIX@": ".dylib",
        },
        "@platforms//os:linux": {
            "@CMAKE_SHARED_LIBRARY_PREFIX@": "lib",
            "@CMAKE_SHARED_LIBRARY_SUFFIX@": ".so",
        },
    }),
    template = "Debug/MojoDebug.h.in",
)

modular_cc_library(
    name = "MojoDebugHeader",
    hdrs = [":MojoDebugHeaderGen"],
    include_prefix = "Debug",
)

[
    driver_option_tablegen(
        name = command,
        srcs = glob(["{}/*.td".format(command)]),
        manual_name = "mojo-{}".format(command.lower()),
        markdown_name = command.lower(),
        td_file = "{command}/{command}Options.td".format(command = command),
        deps = [
            ":MojoDescriptionTdFiles",
        ],
    )
    for command in [
        "Build",
        "Debug",
        "Demangle",
        "Doc",
        "Format",
        "Package",
        "REPL",
        "Run",
        "Test",
    ]
]

td_library(
    name = "MojoDescriptionTdFiles",
    srcs = glob([
        "*.td",
        "Common/*.td",
    ]),
    includes = ["."],
    deps = [
        "//Support:DriverCommandTdFiles",
        "//Support:OptTableTdFiles",
    ],
)

driver_option_tablegen(
    name = "Index",
    srcs = ["DriverOptions.td"],
    includes = ["."],
    manual_name = "mojo",
    markdown_name = "index",
    td_file = "DriverOptions.td",
    deps = [
        ":Build.td_library",
        ":Debug.td_library",
        ":Demangle.td_library",
        ":Doc.td_library",
        ":Format.td_library",
        ":MojoDescriptionTdFiles",
        ":Package.td_library",
        ":REPL.td_library",
        ":Run.td_library",
        ":Test.td_library",
    ],
)

pkg_files(
    name = "docs",
    srcs = [
        ":Build.man_files",
        ":Debug.man_files",
        ":Demangle.man_files",
        ":Doc.man_files",
        ":Format.man_files",
        ":Index.man_files",
        ":Package.man_files",
        ":REPL.man_files",
        ":Run.man_files",
        ":Test.man_files",
    ],
    visibility = ["//visibility:public"],
)

modular_cc_binary(
    name = "mojo",
    srcs = glob([
        "**/*.h",
        "**/*.cpp",
    ]),
    includes = ["."],
    deps = [
        ":Build.inc_files",
        ":Debug.inc_files",
        ":Demangle.inc_files",
        ":Doc.inc_files",
        ":Format.inc_files",
        ":Index.inc_files",
        ":MojoDebugHeader",
        ":Package.inc_files",
        ":REPL.inc_files",
        ":Run.inc_files",
        ":Test.inc_files",
        ":rpaths",
        "//AsyncRT:Init",
        "//AsyncRT:Runtime",
        "//AsyncRT:RuntimeGlobals",
        "//Config",
        "//KGEN:Compiler",
        "//KGEN:ExecutionEngine",
        "//KGEN:KGENDialect",
        "//KGEN:LITDialect",
        "//KGEN:MojoParser",
        "//KGEN:MojoTesting",
        "//KGEN:MojoTooling",
        "//KGEN:ObjectCompiler",
        "//KGEN:POPDialect",
        "//KGEN:Support",
        "//KGEN:ToolCommon",
        "//KGEN/tools/common",
        "//Support:Base",
        "//Support:Compiler",
        "//Support:CrashReporting",
        "//Support:Driver",
        "//Support:Filesystem",
        "//Support:Globals",
        "//Support:MArchTarget",
        "//Support:MDialect",
        "//Support:Telemetry",
        "@llvm-project//mlir:IndexDialect",
    ],
)

rpath_shim(
    name = "rpaths",
    visibility = ["//visibility:private"],
    deps = [
        "//ModularFramework/tools/mof",
    ],
)

run_tool(
    name = "mojo-standalone",
    data = [
        "//:libpython",
        "//GenericML:DeviceDriver",
        "//GenericML:modular-framework-common",
        "//KGEN:CompilerRT",
        "//KGEN:CompilerRT.distributable",
        "//KGEN:MojoLLDB",
        "//KGEN:mojo-lldb",
        "//KGEN/tools/mojo",
        "//KGEN/tools/mojo-repl-entry-point",
        "//Kernels/mojo/_mlir",
        "//Kernels/mojo/algorithm",
        "//Kernels/mojo/autotune",
        "//Kernels/mojo/benchmark",
        "//Kernels/mojo/buffer",
        "//Kernels/mojo/compile",
        "//Kernels/mojo/complex",
        "//Kernels/mojo/extensibility",
        "//Kernels/mojo/gpu",
        "//Kernels/mojo/layout",
        "//Kernels/mojo/linalg",
        "//Kernels/mojo/nn",
        "//Kernels/mojo/nvml",
        "//Kernels/mojo/nvrtc",
        "//Kernels/mojo/quantization",
        "//Kernels/mojo/register",
        "//Kernels/mojo/runtime",
        "//Kernels/mojo/subprocess",
        "//ModularFramework/tools/mof",
        "//SDK/lib/API/mojo/max/max",
        "//open-source/mojo/stdlib/stdlib",
        "//utils/mblack",
        "//utils/mblack:shim.py",
        "@llvm-project//compiler-rt:orc_rt",
        requirement("transformers"),
        requirement("torch"),
    ],
    env = {
        "MODULAR_MOJO_MAX_MBLACK_PATH": "$(rlocationpath //utils/mblack:shim.py)",
    },
    env_inherit = [
        "MODULAR_PROFILE_FILENAME",
        "MODULAR_MAX_TEMPS_DIR",
    ],
    tags = ["manual"],
    tool = ":mojo",
    visibility = ["//visibility:private"],
)
