load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "test",
    srcs = glob([
        "**/*.mlir",
        "**/*.td",
    ]),
    custom_substitutions = {
        "%driver-tblgen": "$(rlocationpath //Support/tools/driver-tblgen) -I $(dirname $(dirname $(dirname ../../../../$(location //Support:include/Support/Driver/DriverCommand.td)))) -I $(dirname $(dirname $(dirname ../../../../../$(rlocationpath @llvm-project//llvm:include/llvm/Option/OptParser.td))))",
    },
    data = [
        "//Support:DriverCommandTdFiles",
        "//Support:include/Support/Driver/DriverCommand.td",
        "@llvm-project//llvm:include/llvm/Option/OptParser.td",
    ],
    tools = [
        "//Support/tools/build-info",
        "//Support/tools/driver-tblgen",
        "//Support/tools/support-dialect-opt",
        "//Support/tools/system-info",
        "@crashpad//:modular-crashpad-handler",
    ],
)
