load("//bazel:api.bzl", "modular_cc_binary")

package(default_visibility = ["//KGEN:consumers"])

modular_cc_binary(
    name = "hash-mlir",
    srcs = glob(["*.cpp"]),
    deps = [
        "//KGEN:ToolCommon",
        "//MLRT:AsyncRT/RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)
