load("//bazel:api.bzl", "modular_cc_binary")

modular_cc_binary(
    name = "hash-mlir",
    srcs = glob(["*.cpp"]),
    deps = [
        "//KGEN:ToolCommon",
        "//LLCL:RuntimeGlobals",
        "//Support:Base",
        "//Support:Globals",
        "@llvm-project//mlir:BytecodeWriter",
    ],
)
