load("//bazel:api.bzl", "modular_py_library", "modular_py_test", "pkg_files", "requirement", "strip_prefix")

exports_files(["pyproject.toml"])

modular_py_library(
    name = "support",
    srcs = glob(["modular/**/*.py"]),
    data = ["modular/utils/debuglib/py.typed"],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("find-libpython"),
        requirement("numpy"),
        requirement("pyyaml"),
        requirement("ruamel-yaml"),
    ],
)

modular_py_test(
    name = "unittests",
    srcs = glob(["tests/**/*.py"]),
    args = ["--doctest-modules"],
    env = {
        "GIT_CONFIG_GLOBAL": "/dev/null",
    },
    tags = ["requires-network"],
    deps = [
        ":support",
        requirement("ruamel-yaml"),
        requirement("torch"),
    ],
)

pkg_files(
    name = "support_utils_files",
    srcs = glob(["**"]),
    prefix = "modular",
    strip_prefix = strip_prefix.from_pkg(""),
    visibility = ["//visibility:public"],
)
