load("@pip_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")
load("//bazel:api.bzl", "pytest_test")

py_library(
    name = "support",
    srcs = glob(["modular/**/*.py"]),
    data = ["modular/utils/debuglib/py.typed"],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("find_libpython"),
        requirement("numpy"),
        requirement("ruamel.yaml"),
    ],
)

pytest_test(
    name = "unittests",
    srcs = glob(["tests/**/*.py"]),
    tags = ["requires-network"],
    deps = [
        ":support",
    ],
)
