load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load("//bazel:api.bzl", "modular_cc_library", "modular_py_library", "modular_py_test", "requirement")

exports_files(["pyproject.toml"])

modular_py_library(
    name = "support",
    srcs = glob(["modular/**/*.py"]),
    data = ["modular/utils/debuglib/py.typed"],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        requirement("find_libpython"),
        requirement("numpy"),
        requirement("pyyaml"),
        requirement("ruamel.yaml"),
    ],
)

modular_py_test(
    name = "unittests",
    srcs = glob(["tests/**/*.py"]),
    args = ["--doctest-modules"],
    tags = ["requires-network"],
    deps = [
        ":support",
    ],
)

pkg_files(
    name = "support_utils_files",
    srcs = glob(["**"]),
    prefix = "modular",
    strip_prefix = strip_prefix.from_pkg(""),
    visibility = ["//visibility:public"],
)

modular_cc_library(
    name = "CPython",
    srcs = glob(["lib/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    local_defines = ["Py_LIMITED_API=0x03090000"],
    deps = [
        "@python_3_9//:python_headers",
    ],
)
