#!/usr/bin/env python3
# ===----------------------------------------------------------------------=== #
#
# This file is Modular Inc proprietary.
#
# ===----------------------------------------------------------------------=== #

import argparse
import re
import sys
from pathlib import Path


def find_dependencies(path):
    # If this is a directory, recursively find dependencies in all files
    # within it.
    if path.is_dir():
        dependencies = set()
        for child in path.iterdir():
            dependencies.update(find_dependencies(child))
        return dependencies

    # If this isn't a .mojo/.🔥 file, bail out.
    if not path.suffix in [".mojo", ".🔥"]:
        return set()

    # Otherwise, read the file and find all dependencies. The dependencies are
    # computed by looking for `import` statements.
    skip_regex = re.compile(r".*# disable-validate")
    import_regex = re.compile(r"import\s+(\w+)")
    from_regex = re.compile(r"from\s+(\w+)")
    dependencies = set()
    with open(path, "r") as f:
        for line in f:
            skip_match = skip_regex.match(line)
            if skip_match:
                continue
            import_match = import_regex.match(line)
            if import_match:
                dependencies.add(import_match.group(1))
            from_match = from_regex.match(line)
            if from_match:
                dependencies.add(from_match.group(1))

    return dependencies


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Verifies that dependencies for the given mojo source are covered"
            " by the provided known set."
        )
    )
    parser.add_argument("--path", help="The path to the mojo source.")
    parser.add_argument(
        "--known_dependencies",
        nargs="*",
        help="The known dependencies declared for the source.",
    )
    args = parser.parse_args()
    path = Path(args.path)

    if not path.exists():
        print(
            f"error: '{args.path}' does not exist",
            file=sys.stderr,
        )
        exit(1)

    # Collect the set of importable modules generated by this mojo source. If
    # this is the `stdlib`, this is both `stdlib` and any nested modules.
    # Otherwise, this is just the module itself.
    path_modules = {path.stem}
    if path.name == "stdlib":
        for child in path.iterdir():
            path_modules.add(child.stem)

    # Find all dependencies needed within the given path.
    dependecies = find_dependencies(path)

    # Check that all dependencies are covered by the known dependencies.
    unknown_dependencies = (
        dependecies - set(args.known_dependencies) - path_modules
    )
    if unknown_dependencies:
        print(
            (
                f"error: '{args.path}' has undeclared dependencies:"
                f" {unknown_dependencies}"
            ),
            file=sys.stderr,
        )
        exit(1)


if __name__ == "__main__":
    main()
