load("//bazel:api.bzl", "lit_tests", "pkg_files")

_DATA = [
    "inputs/**",
]

lit_tests(
    name = "test",
    srcs = glob(
        [
            "*.mlir",
            "**/*.mojo",
        ],
        exclude = _DATA,
    ),
    data = glob(["inputs/**/*.mojo"]),
    mojo_deps = [
        "//open-source/max/max/_mlir/src:_mlir",
        "@mojo//:stdlib",
    ],
    tags = ["gpu"],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/kgen",
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/kgen-translate",
        "//KGEN/tools/llvm-module-split",
        "//KGEN/tools/mojo",
        "@llvm-project//llvm:llvm-objdump",
    ],
)

lit_tests(
    name = "test_stdlib_srcs",
    # This tests require the stdlib and mlirc srcs, where other tests do
    # not require them
    srcs = glob(["*.test"]),
    data = glob(["inputs/**/*.mojo"]) + [
        "//open-source/max/max/_mlir/src:_mlir_srcs",
        "//open-source/max/mojo/stdlib/stdlib:stdlib_srcs",
    ],
    env = {
        "MODULAR_MOJO_IMPORT_SRCS": "$(locations //open-source/max/max/_mlir/src:_mlir_srcs) $(locations //open-source/max/mojo/stdlib/stdlib:stdlib_srcs)",
    },
    mojo_deps = [
        "@mojo//:stdlib",
    ],
    tools = [
        "//KGEN/tools/hash-mlir",
        "//KGEN/tools/kgen",
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/kgen-translate",
    ],
)

pkg_files(
    name = "test_python",
    srcs = [
        "mojo_build_python.mojo",
    ],
    visibility = ["//visibility:public"],
)
