load("@rules_pkg//pkg:mappings.bzl", "pkg_files")
load("//bazel:api.bzl", "lit_tests")

lit_tests(
    name = "test",
    srcs = glob(
        [
            "*.mojo",
            "*.mlir",
        ],
        exclude = [
            "canonicalize-custom-ops.mojo",
            "multiresult_asm_mma.mojo",
        ],
    ),
    data = glob(["inputs/**/*.mojo"]) + [
        "//:libpython",
        "//KGEN:CompilerRT",
        "//KGEN:CompilerRT.distributable",
        "@llvm-project//compiler-rt:orc_rt",
    ],
    mojo_deps = [
        "//Kernels/mojo/gpu",
        "//Kernels/mojo/runtime",
        "//open-source/mojo/stdlib/stdlib",
    ],
    target_compatible_with = select({
        "//:tsan": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    tools = [
        "//KGEN/tools/kgen",
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/kgen-translate",
        "//KGEN/tools/llvm-module-split",
        "//KGEN/tools/mojo",
    ],
)

lit_tests(
    name = "test_stdlib_srcs",
    # This tests require the stdlib and mlirc srcs, where other tests do
    # not require them
    srcs = [
        "canonicalize-custom-ops.mojo",
        "multiresult_asm_mma.mojo",
    ],
    data = glob(["inputs/**/*.mojo"]) + [
        "//KGEN:CompilerRT",
        "//Kernels/mojo/_mlir:_mlir_srcs",
        "//open-source/mojo/stdlib/stdlib:stdlib_srcs",
        "@llvm-project//compiler-rt:orc_rt",
    ],
    env = {
        "MODULAR_MOJO_IMPORT_SRCS": "$(locations //Kernels/mojo/_mlir:_mlir_srcs) $(locations //open-source/mojo/stdlib/stdlib:stdlib_srcs)",
    },
    mojo_deps = [
        "//open-source/mojo/stdlib/stdlib",
    ],
    tools = [
        "//KGEN/tools/kgen",
        "//KGEN/tools/kgen-opt",
        "//KGEN/tools/kgen-translate",
    ],
)

pkg_files(
    name = "test_python",
    srcs = [
        "mojo-build-python.mojo",
    ],
    renames = {
        "mojo-build-python.mojo": "test_python.mojo",
    },
    visibility = ["//visibility:public"],
)
